configs/platforms/ubuntu-15.10-amd64.rb
configs/platforms/ubuntu-15.10-i386.rb

before this commit the location of the service directory
for systemd was incorrect and puppet installs on ubuntu wily
failed trying to load puppet.service. this commit changes
the servicedir for systemd on both wily installs to the
correct path

(PA-135) Can't manage puppet service on ubuntu wily

---

configs/components/curl.rb
configs/components/openssl.rb
configs/components/puppet-ca-bundle.rb
configs/components/runtime.rb
configs/platforms/win-2012-x64.rb
configs/platforms/win-2012-x86.rb
configs/projects/puppet-agent.rb
resources/patches/openssl/openssl-mingw-do-not-build-applink.patch

This initial commit adds in the base work to build the puppet-agent project on windows, and modifies the curl, openssl, puppet-ca-bundle and runtime components to run on windows.

(RE-6013, RE-6012, RE-6116, RE-611) Build OpenSSL, Curl, and our ca certs for windows

---

README.md

The Windows build example was incorrect and did not work

(docs) Fixed Windows build example

---

configs/projects/puppet-agent.rb

We currently have duplicate entires for eos settings. This is confusing
and unnecessary. This commit removes the duplicate entries.

(maint) Remove duplicate settings

---

configs/components/windows_puppet.json

- In 418268e a commit was introduced for stable to track stable.
In 0270b3a that was reverted for some reason, and stable began to
track puppet_for_the_win#master.  Let's set this back to stable.
- Note that releases 1.3.2, 1.3.1, 1.3.0, 1.2.7, etc were all
properly pinned to the appropriate version tag in puppet_for_the_win

(maint) Track puppet_for_the_win#stable

---

configs/components/libxml2.rb

Per http://www.xmlsoft.org/news.html, we should update
libxml2 2.9.3 that will be shipped with puppet-agent
(currently only in master). This commit updates the
md5 sum of and version number for the libxml2
component

(PA-100) Update version of libxml2 built in puppet-agent

---

configs/components/rubygem-mini_portile.rb
configs/components/rubygem-net-netconf.rb
configs/components/rubygem-net-scp.rb
configs/components/rubygem-nokogiri.rb

This adds component definitions for the following gems:
* net-netconf
* net-scp (dependency of net-netconf)
* nokogiri (dependency of net-netconf)
* mini_portile (dependency of nokogiri)
These gems will be included in the Huawei agent package.

(HUAWEI-2) Add ruby gems for net-netconf and depdencies

---

bin/build-facter.ps1
bin/build-leatherman.ps1
bin/build-windows.rb
configs/components/facter.rb
configs/components/leatherman.json
configs/components/leatherman.rb
configs/projects/puppet-agent.rb

This enables us to un-vendor leatherman from all of our individual
projects. Until those projects are ready to consume an external
leatherman install, this will go unused. We can't remove the vendoring
until we have this in place in P-A, though.

(PA-131) Add leatherman as its own component

---

configs/components/leatherman.rb

Becasue we're setting multiple environment variables for testing, we
need to use `env` to set them. Unfortunately, the null test case was
using `:`, which is a shell built-in. Using `/bin/true` instead of `:`
allows env to run (doing nothing)

(maint) Use /bin/true instead of : for the null-test-run in leatherman

---

configs/components/curl.rb
configs/components/openssl.rb
configs/components/puppet-ca-bundle.rb
configs/components/ruby-stomp.rb
configs/components/ruby.rb
configs/components/rubygem-deep-merge.rb
configs/components/rubygem-ffi.rb
configs/components/rubygem-minitar.rb
configs/components/rubygem-net-ssh.rb
configs/components/rubygem-win32-dir.rb
configs/components/rubygem-win32-eventlog.rb
configs/components/rubygem-win32-process.rb
configs/components/rubygem-win32-security.rb
configs/components/rubygem-win32-service.rb
configs/platforms/win-2012-x64.rb
configs/platforms/win-2012-x86.rb
configs/projects/puppet-agent.rb
resources/patches/ruby/windows_fixup_generated_batch_files.patch
resources/patches/ruby/windows_remove_DL_deprecated_warning.patch
resources/patches/ruby/windows_ruby_2.1_update_to_rubygems_2.4.5.1.patch
resources/patches/ruby/windows_ruby_2.1_update_to_rubygems_2.4.5.patch
resources/patches/rubygem-win32-service/PUP-4390-win32-service-0.8.6-restore_win_2003_compat.patch

This PR mainly updates the windows feature branch to build ruby and individually manage all required rubygems.
This PR also fixes a few assumptions that were incorrect prior to this.
1) Ruby expects the ca cert pem file to be in the openssl prefix directory. There may be a way to specify a custom location during the configure, but I have yet to figure out what that is.
2) We should be defaulting to cygwin make rather than mingw make. We call out to shell in a few places in the makefile, and if we're running the makefile with mingw make, these shell calls don't really do anything, or they just spin. It's also simpler to default to cygwin make and override with mingw make if the need arrises.

(RE-5733, RE-5734) Build ruby and rubygems on windows

---

configs/components/ruby-stomp.rb
configs/components/rubygem-deep-merge.rb
configs/components/rubygem-ffi.rb
configs/components/rubygem-hocon.rb
configs/components/rubygem-minitar.rb
configs/components/rubygem-net-ssh.rb
configs/components/rubygem-win32-dir.rb
configs/components/rubygem-win32-eventlog.rb
configs/components/rubygem-win32-process.rb
configs/components/rubygem-win32-security.rb
configs/components/rubygem-win32-service.rb
configs/projects/puppet-agent.rb

For windows, there is no reason we have GEM_HOME defined in the cygwin
path format. We shouldn't be converting it to a windows style path every
time we need it. Instead, we make sure it's a windows style patch from
the get-go.

(maint) Set GEM_HOME in project

---

bin/build-cpp-pcp-client.ps1
bin/build-facter.ps1
bin/build-pxp-agent.ps1
bin/build-windows.rb
bin/windows-env.ps1
bin/windows-toolset.ps1

Prior to this commit, we were building facter, pxp-agent, and
cpp-pcp-client with an outdated version of openssl and with a ruby that
was linked against the same outdated version of openssl.
Given that we are building everything else with a much more recent
version of openssl, we really really should continue to use that.
This commit also updates the paths that facter searches when linking.
We need to ensure all our dependency directories are included in the
search path, including openssl and ruby. This ensures facter will find
and correctly link against those libraries.
This commit addresses CVE-2015-7551

(PA-138) Build native software on windows with secure components

---

configs/platforms/aix-5.3-ppc.rb
configs/platforms/aix-6.1-ppc.rb
configs/platforms/aix-7.1-ppc.rb

This commit enables the vanagon hardware engine for AIX builds by
specifying a specific builder to use. The hardware engine produces a
lock so that other builds/tests do not trample on the instance being
used during the build. Right now we're only specifying one host, but
this could easily be multiple if we had the builders available.

(PA-140) Specify builders for AIX targets

---

configs/components/windows_ruby.json

Ruby was rebuilt with a newer version of openssl. Use those for windows
puppet-agent builds.

(RE-6194) Use updated ruby builds

---

Gemfile

AIX builders now use a build_host method that is only available
in vanagon 0.5, this commit simply bumps vanagon to 0.5 to
remedy the issue

(PA-156) bump vanagon to 0.5.0 to fix failing AIX builders

---

configs/components/augeas.rb
configs/components/facter.rb
configs/components/openssl.rb
configs/platforms/huaweios-6-ppce500mc.rb

This removes obsolete code referring to HuaweiOS when it was targeted for
WRL/RPM.

(maint) Remove obsolete definitions for huaweios

---

configs/platforms/cumulus-2.2-amd64.rb
configs/platforms/debian-6-amd64.rb
configs/platforms/debian-6-i386.rb

prior to this commit we did not ensure Debian Squeeze and Cumulus 2.2
was provisioned with rsync ( which is a requirement of Vanagon ).

(maint) provision Debian platforms with rsync

---

ext/build_defaults.yaml

Add ubuntu 15.10 to foss whitelist for shipping to nightlies.

(PA-142) Add ubuntu 15.10 to foss whitelist

---

configs/components/leatherman.rb

This was originally put here to deal with environment variables on
solaris. We don't actually require it though.
This is currently only causing problems on windows when we deal with
different environments. `env` isn't available in the windows
environment, only in cygwin. So this fails when we need to exclude
everything cygwin from the path.

(maint) Remove `env` from Leatherman tests

---

bin/build-windows.rb
bin/windows-env.ps1
configs/components/windows_ruby.json

To address CVE-2015-7551 we need to update from ruby 2.1.7 to ruby
2.1.8.

(RE-6143) Use ruby 2.1.8 with windows

---

configs/platforms/osx-10.10-x86_64.rb

During provisioning we update the CLT on OSX.  Apple has removed 7.1
for OSX 10.10 and has made 7.2 available.  This commit updates the
provisioning process to install 7.2.

(maint) bump Xcode CLT to 7.2 on OSX 10.10

---

configs/components/dmidecode.rb

We build our own dmidecode. This ships 3 items in the bin directory, but
we only need dmidecode for the puppet-agent package. So, this removes
vpddecode and biosdecode.

(PA-40) Remove unneeded binaries from dmidecode

---

configs/components/facter.rb
configs/components/openssl.rb
configs/components/runtime.rb

The version of pl-gcc that is currently used in the solaris 10
build does not properly set the library rpath, leading to issues
if the user has an incompatible build of GCC in their default system
library path.
This updates to a more recent build that sets the rpath correctly.
The issue was fixed in the pl-build-tools repo a while back, but
puppet-agent was never updated to use the newer build.
The version of GCC itself does not changed, just the linker flags passed
to the build.

(PE-13590) Update pl-gcc build to fix solaris 10 linking

---

bin/build-cpp-pcp-client.ps1
configs/components/cpp-pcp-client.rb

With this commit, we add leatherman's path to cpp-pcp-client's
CMAKE_PREFIX_PATH and we require leatherman's package when building
cpp-pcp-client.
Those changes are required after removing leatherman's git submodule
from cpp-pcp-client.

(PCP-209) Remove leatherman git submodule from cpp-pcp-client

---

bin/build-pxp-agent.ps1
configs/components/pxp-agent.rb

With this commit, we add leatherman's path to cpp-pcp-client's
CMAKE_PREFIX_PATH and we require leatherman's package when building
pxp-agent.
Those changes are required after removing leatherman's git submodule
from pxp-agent. Note that cpp-pcp-client's submodule has been removed as
well but no change in puppet-agent's build scripts should be necessary
since cpp-pcp-client dependency is managed directly.

(PCP-209) Remove leatherman git submodule from pxp-agent

---

configs/components/libxslt.rb
configs/components/openssl.rb
configs/components/virt-what.rb
configs/platforms/el-7-ppc64le.rb

With this change I can successfully build puppet-agent on RHEL 7.2 ppc64le.
I suspect there is a better way to implement the changes libxslt.rb and virt-what.rb. I'll gladly update this patch set.
I plan on submitting upstream bug reports requesting config.guess gets updated in virt-what and libxslt.

ppc64le support

---

configs/platforms/windows-2012r2-x64.rb
configs/platforms/windows-2012r2-x86.rb

The win-2012r2-x86_64.make pooler template has been switched to live
production, so windows platform needs updating.
See RE-6093

(MAINT) Update win-2012 Pooler template reference

---

configs/platforms/windows-2012r2-x64.rb
configs/platforms/windows-2012r2-x86.rb

This reverts commit ed102cfc352ce1fecc76880dd95f1287970d7b7a.
Necessary until we resolve the Jenkins/CI build issues with the new template.

Revert "(MAINT) Update win-2012 Pooler template reference"

---

configs/components/facter.json
configs/components/hiera.json
configs/components/puppet.json

this will update tags for puppet (to 4.3.2)
hiera (to 3.0.6) and facter (to 3.1.4)

(PA-148) update component tags for 1.3.3 release

---

configs/components/windows_puppet.json

Tags for puppet_for_the_win have been pushed
for the recent update to puppet 4.3.2, this
commit remedies the reference in puppet-agent
to puppet_for_the_win

Update the tag for puppet_for_the_win

---

configs/components/cpp-pcp-client.json
configs/components/puppet-ca-bundle.json

For posterity we would like to make sure all ref: fields
in puppet-agent components all look the same: i.e. each
component json has ref:"refs/tags/####" not just
ref:"####"

Fix ref: fields in puppet agent to match

---

bin/build-windows.rb

This fix is a side-effect of the Windows/Vanagon build upgrade work,
where the new "win-2012r2-x86_64" pooler template caused the existing
pxp-agent/puppet-agent builds to hand in the pipeline (see RE-6093).
The hangs only occurred when running from Jenkins and were thought to be
related to the ssh/TERM handling as the actual hang occurred during a
remote-ssh command to install the cmake package on the target pooler
windows machine.
The updated pooler template had some additional cygwin packages added
which required a general cygwin package refresh. This caused the pooler
machine ssh version to update from Version "SSH-2.0-OpenSSH_6.5"  to
Version "SSH-2.0-OpenSSH_7.1"
While it is not clear why this should cause the hang, it is assumed that
the problem was related to Pseudo-tty handling …

(RE-6286) Set -T instead of -t for remote_ssh cmd

---

configs/components/cpp-pcp-client.json

Previously puppet-agent#stable was tracking cpp-pcp-client#master,
which led to a little confusion. There's room for discussion about
how we want to handle internal components that do *not* have promoting
pipelines (e.g. branches or tags), and right now cpp-pcp-client is
the only example of such. But for now, this is more consistent with
what puppet-agent does for most other internal components.

(maint) Track the stable branch of cpp-pcp-client

---

configs/components/ruby.rb
resources/files/windows/elevate.exe.config

This is an executable compiled by Josh Cooper and used to run our
projects interactively
We need elevate.exe.config to allow elevate.exe to run against .NET 4.
See
puppetlabs/puppet-win32-ruby@70847bd
and PUP-1951 for more information.
elevate.exe is used to run our project with elevated permissions. This
doesn't work in a cygwin environment, but otherwise allows facter and
puppet to request UAC elevation and run in a command prompt window with
administrator privileges.

(maint) Add elevate.exe to ruby on windows

---

configs/components/shellpath.rb

On cisco-wrlinux-5 scripts must be set as executable to be processed.  This commit also changes the scripts from configfile to normal file as these should not be considered protected configuration bits.

(PA-162) set shellpath executable on cisco-wrlinux-5

---

configs/components/cpp-pcp-client.json
configs/components/puppet-ca-bundle.json
configs/components/pxp-agent.json

Prior to this, some components were accessing github over SSH which is
something that most of the world can't do. This commit changes to using
the public URIs. Thus removing one of many issues when trying to build
puppet-agent outside of Puppet Labs.

(PA-185) Use publicly available URIs for git clone

---

configs/components/puppet.rb
resources/files/windows/environment.bat

In puppet-agent on windows, we need to install environment.bat so our
batch files can have access to a cohesive group of environment
variables, etc. This commit adds that.

(PA-187) Install environment.bat on windows

---

configs/components/puppet.rb

In install.rb, the check-prereqs flag will check the system we are
running on and check to see if our requirements for install are
available. This requires that facter can run on the build system. This
is generally fine except when we are cross compiling. This flag also
enables some windows-specific functionality.
Because we need the extra functionality only on windows, we only need to
set this flag for windows. Everything else, including systems we cross
compile on, shouldn't need to check prereqs

(maint) Only check reqs on windows

---

configs/components/facter.rb
configs/platforms/osx-10.10-x86_64.rb
configs/platforms/osx-10.11-x86_64.rb
configs/platforms/osx-10.9-x86_64.rb

This PR attempts to remove external build dependencies on OSX.
* The required CLT updates are now installed via a DMG that is hosted locally.  
* brew is now installed from a tar ball that is hosted locally, a private tap has been created for required build tools, and a local bottle mirror is utilized.  The build tool formulas for versions we require were pulled from upstream and only slight modifications were made ( update/add checksum for bottles if required and default to build yaml-cpp with static libs ).
* A wrapper script is utilized to assist in installing packages via the OSX installer ( for DMGs such as the CLT ) and brew ( for build dependencies ).  All necessary bits are currently hosted on pl-build-tools.
There's certainly opportunity for additional automation here.

(RE-6251,6252) remove external build dependencies on OSX

---

configs/platforms/huaweios-6-ppc.rb

The HuaweiOS environment is based on a containerized instance of
Debian 8, and runs on PPC hardware. We are using the x86_64 debian 8
pooler template to run cross-compiled builds from.

(PA-160) Add platform config for huaweios-6-ppc

---

configs/components/marionette-collective.rb
configs/components/puppet.rb
configs/components/pxp-agent.rb
configs/projects/puppet-agent.rb

Since we need to maintain a consistent set of files in our MSI, we need
to set the pid and log dirs to be consistent locations to what has
already been established.

(maint) Install pid files and log files into ProgramData

---

configs/components/openssl.rb

With this update, the OpenSSL team is no longer packaging their source
code with symlinks. This means we no longer have to do all of our
strange jumping around and editing the upstream tarball to get openssl
to compile on windows. Yay!

(RE-6446) Update to OpenSSL 1.0.2f

---

README.md

I just noticed this. Its just to correct the spelling of the link title.

(MAINT) Fixed spelling mistake in the README.md

---

configs/platforms/windows-2012r2-x64.rb
configs/platforms/windows-2012r2-x86.rb

The cygwin updates for vanagon are now in production, so the VM Pooler
platform needs to be updated.

(MAIN) Point to production Win-2012r2 template

---

configs/platforms/huaweios-6-ppc.rb

HuaweiOS is based on Debian 8 but uses sysv init instead of systemd

(maint) Use sysv init for huaweios

---

configs/projects/puppet-agent.rb

In how things are installed on windows, we need to ensure all our
content is safely nested under the `installdir`. This generally consists
of a format like `Program Files\company\project`. So, to both conform
with this outline and to maintain parity with the existing puppet-agent
packages, this commit assumes the installdir will be
`ProgramFiles\PuppetLabs\Puppet`, which means our main bindir will be
`ProgramFiles\PuppetLabs\Puppet\bin` and the bindir will everything in
it will be `ProgramFiles\PuppetLabs\Puppet\puppet\bin`.

(maint) Nest prefix under Puppet on windows

---

configs/components/facter.json
configs/components/pxp-agent.json

Merging master to stable left two components - facter and pxp-agent -
unable to update independently. The old SHAs use a vendored Leatherman,
but a flaw in how they added Leatherman include directories means the
installed Leatherman causes a conflict. That would be fine if it were
just one (that one would pass on update), but since two components have
that issue the one not being updated will cause a build failure.
Update them concurrently to the latest SHA to bypass the issue.

(maint) Update conflicting components after merge-up

---

configs/components/pxp-agent.rb

When installing a fresh puppet-agent package on a debian-based system,
our services will be enabled but not running by default. This means that
on restart, our services will start running. This goes against what
happens on rpm systems, which do not start services by default.
This is fine for the most part, but given pxp-agent is a new product and
is not usable outside of PE, we want to ensure it is disabled by default
on a fresh install.
This will not impact users who are upgrading. If they have the pxp-agent
service running, it will restart. If they have the service disabled, it
will remain that way.

(PA-141) Don't enable pxp-agent service on install

---

README.md

on Jan 22 2015, Melissa stated:
> The aardwolf branch is no longer is use. Releases in the current series are cut from the stable branch.
As someone that was trying to build puppet-agent, the references to the aardwolf branch mislead me. 
I figured this patch could start the discussion to updating the readme removing the references to aardwolf.

remove references to aardwolf branch

---

configs/components/openssl.rb

This will update the puppet-agent openssl to 1.0.2g in order
to facilitate fixes for the openssl march CVEs
build succeeded at http://jenkins-release.delivery.puppetlabs.net/job/vanagon_generic_job/310/

(RE-6663) Update openssl for march CVEs

---

configs/components/windows_ruby.json

This is to address the March 2016 OpenSSL CVEs.

(maint) Use ruby built against OpenSSL 1.0.2g

---

configs/components/cpp-pcp-client.rb
configs/components/facter.rb
configs/components/leatherman.json
configs/components/leatherman.rb
configs/components/pxp-agent.rb

wrlinux is an embedded environment that does not have full locale support. We shouldn't be attempting to do i18n there.
This requires Leatherman 0.4.2, which we plan to tag Monday. The only change in 0.4.2 will be the necessary support for disabling using locales on Linux variants that don't properly support it.

(PA-242) Disable boost::locale on cisco wrlinux 

---

configs/components/marionette-collective.rb
configs/components/puppet.rb
configs/components/pxp-agent.rb
configs/projects/puppet-agent.rb
resources/windows/wix/service.mcollective.wxs.erb
resources/windows/wix/service.puppet.wxs.erb
resources/windows/wix/service.pxp-agent.wxs.erb

This is the initial set of service specific files to support the Puppet
Agent Vanagon Windows build.
This PR replaces https://github.com/puppetlabs/puppet-agent/pull/514/

(RE-6640) Service Specific Files for Vanagon

---

resources/windows/wix/service.mcollective.wxs.erb
resources/windows/wix/service.puppet.wxs.erb
resources/windows/wix/service.pxp-agent.wxs.erb

tl;dr: the way we currently do services is bad, it reqiures users know how vanagon autogenerates some values, so I changed it so they can just call in to vanagon for the stuff they need. 
Requires Vanagon PR: https://github.com/puppetlabs/vanagon/pull/312

(maint) Update Services for windows

---

README.md

Aardwolf no longer exists, and the instructions specify a merge from
stable to master. So restore json files to master versions, not
aardwolf. Windows Ruby is always tagged, so don't revert newer commits.

(docs) Update README merge instructions

---

configs/components/ruby.rb
configs/projects/puppet-agent.rb

Prior to this commit, puppet-agent builds for Solaris
10 SPARC frequently fail with a ruby segfault. These
builds (which are cross-crompiled), currently use
openscsw's ruby 1.9 (currently 1.9.3p0) in lieu of a
a miniruby.
This commit updates Solaris 10 SPARC to use opencsw's
ruby 2.0 (currently 2.0.0p594) instead of ruby 1.9
during Solaris 10 SPARC builds.

(RE-6217) Use Ruby 2.0 during Solaris 10 SPARC builds

---

Gemfile

0.5.3 has some fixes for solaris service management on upgrades
and adds vanagon retries to certain operations

Update vanagon to 0.5.3

---

configs/components/augeas.rb
configs/components/cpp-pcp-client.rb
configs/components/curl.rb
configs/components/dmidecode.rb
configs/components/facter.rb
configs/components/leatherman.rb
configs/components/libedit.rb
configs/components/libxml2.rb
configs/components/libxslt.rb
configs/components/pxp-agent.rb
configs/components/ruby.rb
configs/projects/puppet-agent.rb

This should explcitly target `core2` as the chipset to optimize for
at compilation time. That will hopefully help move along the
"illegal instruction" problem we've been seeing.

(PA-181) Explicitly specify -march for OS X builds

---

configs/components/virt-what.rb

virt-what needs the --host option to specify the platform for cross
compiling, so previously this never actually worked. This commit
adds the proper --host flag and sets PATH/CFLAGS/LDFLAGS for huaweios.
I've tested this with the huaweios agent build and it now builds a binary for powerpc. I did *not* touch the el-7 powerpc64 configuration as I don't even believe it includes the necessary cross-toolchain so I can't fully test that. It looks like that platform was added by a community member.

(maint) fix cross-compiling of virt-what

---

configs/platforms/huaweios-6-powerpc.rb
configs/projects/puppet-agent.rb

The addition of binutils-powerpc-linux-gnu is necessary for the debian
packaging to be able to find the target arch strip command. I cannot
force debuilder to pass along a modified PATH environment to dh_strip,
so the distro version of binutils is required for this instead of our
pl-binutils.
This PR depends on [PR-322](https://github.com/puppetlabs/vanagon/pull/322) getting merged into vanagon first.

(RE-6520) Build the huaweios package as powerpc instead of noarch

---

configs/projects/puppet-agent.rb

The cascading if/else for setting CFLAGS could lead to more than one situation
no LDFLAGS are set or the standard LDFLAGS are duplicated in each conditional.
We can improve this by setting broad, generally correct defaults and then only
adding to them or changing them as needed. This also eases the pressures that
likely led to a cascading if/else statement.

(PA-181) Simplify/correct CFLAGS and LDFLAGS logic

---

resources/windows/wix/componentgroup.wxs.erb
resources/windows/wix/users.wxs.erb

Normally the puppet services are run under LocalSystem, but the User
settings allow it to be overridden so that for example a Domain account
can be configured to run the services

(RE-6507) Add USER_ACCOUNT Wix definitions

---

configs/projects/puppet-agent.rb

This reverts commit 4eb0a5ac918d260ca4bcc6e94badc0daaf1b8751, reversing
changes made to c8e7924a7809628ee2d1ea9901e8d4b2e771eadc.
Causing breakage in libxml2 on osx

Revert "Merge pull request #581 from mckern/PA-181/explicit-march"

---

bin/build-facter.ps1

Declare the Facter CMAKE_INSTALL_PREFIX and RUBY_LIB_INSTALL locations
in preparation for FACT-1294, when they'll be used to generate a
relative lookup path from facter.rb to libfacter.so.

(PA-252) Declare Facter install and Ruby vendordir locations

---

configs/platforms/windows-2012r2-x64.rb
configs/platforms/windows-2012r2-x86.rb

The MSI packaging process is in a state where it's possible
to build an MSI straight out of the box with no changes to
vanagon or any configs. We now need MSI to be the default
type of windows build

(maint) update the windows plat definitions to msi

---

resources/windows/wix/registryEntries.wxs.erb

puppetres.dll now resides in [INSTALLDIR]puppet/bin, so the event log
registry key
(SYSTEM\CurrentControlSet\services\eventlog\Application\Puppet) needs
updated to this directory.
Note - this change is still under some discussion - i.e. whether using
the Ruby install.rb is correct in the build for windows/vanagon.
This change should be merged in the interim, as at the moment,
puppetres.dll is in the puppet/bin directory, so event log messages
won't work unless the registry entry points to it.

(RE-6793) Update puppetres Registry Key

---

Gemfile

Vanagon 0.5.7 was released it incorporates
some new changes we need for the windows/vanagon
work. this updates the gem to use 0.5.7

(maint) bump vanagon due to new release

---

Gemfile

Downgrading vanagon to 0.5.7 to avoid a showstopper packaging bug on
Linux platforms.

(maint) downgrade vanagon to 0.5.7

---

Gemfile

This is a temporary change since the rubygems.org index cache
is still reporting that vanagon 0.5.8 is available, but now
the gem itself can no longer be downloaded as it was yanked.

(RE-6882) hard-pin vanagon to 0.5.7

---

Gemfile

The stable branch should not follow new vanagon releases unless
explicitly updated in the Gemfile.

(RE-6882) hard-pin vanagon to 0.5.6

---

resources/windows/wix/componentgroup.wxs.erb
resources/windows/wix/environment.wxs
resources/windows/wix/environment.wxs.erb
resources/windows/wix/shortcuts.wxs.erb

This PR contains a number of small fixes to the Vanagon/MSI installer for Puppet Agent to fix defects detected as part of the RE-5735/RE-5736.
Separate commits are used for each ticket and include:
RE-6858 - Add PATH/Environment Variable (Also RE-6857)
RE-6801 - Add Start Menu/App Shortcuts (Also RE-6859)
RE-6860 - Some Inifiles are missing from Installer

(RE-6801) Add Start Menu Shortcuts and other Vanagon/MSI Fixes

---

resources/windows/wix/componentgroup.wxs.erb
resources/windows/wix/wixvariables.wxs.erb

These definitions point to the Image resouces used by the installer UI.
At the moment, the main image is set to the FOSS version of the BMP

(RE-6852) Add Image Resource Variable definitions

---

resources/windows/wix/componentgroup.wxs.erb
resources/windows/wix/condition.wxs.erb

These were missing from the initial windows/msi
The launch conditions prevent the installer from being installed on Windows 2003 or earlier.

(RE-6861) Add Launch Conditions

---

resources/windows/wix/customactions.wxs.erb
resources/windows/wix/sequences.wxs.erb

These Custom actions leaked into to the Vanagon build and should be
removed. They were included for PA-65, but this change was subsequently
removed.

(RE-6863) Remove pxp-agent service custom actions

---

configs/platforms/huaweios-6-powerpc.rb

Previously we were building it as 'jessie', which means the package
will get shipped to the Debian Jessie repo. Instead we want to ensure
the package is shipped to a separate apt repo for huaweios.

(RE-6970) Use huaweios as the codename for the huaweios agent

---

configs/components/facter.rb
configs/components/hiera.rb
configs/components/marionette-collective.rb
configs/components/puppet.rb
resources/files/windows/environment.bat
resources/files/windows/facter.bat
resources/files/windows/facter_interactive.bat
resources/files/windows/hiera.bat
resources/files/windows/mco.bat
resources/files/windows/puppet.bat
resources/files/windows/puppet_interactive.bat
resources/files/windows/puppet_shell.bat
resources/files/windows/run_facter_interactive.bat
resources/files/windows/run_puppet_interactive.bat
resources/windows/wix/shortcuts.wxs.erb

Before this we were planning on keeping the .bat files
that actually execute puppet in windows inside Puppet\puppet\bin
and creating symlinks in Puppet/bin to the .bat files. However
we have since decided that the symlinks are not the way to proceed
since they require custom actions for both install and uninstall
and the act of symlinking is moving away from being windows native.
Thus we elected to move the .bat files entirely to the Puppet\bin
directory and change the contents to point to the correct paths.
This update does the following:
* Adds each .bat file we were using in Puppet-Agent to the actual
Puppet-agent vanagon project. this means those files are now under
the resources/files/windows and we will no longer use those generated
by any of the install.rb scripts.
* AS A SPECIAL …

(RE-6892) Move the .bat files location

---

configs/components/facter.rb

For the windows platform there are cmake flags that
provide variables to facter with paths in them. The
problem is we cannot specifiy any kind of path for
a windows build until after install time finishes
in the MSI. See RE-7004 for a better description
This commit updates the cmake invocation in facter.rb
so it no longer provides those flags for the windows
platform.

(RE-7004) update facter cmake invocation for windows

---

configs/components/facter.rb

Commit 7b4256ab28fcc535e70d1887c991d5525c9f88cc for RE-7004 introduced
a 'special_flags += <stuff>' stanza to separate some functionality
not needed on windows. Unfortunately, special_flags is not defined
at the point the stanza is executed which results in an exception.
This change simply initializes special_flags so it is always defined.

(PA-282) Fix special_flags handling to restore builds on *nix

---

configs/components/ruby.rb
resources/files/rbconfig-powerpc-ibm-aix5.3.0.0.rb
resources/files/rbconfig-powerpc-ibm-aix6.1.0.0.rb
resources/files/rbconfig-powerpc-ibm-aix7.1.0.0.rb

Ruby 2.1.9 contains several fixes for AIX, including
an AIX-specific fix to Ruby's `thread_pthread.c`, which
may fix an intermittent Ruby segfault on AIX.
This commit updates puppet-agent's vendored Ruby to
to 2.1.9, but just for AIX.

(PA-283) Update Ruby to 2.1.9 for AIX

---

configs/components/rubygem-nokogiri.rb

This fixes an intermittent build failure where rubygem-deep-merge
could be installed after nokogiri. As we've found, the only way to
keep nokogiri in line is to ensure it is the *last* gem installed.

(maint) ensure rubygem-deep-merge is built before nokogiri

---

configs/components/dmidecode.rb
configs/projects/puppet-agent.rb

It's unlikely that dmidecode will ever be used on CloudEngine switches, but I have confirmed that the Yocto Project builds dmidecode for powerpc 32 and 64 bit platforms, and this will quiet a warning message that puppet spews during runs when the dmidecode binary is missing.

(HUAWEI-15) Include cross-compiled dmidecode in huaweios builds

---

configs/components/ruby.rb
resources/files/rbconfig-i386-pc-solaris2.10.rb
resources/files/rbconfig-i386-pc-solaris2.11.rb
resources/files/rbconfig-powerpc-linux-gnu.rb
resources/files/rbconfig-sparc-sun-solaris2.10.rb
resources/files/rbconfig-sparc-sun-solaris2.11.rb

Ruby 2.1.9 contains several fixes for AIX, including
an AIX-specific fix to Ruby's `thread_pthread.c`, which
may fix an intermittent Ruby segfault on AIX.
This changeset updates puppet-agent's vendored Ruby to
to 2.1.9.

(PA-283) Update to Ruby 2.1.9

---

resources/windows/wix/registryEntries.wxs.erb
resources/windows/wix/shortcuts.wxs.erb

This replaces "settings[:product_name]" with
"settings[:product_id]" to use the correct name for
names of registry entries
I cannot fix the batch file tickets RE-7018 and RE-7019 until the major change to paths in RE-7027 is complete. so this PR is now just one ticket worth of work

(RE-7021) Update the puppet-msi with fixes

---

configs/components/puppet.rb

Both packages own /etc/puppetlabs/puppet/auth.conf, so this is needed
to ensure that packages get installed/uninstalled in the correct order
on upgrade.

(maint) The puppet component needs to replace pe-puppetserver-common

---

configs/components/cpp-pcp-client.json
configs/components/leatherman.json

Facter fixes on stable require Leatherman 0.6.0. Update to it.

(PA-304) Bump to Leatherman 0.6.1 for Facter bug fixes

---

configs/components/curl.rb
configs/components/puppet-ca-bundle.rb
configs/projects/puppet-agent.rb

And re-enable it on sles-11-s390x.

(RE-7032) Fix puppet-ca-bundle installs on cross-compiled platforms

---

configs/components/ruby.rb
resources/files/rbconfig-s390x-linux-gnu.rb

Our switch to ruby 2.1.9 happened in the midst of me working on
this platform, so bumping it apart from the other platform rbconfigs.

(RE-7099) Update Ruby to 2.1.9 for sles-11-s390x

---

resources/windows/wix/shortcuts.wxs.erb

The batch files that the P-A shortcuts point to live under INSTALLDIR/bin, not
INSTALLDIR/puppet/bin. this needs to be updated

(RE-7029) update the paths to windows shortcuts

---

Gemfile
configs/projects/puppet-agent.rb

windows builds of puppet agent are longer than the standard 1 hour set by the
new vanagon retry logic. we need to extend the timeout.

(PA-308) update timeout for windows

---

configs/components/cfpropertylist.json
configs/components/cfpropertylist.rb

The tarball we use to package this is of unknown provenance and the mixed case has been sort of an annoyance to use with Vanagon's rewrite engine. By switching to a git SHA (specifically for the version we're already using), we should hopefully avoid both of these problems.

(MAINT) Use a SHA reference for CFPropertylist

---

configs/components/cfpropertylist.json

Should have used `cfpropertylist-2.2.7`. Oops.

(MAINT) Fix bad tag for CF Property List

---

configs/components/rubygem-semantic_puppet.rb
configs/projects/puppet-agent.rb

This is currently vendored in puppet and adding it to puppet-agent
will allow us to unvendor and thus to maintain just one copy of the code.

(PA-320) Add semantic_puppet gem to puppet-agent

---

configs/components/leatherman.json

Bumps to a Leatherman version that disables the Leatherman.curl tests
under the puppet-agent build configuration. AppVeyor CI is still testing
using different configurations, but we haven't yet resolved how to use
libcurl stubs with dynamic Leatherman and libcurl. See LTH-70.
/cc @McdonaldSeanp; I'm running a test build locally, I'll update when it finishes.

(PA-321) Bump Leatherman version to resolve test failure on win2012

---

configs/components/hiera.rb
resources/windows/wix/appdatafiles.wxs

For new installations, hiera.yaml will be installed in the puppet_configdir rather than codedir.
For upgrades, if hiera.yaml exists in codedir it will be preserved there.

(PA-287) Move hiera.yaml from codedir to puppet_configdir

---

ext/build_defaults.yaml

It seems that we need to specify deb_targets in order to have packages
promote successfully into PE. The promotion job takes this list of
platforms and will only promote the packages that correspond to this
list somehow. I could very well be wrong in this assertion, but that is
certainly how things seem to work at the moment.

(maint) Add xenial to build targets

---

bin/windows-env.ps1
configs/components/openssl.rb
configs/components/windows_ruby.json

Reverts puppetlabs/puppet-agent#659
The openssl update is causing a test failure, reverting until we fully understand the root cause.

Revert "(RE-7221) Update to OpenSSL 1.0.2h"

---

bin/windows-env.ps1
configs/components/openssl.rb
configs/components/windows_ruby.json

Between openssl 1.0.2g and 1.0.2h, the behavior of the no-ssl2 configure
flag was changed. Previously, no-ssl2 disabled all ssl2 methods. In 1.0.1h,
the methods are no longer disabled, they just return NULL, unless the new
configure flag 'no-ssl2-method' is added. This behavior change was
breaking our tests that ensure ssl2 is disabled.
This adds the no-ssl2-method flag to the openssl build, restoring
the same behavior seen in 1.0.2g: specifically
```
ruby -ropenssl -e "puts OpenSSL::SSL::SSLContext::METHODS.include?(:SSLv2)"
```
will return 'false'

Re-add openssl 1.0.2h and add 'no-ssl2-method' configure flag

---

configs/components/cpp-pcp-client.json

Bump to cpp-pcp-client#stable, the pre-release code for cpp-pcp-client.

(maint) Bump to pre-release cpp-pcp-client

---

configs/components/facter.rb
configs/components/hiera.rb
configs/components/leatherman.rb
configs/components/marionette-collective.rb
configs/components/nssm.rb
configs/components/puppet.rb
configs/components/pxp-agent.rb
configs/components/ruby-stomp.rb
configs/components/ruby.rb
configs/components/rubygem-deep-merge.rb
configs/components/rubygem-ffi.rb
configs/components/rubygem-hocon.rb
configs/components/rubygem-mini_portile2.rb
configs/components/rubygem-minitar.rb
configs/components/rubygem-net-netconf.rb
configs/components/rubygem-net-scp.rb
configs/components/rubygem-net-ssh.rb
configs/components/rubygem-win32-dir.rb
configs/components/rubygem-win32-eventlog.rb
configs/components/rubygem-win32-process.rb
configs/components/rubygem-win32-security.rb
configs/components/rubygem-win32-service.rb
configs/components/runtime.rb
configs/projects/puppet-agent.rb
resources/files/windows/environment.bat
resources/windows/wix/service.mcollective.wxs.erb
resources/windows/wix/service.puppet.wxs.erb
resources/windows/wix/service.pxp-agent.wxs.erb

We are doing a major path change to the current windows Puppet-Agent work. The change itself is actually a reversion to old standards for MSIs. See https://tickets.puppetlabs.com/browse/RE-7027 for details on why we are doing this

Revert to PTFW File Paths

---

configs/components/augeas.rb
configs/components/curl.rb
configs/components/dmidecode.rb
configs/components/libedit.rb
configs/components/libxml2.rb
configs/components/libxslt.rb
configs/components/nssm.json
configs/components/nssm.rb
configs/components/openssl.rb
configs/components/ruby-augeas.rb
configs/components/ruby-selinux.rb
configs/components/ruby-shadow.rb
configs/components/ruby-stomp.rb
configs/components/ruby.rb
configs/components/rubygem-deep-merge.rb
configs/components/rubygem-ffi.rb
configs/components/rubygem-hocon.rb
configs/components/rubygem-mini_portile2.rb
configs/components/rubygem-minitar.rb
configs/components/rubygem-net-netconf.rb
configs/components/rubygem-net-scp.rb
configs/components/rubygem-net-ssh.rb
configs/components/rubygem-nokogiri.rb
configs/components/rubygem-win32-dir.rb
configs/components/rubygem-win32-eventlog.rb
configs/components/rubygem-win32-process.rb
configs/components/rubygem-win32-security.rb
configs/components/rubygem-win32-service.rb
configs/components/virt-what.rb
configs/projects/puppet-agent.rb

Prior to this commit, for anybody not on the Puppet, Inc VPN a person
had to manually gather sources for ~20 items and place them at a
location web accessable and then modify component files to point to that
location just to get started on a build.
Vanagon has had http rewrite rule magic in it for a while. This commit
simply puts the upstream URL in place for primary url on most
components. This should remove the first hour or two of work from any
community member attempting to build out the puppet-agent.
If you're a community member, now you'll simply have to comment out the
rewrite line in configs/projects/puppet-agent.rb
This will not allow community members to build hauwei, or aix due to
other things required that our only on our build infrastructure.
Windows will not work with just …

(PA-186) components should use upstream and rewrite urls

---

configs/components/leatherman.rb

Recently, Solaris builds of Puppet Agent began failing due
to leatherman test failures following the build. These test
errors are due to a locale issue, specifically:
unexpected exception with message:
locale::facet::_S_create_c_locale name not valid
Setting LC_ALL before running `make test` prevents this
issue, though this is a temporary solution. Future
improvements could include attempting to invoke std::locale
early in the execution lifetime, and setting LANG and LC_ALL
if an exception is thrown. Alternatively, these variables
could become part of the environment for tests in CMake.
(Thanks to @MikaelSmith for tracking this down and for the
above suggestions)

(maint) Set LC_ALL=C when running leatherman tests on Solaris

---

configs/components/facter.rb
configs/projects/puppet-agent.rb

Configures Facter to hard-code the AIO_AGENT_VERSION based on the
puppet-agent package version.

(PA-241) Set AIO_AGENT_VERSION fact when building Facter

---

configs/components/nssm.json

nssm.json was removed because the contents of that file were moved into
nssm.rb which vanagon uses. Currently, however, the Windows builds still
use the bin/build-windows command which needs to read information about
nssm from the json file.
Once we move fully to a pure-vanagon build of the Windows MSI, nssm.json
should be removed.

(PA-347) Put back nssm.json

---

configs/components/facter.rb
configs/components/hiera.rb
configs/components/marionette-collective.rb
configs/components/puppet.rb

Now that puppet-agent carries batch files inside it's own project, we need to
specify to the component installers that they do not need to install them.

(RE-7020) Remove extraneous batch files from bin dirs

---

configs/components/facter.rb
configs/components/hiera.rb
configs/components/leatherman.rb
configs/components/marionette-collective.rb
configs/components/puppet.rb
configs/components/pxp-agent.rb
configs/components/ruby-stomp.rb
configs/components/ruby.rb
configs/components/rubygem-deep-merge.rb
configs/components/rubygem-ffi.rb
configs/components/rubygem-hocon.rb
configs/components/rubygem-mini_portile2.rb
configs/components/rubygem-minitar.rb
configs/components/rubygem-net-netconf.rb
configs/components/rubygem-net-scp.rb
configs/components/rubygem-net-ssh.rb
configs/components/rubygem-semantic_puppet.rb
configs/components/rubygem-win32-dir.rb
configs/components/rubygem-win32-eventlog.rb
configs/components/rubygem-win32-process.rb
configs/components/rubygem-win32-security.rb
configs/components/rubygem-win32-service.rb
configs/components/runtime.rb

Ruby links against several DLLs during its own compilation. Some of these DLLs
are also runtime deps, and need to be pulled in after compilation so they will
be included in the ruby we vendor

(RE-7262) Update runtime to pull in dlls + update components to use ruby_bindir

---

configs/components/facter.rb

Make the `aio_agent_version` fact in Facter consistent with that in PE
by excluding the git sha from git describe.

(PA-241) AIO_AGENT_VERSION excludes git sha

---

configs/components/cpp-pcp-client.rb
configs/components/facter.rb
configs/components/leatherman.rb
configs/components/pxp-agent.rb

Enable tests on cpp-pcp-client and pxp-agent (on platforms where they're
expected to pass). Update facter and leatherman to use the
Component#check method for tests.

(maint) Enable tests, use check on all CMake projects

---

configs/projects/puppet-agent.rb

This was apparently lost during a merge, and is needed
for HuaweiOS

(maint) Remove Huaweios exclusion for dmidecode

---

configs/components/puppet.json

This reverts commit 537d75e78ec62bb3c4efafe0ca7be7dcfe191d35.
This version of puppet is breaking ci

Revert "bumping puppet to 0fd9d93d36ff461b6ac7d4d60b97cf3426a691cb"

---

configs/components/leatherman.json

Leatherman 0.7.2 made a few untested changes to a file only tested when
`std::locale` use is disabled. Bump to pick up a fix for that.

(maint) Bump Leatherman to fix platforms with locale disabled

---

configs/components/cpp-pcp-client.rb
configs/components/facter.rb
configs/components/leatherman.rb
configs/components/pxp-agent.rb

This reverts commit 4ac2e2bb747df97dd99ac35f19b7e6564a9dbfb1.
Causing facter test failures with leatherman 0.7.1

Revert "(PA-375) Disable locales on SLES and EL-4"

---

configs/components/cpp-pcp-client.rb
configs/components/facter.rb
configs/components/leatherman.json
configs/components/leatherman.rb
configs/components/pxp-agent.rb

We haven't built our own gettext packages yet, so avoid using them
altogether.

(PA-375) Avoid using gettext

---

configs/components/puppet-ca-bundle.rb

Prior to this commit, facter depended on curl, which depended on
puppet-ca-bundle, which depended on facter. This is bad, since we don't
want circular dependencies in our build systems.
This commit removed that circular dependency by altering
puppet-ca-bundle's requirement on facter. The only reason facter was
listed as a build dependency was to get a list of platforms that had
java installed on them. Though the Makefile for puppet-ca-bundle does
not require java explicitly, this was a means to determine which
platforms would be made available as master platforms. These required
the additional keystore to be available to the puppetserver package. The
original logic behind this decision was to avoid duplication of logic in
determining which platforms to make the keystore available on. …

(PA-349) Remove facter/curl/puppet-ca-bundle circular deps

---

resources/windows/wix/project.wxs.erb

After realizing that project.wxs does not actually constitute a default that
belongs in vanagon, this file should be moved under puppet-agent. Vanagon is
already built to handle this change so no vanagon changes will be required.

(maint) move project.wxs from vanagon to puppet-agent

---

configs/components/leatherman.json

Merge from stable didn't bring over a related Leatherman ref bump to
support new configuration. Update it now.

(maint) Update to correct Leatherman version after merge

---

ext/build_defaults.yaml

Update the pe_platforms list to include sles-11-s390x to include it in nightlies

(RE-6958) Update build-data to include sles-11-s390x

---

ext/build_defaults.yaml

Update the pe_platforms list to include sles-12-s390x to include it in
nightlies

(RE-7178) Update build-data to include sles-12-s390x

---

configs/components/facter.rb

Prior to this commit, there wasn't any verification that we were linking
against our  libstdc++ vs the system-wide library. We'd like to make
sure that we've either statically linked libstdc++ and libgcc_s into our
builds or that we're using the runtime-provided components that would
end up in /opt/puppetlabs/puppet/lib.

(PA-392) Ensure linking against PL libs

---

configs/components/runtime.rb

The recent addition of 'runtime.sh' fails with an
error on OSX. As it's not needed or useful on OSX,
this skips the invocation on those platforms.

(maint) Skip runtime.sh on OSX

---

configs/components/libxslt.rb

Due to failing builds on solaris OSes we are reverting the libxslt version bump
on only solaris platforms. This should be a temporary fix.

(RE-7540) revert libxslt bump back to 1.1.28 on solaris

---

configs/components/facter.rb
configs/components/puppet.rb

due to the legacy build process, puppet-agent and the test suite expect
facter.rb to exist under facter/lib, not the vendor_ruby directory. This commit
uses the ruby_lib_install option of facter's cmake makefile to move that file.

(RE-7407) move facter rb

---

configs/components/facter.json

Reverts puppetlabs/puppet-agent#732
This was not the cause of the issue, we can re-add this ref

Revert "Revert "bumping facter to fbc52a015e94028986ed562edd12da7315c89d28""

---

configs/components/ruby-stomp.rb

Fixes certificate hostname verification

(RE-7301) Update stomp gem to 1.4.1

---

configs/components/marionette-collective.rb
configs/components/puppet.rb

Prior to this, services on AIX are not restarted on upgrade, so
the old puppet and mcollective services may be left running.
This updates puppet-agent's puppet and mcollective component
configurations to save and apply the pre-upgrade service state
for puppet and mcollective (as is done for other RPM platforms 
not using systemd)
Also, on AIX, the system default `install` utility does not create
directories. This commit updates the puppet and mcollective preinstall
actions to use a more portable way of creating the `rpm_statedir`
directories.

(PA-390) On AIX, restart services on upgrade

---

configs/components/libxslt.rb
resources/patches/libxslt/Update-missing-script-to-return-0.patch

Patching the missing script is currently the only way to build on solaris for
1.1.29. This patch will add many warnings on solaris builds, but these seem
harmless and "make check" does not fail, so indications point to clean builds
with this patch.

(RE-7544) patch missing script for libxslt and bump to libxslt 1.1.29

---

Gemfile

This commit bumps the pinned vanagon version to 0.6.3 to pick up a
change for AIX service handling on upgrade.

(PA-390) Bump vanagon to 0.6.3

---

ext/build_defaults.yaml

This commit adds Fedora 23 and 24 to the 'foss_platforms' list, so we
can ship them to nightlies.

(RE-7338) Add Fedora 23 and 24 to 'foss_platforms'

---

configs/components/libxml2.rb
configs/components/rubygem-mini_portile2.rb
configs/components/rubygem-pkg-config.rb

We recently started using upstream component sources in puppet-agent
component source configs.
This commit updates the component configs for `libxml2`,
`mini_portile2`, and `pkg-config` to use the upstream source URLs.

(maint) Use upstream URLs for libxml2, pkg-config, and mini_portile2.

---

configs/platforms/ubuntu-12.04-amd64.rb
configs/platforms/ubuntu-12.04-i386.rb
configs/platforms/ubuntu-14.04-amd64.rb
configs/platforms/ubuntu-14.04-i386.rb

We require fakeroot to build Puppet Agent.  The templates for Ubuntu 12.04 and 14.04 were previously handcrafted and included this package.  By default it is not installed and needs to be explicitly called out to support moving to packer based templates.

(RE-7570) Add rsync and fakeroot to Ubuntu 12.04 and 14.04

---

configs/components/libxslt.rb
configs/components/rubygem-semantic_puppet.rb

We recently started using upstream component sources in puppet-agent
component source configs.
This commit updates the component configs for `semantic_puppet` and
`libxslt` to use the upstream source URLs.

(maint) Use upstream URLs for semantic_puppet and libxslt

---

configs/platforms/ubuntu-12.04-amd64.rb
configs/platforms/ubuntu-12.04-i386.rb
configs/platforms/ubuntu-14.04-amd64.rb
configs/platforms/ubuntu-14.04-i386.rb

We require fakeroot to build Puppet Agent.  The templates for Ubuntu 12.04 and 14.04 were previously handcrafted and included this package.  By default it is not installed and needs to be explicitly called out to support moving to packer based templates.

(RE-7570) Add fakeroot to Ubuntu 12.04 and 14.04

---

configs/components/ruby-stomp.rb

Reverts puppetlabs/puppet-agent#735
Causing problems with PE tests. Patch to come shortly.

Revert "(RE-7301) Update stomp gem to 1.4.1"

---

configs/components/cfpropertylist.json

Previously, we were cloning cfpropertylist using ssh, which requires
ssh authentication and an entry in ~/.ssh/known_hosts. Since the
cfpropertylist repo is public, switch to the git protocol instead.

(maint) Use git protocol instead of ssh

---

configs/components/hiera.rb

This option was added in master hiera, but will not be available until after
the 1.5.3 release

(maint) Update hiera config to not use --no-batch-files

---

configs/components/libxml2.rb

Previously, cross compiled Debians required pl-pkg-config to build
libxml2 but was only referenced in augeas. This commit places the build
requirement in the correct spot (libxml2) and ensures that anything
cross compiled as a Debian system will require pl-pkg-config.
If you just use system pkg-config, the cross compile will fail on some
platforms as the flags returned are incorrect.

(Maint) Fix up pkg-config dependency for cross compiles

---

configs/platforms/fedora-f23-i386.rb

apache fails to start unless it's updated

(maint) Fedora 23 i386 needs an updated libnghttp2

---

configs/components/ruby.rb

If you try to download Ruby 2.3.1 from a Ruby 2.1 URL, you're gonna have a bad time.

(MAINT) Use correct URL for Ruby 2.3.1

---

configs/components/ruby.rb

Both the el-6-s390x and windows platforms are not ready for the 2.3 bump, this
commit should revert some of the ruby work for those platforms to bring them
back in line with 2.1.9.

(RE-7685) (RE-7684) Update ruby to revert el-6-s390, windows

---

configs/components/ruby.rb
resources/patches/ruby/windows_fixup_generated_batch_files.patch

Some missing patch invocations and different patches are out of band with the
original 2.1.9 build. This commit remedies that by reverting to using all the
correct patches for ruby 2.1.9 with windows.

(maint) Update windows to complete revert back to ruby 2.1.9

---

configs/components/rubygem-win32-service.rb

- Version 0.8.7 of the win32-service gem had a bug that prevented it
from properly retrieving all services on Windows 10 with the
Win32::Service.services call.
In particular, the services pvhdparser and vhdparser don't have
delayed start info on Windows 10, which would previously cause
errors.
This is fixed in the 0.8.8 version of the gem

(PUP-6459) Update win32-service to 0.8.8

---

configs/components/windows_ruby.json

- Though future packaging should change to Vanagon based, current
pipelines are still testing with packages produced with the older
process that rely on the puppet-win32-ruby repository.
To verify that the updated win32-service 0.8.8 gem passes through
acceptance properly, update to the latest SHAs at the head of the
2.1.x-x{86|64} branches of puppet-win32-ruby that include
win32-service 0.8.8
Once validated, these SHAs can be turned into tags, and this
component configuration can be updated.

(PUP-6459) Test updated win32-service 0.8.8

---

Gemfile
configs/platforms/cumulus-2.2-amd64.rb
configs/platforms/debian-7-amd64.rb
configs/platforms/debian-7-i386.rb
configs/platforms/debian-8-amd64.rb
configs/platforms/debian-8-armhf.rb
configs/platforms/debian-8-i386.rb
configs/platforms/osx-10.10-x86_64.rb
configs/platforms/osx-10.11-x86_64.rb
configs/platforms/osx-10.9-x86_64.rb
configs/platforms/solaris-10-i386.rb
configs/platforms/solaris-10-sparc.rb
configs/platforms/solaris-11-i386.rb
configs/platforms/solaris-11-sparc.rb
configs/platforms/ubuntu-10.04-amd64.rb
configs/platforms/ubuntu-10.04-i386.rb
configs/platforms/ubuntu-12.04-amd64.rb
configs/platforms/ubuntu-12.04-i386.rb
configs/platforms/ubuntu-14.04-amd64.rb
configs/platforms/ubuntu-14.04-i386.rb
configs/platforms/ubuntu-15.10-amd64.rb
configs/platforms/ubuntu-15.10-i386.rb
configs/platforms/ubuntu-16.04-amd64.rb
configs/platforms/ubuntu-16.04-i386.rb
configs/platforms/windows-2012r2-x64.rb
configs/platforms/windows-2012r2-x86.rb

This vanagon release includes a change to output directories that creates a
default output directory for all platforms with a choice to override the
default. Infrastructure requirements forces us to override the default for:
* Debian based platforms
* solaris platforms
* windows platforms

(maint) Bump vanagon to 0.7.0

---

configs/components/ruby-selinux.rb
configs/components/ruby.rb

Enable proper cross-compilation of ruby-selinux, and remove redundant
include and link flags.

(RE-7660) Fix cross-compilation of ruby-selinux

---

Gemfile

This will update windows packages to be named puppet-agent-VERSION-ARCH.msi and
not puppet-agent-VERSION.RELEASE-ARCH.msi

(maint) Update vanagon to 0.7.1

---

configs/components/ruby.rb
resources/files/ruby/windows_ruby_gem_wrapper.bat
resources/patches/ruby/update_rbinstall_for_windows.patch

Windows builds of the vendored ruby will incorrectly create batch files using
old legacy rbinstall code. This commit patches out the old legacy code and
keeps creation of ruby wrappers in line with what rubygems will do.

(maint) Update ruby congifuration for windows

---

configs/components/libxslt.rb
configs/projects/puppet-agent.rb

This removes unused code from the libxslt component that was intended
to specify the target build architecture, but actually does nothing. The
correct way to specify the target is with the --host flag, which is
already set via the settings[:host] option.

(RE-7449) libxslt component refactor

---

configs/components/rubygem-ffi.rb

windows is still operating with ruby 2.1.9, which requires ffi 1.9.10, not
1.9.14. revert back to 1.9.10

(maint) Revert ffi to 1.9.10 for windows

---

configs/platforms/osx-10.10-x86_64.rb
configs/platforms/osx-10.11-x86_64.rb
configs/platforms/osx-10.9-x86_64.rb
resources/patches/osx/0001-libcxx_include_memory_fix.patch
resources/patches/osx/0002-libcxx_include_memory_fix.patch
resources/patches/osx/0003-libcxx_include_memory_fix.patch

Prior to this commit, cpp-hocon builds fail on OS X due to a known issue
(https://llvm.org/bugs/show_bug.cgi?id=18843) in an earlier version of
the libc++ headers shipped with LLVM (in the Xcode Command Line Tools).
This issue is fixed in Xcode Command Line Tools 7.3.
This changeset updates the OS X 10.11 platform config to use Xcode Command
Line Tools 7.3.1, the current version for OS X 10.11.
Unfortunately, installation of Xcode CLT 7.3 is blocked on OS X 10.9 and 10.10. 
As a workaround, this changeset updates puppet-agent's OS X 10.9 and 10.10 
platform configurations to patch libc++'s 'include/memory' header as a
provisioning step before the build.

(RE-7667) OSX: Update 'include/memory' header for libc++ bug

---

resources/patches/ruby/aix_ruby_2.1_libpath_with_opt_dir.patch

It needed to be updated for 2.3, this commit reverts it to work for 2.1.9

(maint) revert AIX ruby patch to work for 2.1.9

---

configs/components/ruby.rb

Due to issues trying to statically link libgcc on windows x86, we are going to
dynamically link that lib and copy it over to the ruby bindir.

(maint) Update ruby to use dynamic linking

---

configs/components/ruby.rb

Somehow this build option fell through the cracks.

(maint) Add -O3 back to ruby optflags environment for windows

---

configs/components/puppet.json

This resets the Puppet SHA to a version before corrective change
landed. This will let us get a clean build to the PE integration team
while we sort out what we're going to do in corrective change land.
This can't be our final shipping SHA since it's missing some other
fixes, but it should be good enough to unblock the integration team.

(maint) Reset puppet to a pre-corrective-change-reporting SHA

---

resources/files/windows/environment.bat

- Previously, the SSL directory was configured improperly in the
environment.bat that was in the package.  The resulting values were:
SSL_CERT_DIR=C:\Program Files\Puppet Labs\Puppet\ssl\certs
SSL_CERT_FILE=C:\Program Files\Puppet Labs\Puppet\ssl\cert.pem
This is not the location of the cert.pem file.  The actual location is:
C:\Program Files\Puppet Labs\Puppet\puppet\ssl\cert.pem
- Adjust the batch file to use the appropriate directory

(PA-461) Configure OpenSSL cert bundle on Windows

---

resources/files/windows/environment.bat

In commit 24f8e0d we introduced a different path for
FACTER_env_windows_installdir - it used to "C:\\Program Files\\Puppet
Labs\\Puppet" but now goes to "C:\\Program Files\\Puppet Labs\\Puppet\\facter".
This commit fixes this. The impact is that in PE, the aio_agent_build fact uses
this fact to create the path to the VERSION file - without it, no
aio_agent_build fact is reported, causing CI pipelines to fail.

(PA-466) Correct env_windows_installdir

---

configs/components/puppet.rb

The Version file for puppet-agent needs to exist under Puppet Labs\Puppet\ not
Puppet Labs\Puppet\puppet. Update packaging to copy the file there.

(PA-466) Update packaging to copy VERSION to installdir

---

configs/platforms/windows-2012r2-x64.rb
configs/platforms/windows-2012r2-x86.rb

This updates the platform triple of windows builds to be:
i686-w64-mingw32
or
x86_64-w64-mingw32
instead of: i686/x86_64-unknown-migw32
This is meant to fix some gem loading for gems that expect this platform triple
inside ruby.

(PA-475) Update windows platform triple to include w64

---

.travis.yml
Rakefile

We want to make sure we aren't using private projects in our commit
messages. This will allow maint, doc, docs, packaging, pa, and cpr

(maint) Add commit checks

---

resources/windows/wix/properties.wxs.erb
resources/windows/wix/registryEntries.wxs.erb

The Wix files that read and write registry entries during upgrade to remember
preferences were writing the remembered properties to the wrong place
(HKLM\SOFTWARE\Puppet Labs\Puppet). This commit updates them to write to the
correct key location (HKLM\SOFTWARE\Puppet Labs\PuppetInstaller).
This commit also adds extra registry searches for the incorrect location
of the keys so we can still pull preferences from the incorrect locations
in the 1.6.2 release when upgrading from 1.6.1 to 1.6.2

(PA-496) Update Registry entries to write to the correct place

---

configs/components/ruby.rb

The removal of the parallel make was made during dev for ruby 2.3, and should
have been added back.

(maint) Re-add the -j flag to make during ruby build

---

ext/build_defaults.yaml

This commit updates the key that is used to sign packages. We are
in the process of introducing a new signing key to verify our packages.
As a part of this effort, we need to actually switch over to this new
key for our individual projects.

(maint) Upgrade to new signing key

---

MAINTAINERS

This commit adds an empty maintainers file to puppet-agent in the specification
described by https://github.com/puppetlabs/maintainers. This file will be used
to record the active maintainers of the repository.

(MAINT) Add a maintainers file

---

MAINTAINERS

This commit adds an empty maintainers file to puppet-agent in the specification
described by https://github.com/puppetlabs/maintainers. This file will be used
to record the active maintainers of the repository.
This PR builds on https://github.com/puppetlabs/puppet-agent/pull/837, which adds the MAINTAINERS file - that should be merged first.

(maint) Add moses as maintainer

---

configs/components/facter.json
configs/components/hiera.json
configs/components/marionette-collective.json
configs/components/puppet.json
configs/components/pxp-agent.json

This will also update the SHA of the puppet component to the latest of https://github.com/puppetlabs/puppet/tree/4.7.x

(PA-540) retag all components not updating in 1.7.0

---

configs/components/cpp-pcp-client.rb
configs/components/facter.rb
configs/components/leatherman.rb
configs/components/pxp-agent.rb

Previously facter and pxp-agent set CMAKE_INSTALL_RPATH to ensure rpath
is set when installing to non-default locations. Packaging relies on
this to get the correct rpath configuration. Leatherman was missing this
configuration, which was exposed when moving to dynamically linking
against `libstdc++`.
Fix link paths by explicitly setting RPATH for all CMake projects
(in conjunction with settings in the toolchain fails, in accordance with
https://cmake.org/Wiki/CMake_RPATH_handling's "Always full RPATH"
scenario). Also explicitly set LD_LIBRARY_PATH/LIBPATH for test
executables, as they won't have the correct rpath for `libstdc++`.

(PA-495) Set library paths for CMake projects explicitly

---

configs/components/leatherman.rb

A previous commit to move Leatherman unit tests to the `check` command
missed preserving the hard-coded LANG and LC_ALL variables for tests on
Solaris 10. Restore them.

(maint) Restore setting locale for LTH tests on Solaris 10

---

configs/components/ruby.rb

Gem path changes between Ruby 2.1 and 2.3 cause issues for a few
components shipped in PE < 2016.3.
To prevent unintended installation of puppet-agent with Ruby 2.3.1 on
earlier PE versions, this commit adds versioned conflicts for
`pe-puppet-enterprise-release`, `pe-installer`, `pe-r10k`, and
`pe-client-tools`.

(PA-542) Add conflicts with PE < 2016.3 components

---

configs/components/puppet.json

The old SHA was from the 4.7.x branch, which contained the correct commits,
however during the mergup after the release will dirty up the commit history.
Stable has been cleaned up and is ready to go in to the RC

(maint) move the puppet component SHA to stable

---

ext/build_defaults.yaml

This commit updates the key that is used to sign packages. We are
in the process of introducing a new signing key to verify our packages.
As a part of this effort, we need to actually switch over to this new
key for our individual projects.

 (PA-537) Upgrade to new signing key

---

configs/components/ruby.rb

When cross-compiling ruby 2.3.1 on solaris sparc, the socket library
will not be built unless you specify a close-fds-by-recvmsg-with-peek
configure option.

(PA-544) Fix solaris sparc cross-builds of ruby socket library

---

configs/components/rubygem-nokogiri.rb

We had forgotten to create a new prebuilt nokogiri tarball during the ruby 2.3.1 bump, so this addresses that. Tested an agent built with these changes by verifying nokogiri and net-netconf were installed via 'gem list', and ran ldd on the nokogiri library file to confirm it is linking against our vendored libxml2 and libxslt libs. 
Note: this workaround is only done for huaweios. We need to vendor nokogiri as it is a dependency of net-netconf and HuaweiOS doesn't come with compiler tools by default.

(PA-546) Use prebuilt nokogiri based on ruby 2.3

---

configs/components/ruby.rb

Because (1) we're retargeting Puppet Agent's Ruby 2.3 bump to coincide with a later PE version and (2) we determined the conflict with `pe-puppet-enterprise-release` is problematic for upgrades, revert this commit.

Revert "(PA-542) Add conflicts with PE < 2016.3 components"

---

COMMITTERS.md
CONTRIBUTING.md

This PR initially adds the COMMITTERS.md and CONTRIBUTING.md files from the github.com/puppetlabs/puppet project as a baseline for ones to use for Puppet Agent, and then modifies them for use in Puppet Agent.
In COMMITTERS.md file copied from github.com/puppetlabs/puppet for Puppet Agent, references to Puppet are replaced with Puppet Agent. Additionally, notice of a 'security' branch is removed, because Puppet  Agent does not have a security branch nor is this part of the current workflow. We also remove reference to YARD docs as the Puppet Agent project does not have these.
In the CONTRIBUTING.md file, references to Puppet core vs modules are removed, as they are inapplicable. Triage meeting/notes info is removed as we don't have a meeting like that scheduled at the time of this PR. In …

(PA-538) Add committers and contributing guidelines

---

configs/components/cpp-hocon.json

This version includes string externalization, duration parsing, and some
minor API changes used in the fact caching work.

(maint) Bump cpp-hocon to 0.1.4 tag

---

configs/components/leatherman.rb

When we updated the compiler runtime to have an RPATH, we failed to
bring the right version of GCC to SPARC. This commit bumps the GCC patch
version so that we can ship it correctly.

(PUP-572) Use correct RPATH for runtime on SPARC

---

Gemfile

This is needed to fix PA-569, by enabling the brp strip scripts
on Cisco RPM platforms.

(maint) Bump vanagon to 0.8.2

---

configs/components/facter.rb
configs/components/leatherman.rb
configs/projects/puppet-agent.rb

cisco-wrlinux platforms are not compute clusters, so we can safely
disable curl builds for them.

(PA-575) Disable curl builds for cisco-wrlinux platforms

---

MAINTAINERS

This commit updates the MAINTAINERS file in puppetlabs/puppet-agent
to accurately reflect a new list of maintainers for the project.

(maint) update MAINTAINERS file

---

configs/components/ruby.rb

Rubygems recently updated its ssl cert. This patches the new cert into the Rubygems cert bundle in our vendored Ruby.
I build a Windows MSI from this branch and installed it. The cert was dropped in the correct directory, and I was able to successfully add `https://rubygems.org` as a gem source.

(PA-620) Supply ssl cert for rubygems.org

---

configs/projects/puppet-agent.rb

For the upcoming puppet-agent 1.8.0 release, we will need vendor ruby 2.1.9
blocked on https://github.com/puppetlabs/puppet-agent/pull/883

(PA-630) Update Puppet-Agent to use ruby 2.1.9

---

configs/components/facter.json
configs/components/puppet.json

Some of the acceptance tests for Puppet and Facter do not work correctly
on the eccentric platforms. This updates the SHAs for those components
to commits that include acceptance test changes which will allow
validation on the manual pipelines.

(maint) Update Facter and Puppet refs to include acceptance test changes

---

configs/platforms/osx-10.12-x86_64.rb

This is a cherry-pick from master to add the platform config for OSX 10.12.

(PA-463) Add OS X 10.12 (Sierra) platform

---

configs/components/ruby-selinux.rb

Prevent the cross-compiled builds of ruby-selinux from finding the selinux
include headers in /usr/include, and specify the sysroot includedir instead.

(PA-676) Fix cross-compilation of ruby-selinux

---

configs/projects/puppet-agent.rb

After version 2.5.0, pe-r10k begins vendoring the gettext gems, which
puppet-agent also vendors as of 1.8.0, causing these packages to
conflict. This adds a conflicts statement, which prevents them from
being installed together and ensures upgrades are handled correctly.

(PA-678) Cause puppet-agent to conflict with r10k versions less than 2.5.0

---

configs/platforms/osx-10.12-x86_64.rb

Homebrew 1.1.0 removes SHA1 sums (fine, whatever), but it also removes
the ability to run `brew` as root. Yes, this is a good idea but we
have to refactor the entire macOS build process to fix that from our
end.
But "we don't upgrade Homebrew! We use a snapshot!" you say. Well,
true. But `brew` will automatically, and silently, upgrade itself in
the background when you tap a new Homebrew keg... unless you tell it
not to.
While I was in there, I also turned off emoji and turned up verbosity.
Might as well, right?
Yes, this is specific to macOS Sierra right now. It's a snowflake.

(MAINT) Use Homebrew env. vars to prevent 💩

---

configs/components/ruby-selinux.rb
configs/platforms/osx-10.12-x86_64.rb

This brings the following fixes to stable:
- (PA-676) Fix cross-compilation of ruby-selinux on s390x
- prevent Homebrew auto-updating on macOS Sierra

Merge LTS to stable

---

configs/components/ruby-selinux.rb
configs/platforms/osx-10.12-x86_64.rb
configs/projects/puppet-agent.rb

This brings the following fixes to master:
- (PA-676) Fix cross-compilation of ruby-selinux on s390x
- prevent Homebrew auto-updating on macOS Sierra
- (PA-678) Add conflict with pe-r10k < 2.5.0

Merge stable to master

---

configs/components/curl.rb

This updates the version of curl used in our builds to 7.51.0, in
response to a recent security update.

(PA-682) Bump curl to 7.51.0

---

configs/components/rubygem-net-ssh-telnet2.rb
configs/projects/puppet-agent.rb

This is an API wrapper to allow ssh send/expect commands which
follows the Net::Telnet API.
Tested by building the huaweios agent and confirming the gem files exist in the package.

(PA-609) Add net-ssh-telnet2 rubygem for huaweios agents

---

configs/components/curl.rb

Prior to this commit debian-8-arm* platforms were getting a recv error
during configure on curl. This was due to using system pkg-config and
not the one found in /opt/pl-build-tools. This commit simply adjusts
PATH to prefer /opt/pl-build-tools/bin for cross_compiled_linux
platforms in the curl component.
This was a new problem introduced with the recent upgrade of curl.

(maint) Fix XCC of curl for arm platforms

---

configs/components/facter.json
configs/components/hiera.json
configs/components/marionette-collective.json
configs/components/puppet.json
configs/components/pxp-agent.json

This sets all the components to the tags slated for the 1.8.1 release.
All components except puppet are pinned to the versions released in
1.8.0, while puppet is updated to 4.8.1.

(PA-696) Update components to tags for 1.8.1 release

---

configs/components/rubygem-gettext-setup.rb

This bumps the gettext-setup gem version to 0.8, which allows the gem
user to specify which file format to expect for translation files.
This will need to go in before https://github.com/puppetlabs/puppet/pull/5366.

(PUP-6474) Update gettext-setup gem to 0.8

---

configs/components/pxp-agent.json
resources/windows/wix/service.pxp-agent.wxs.erb

Disables halting pxp-agent child processes when restarting or stopping
the service. This makes behavior consistent with all other platforms for
pxp-agent.
Pickup pxp-agent fix from PCP-276 required for this to work.

(PA-247) Don't halt pxp-agent child processes

---

configs/components/leatherman.json

Bump leatherman in LTS-1.7 to the 0.8.2 release which brings in the following fix:
- Handle null characters in JSON strings (LTH-116)

(PA-729) Bump leatherman in LTS-1.7 to 0.10.1

---

configs/components/rubygem-gettext-setup.rb

This update adds functionality which allows files to be excluded during
POT generation.

(INTL-8) Update gettext-setup gem to 0.10

---

configs/components/puppet.rb

A recent refactor changed the way that Puppet's install script required
the `win32/dir` gem. However, this require was broken during a Vanagon
build, because the script required the `win32/dir` gem before Vanagon
installed that gem. This makes the new dependency explicit.

(maint) Make puppet component depend on rubygem-win32-dir

---

configs/components/puppet.rb

This passes a new flag to the puppet install script, which specifies the
correct location for translation files.

(PUP-6474) Specify install location for Puppet localedir

---

configs/components/rubygem-nokogiri.rb

Because we do not build nokogiri as part of puppet-agent (only
precompiled on one platform), we missed updating the source md5sum when
we revved to 1.6.8.

(PA-786) Update md5sum for rubygem-nokogiri

---

configs/components/curl.rb
configs/projects/puppet-agent.rb

Puppet Agent 1.8.x cross compiles fail while attempting to build Curl. The root cause is that Curl is picking up the wrong compiler and trying to use the upstream Debian cross-compiler. This winds up including a local x86_64 library path, which means that curl crosslinks against the wrong zlib during configuration and fails. I'm working up a PR to address this, and as a side-effect I may have sussed out some other cross-compilation wonkiness related to the environment variables we're setting.

(PA-790) fix arm builds for Debian

---

configs/components/rubygem-hocon.rb

This updates the vendored hocon gem to 1.1.3, enabling parsing some new
config file features. This brings the version in puppet-agent up to date
with the version in puppetserver.

(PA-730) Update hocon gem to 1.1.3

---

configs/projects/puppet-agent.rb

Puppetserver versions below 2.7.2 do not vendor certain gems that puppet
depends on (e.g. gettext-setup, hocon). This commit adds a conflict
statement which will prevent this version of puppet-agent from being
installed with old puppetservers.
Please double check my logic and comment language on this one, I got the conflict backwards last time...

(PA-621) Conflict with puppetserver < 2.7.2

---

configs/components/cpp-hocon.rb
configs/components/cpp-pcp-client.rb
configs/components/facter.rb
configs/components/leatherman.rb
configs/components/libxml2.rb
configs/components/libxslt.rb
configs/components/openssl.rb
configs/components/pxp-agent.rb
configs/platforms/debian-9-amd64.rb
configs/platforms/debian-9-i386.rb
configs/projects/puppet-agent.rb
resources/files/debian-native-toolchain.cmake.txt

Debian 9.0 is currently in alpha, but these changes can be used to
generate puppet agents for both of the x86 architectures. Additionally,
building this agent no longer requires packages from pl-build-tools,
and uses the distro provided gcc, boost, and libyaml-cpp packages.

(BUILD-17) Add support for Debian 9 i386 and amd64

---

configs/components/hiera.json
configs/components/marionette-collective.json

These two components have already been released. So they can be pinned to tags
right now.

(PA-811) Update MCO and Hiera to tags for 1.7.2 release

---

configs/components/cpp-pcp-client.json
configs/components/hiera.json
configs/components/marionette-collective.json

This PR updates all puppet-agent components either to tags (non-updating components) or the SHAs we hope to tag for each component for the 1.8.3 release.
Update: no SHAs updating in this PR, will merge stable into this branch instead.

(PA-835) Gather a valid release candidate

---

configs/components/cpp-pcp-client.json
configs/components/puppet.json
configs/components/pxp-agent.json

For the components that we pinned back to previous tags (hiera, mcollective), I had to go in and edit the merge to prefer the SHAs in stable over the tags in 1.8.3-release. For Facter, I preferred the updated SHA which didn't make it into the release. Puppet and pxp-agent were tagged at their most recent stable SHA.

Merge 1.8.3-release to stable

---

configs/projects/puppet-agent.rb

(PA-890)
We have decided to delay/rethink these package conflicts to avoid unanticipated
breakage in a minor version and consequences thereof. In the interim, we will
vendor libs in question, per PA-890 and PUP-7114.

(PA-890) Revert conflicts on (pe-)puppetserver

---

ext/build_defaults.yaml

New changes to the agent internal ship process necessitate new information to
exist in build_defaults.yaml. Specifically, information on platforms that will
need a repo archive and what the locations of the respective repos are
see https://github.com/puppetlabs/packaging/pull/624 for details

(PA-894) Update build_defaults.yaml with new info on repos

---

configs/components/hiera.json
configs/components/puppet.json

These are needed to ensure we get the hiera version bump (kinda important!) and the puppet fix for PUP-6925.

Bump component SHAs for hiera and puppet

---

ext/build_defaults.yaml

We already had fedora-25 in the list of foss_platforms. This just
adds the new repo_location field to the file.

(RE-8343) Add repo_location for Fedora 25 platforms

---

configs/components/puppet.json
configs/components/pxp-agent.json

This also includes a pxp-agent SHA update that simply reflects a trivial README update.

Pull in leatherman fix for pxp-agent hang issues and fedora 25 build_defaults.

---

ext/build_defaults.yaml

The following platforms have gone EOL and will no longer be shipped with the
agent:
SLES 10
OSX 10.9
Fedora 22
Ubuntu 10.04
Ubuntu 15.10

(PA-901) Remove EOL platforms from build_defaults.yaml

---

ext/build_defaults.yaml

Ubuntu 16.10 had previously been added to foss_platforms, but since
then we've started adding repo_location metadata as well, and this
completes this info for this platform.

(RE-8346) Add repo_location for Ubuntu 16.10

---

configs/components/facter.json
configs/components/marionette-collective.json
configs/components/puppet.json

This commit updates Puppet, Facter, and MCollective to new tags for the
1.9.1 release.

(PA-920) Update components to tags for 1.9.1 release

---

configs/components/hiera.json
configs/components/pxp-agent.json

This commit pins hiera and pxp-agent back to the tags released in 1.9.0
in preparation for the release of 1.9.1

(PA-920) Pin non-updating components to tags for 1.9.1 release

---

configs/components/hiera.json
configs/components/marionette-collective.json
configs/components/pxp-agent.json

Reverts puppetlabs/puppet-agent#988
We are going to test with SHAs because there are acceptance changes.

Revert "(PA-954) Pin Hiera, MCO, pxp-agent to tags"

---

configs/components/leatherman.json

LTH-128 fixes a logging issue on AIX that prevented pxp-agent from
logging successfully. That fix is included in Leatherman 0.11.1.

(PCP-677) Bump Leatherman to 0.11.1 for logging fix on AIX

---

configs/components/pxp-agent.json

The commits on pxp-agent's stable branch beyond the 1.4.1 tag are
completely irrelevant to the puppet-agent 1.9.3 release, so this commit
pins that components back to its last released tag.

(PA-999) Pin pxp-agent to 1.4.1 tag

---

resources/windows/wix/filter.xslt.erb
resources/windows/wix/registryEntries.wxs.erb

- Provide an XSLT transform that modifies the puppetres.dll component
harvested by heat.exe.  Simply add the "Permanent" attribute to
prevent the file from being removed on upgrade.
When the event log service is open, it may hold a lock on this DLL
message file.  Typically the event log service may be hosted in the
same process as other important Windows processes (often the
network stack).  To successfully replace this file requires taking
down the event log service process, which also takes down all other
services in the same process - which can lead to disruption of
network based services.  In the wild, this has been observed to
cause Exchange Server service to bounce, which is unacceptable.
- Further mark the registry entries associated with the event log
as "Permanent", so that even …

(PA-768) Mark puppetres.dll permanent

---

configs/components/facter.json
configs/components/hiera.json
configs/components/marionette-collective.json
configs/components/puppet.json

This commit updates Facter, Puppet, Hiera, and MCollective to point to
the correct tags for the PA 1.9.3 release.

(PA-1000) Update all component SHAs to tags

---

configs/components/rubygem-minitar.rb

Update the rubygem-minitar component to version 0.6.1

(PA-970) Update minitar to 0.6.1

---

configs/components/facter.json
configs/components/hiera.json
configs/components/marionette-collective.json

This updates the SHAs in 1.10.x to what they are in the stable branch for Facter, Hiera, and MCO. Since these components do not have any branches automatically promoting into 1.10.x, it is necessary to update them manually.

Mergeup stable -> 1.10.x plus SHA fixes

---

configs/components/rubygem-gettext-setup.rb

This version of the gem introduces translation domain chaining, allowing
the tooling to behave properly when multiple nested project invoke
gettext (e.g. puppet followed by a module).

(maint) Update gettext-setup gem to 0.20

---

configs/components/rubygem-locale.rb

Previously the locale gem component referenced a gem version that does
not exist outside of our internal mirrors. This updates the gem version
to 2.1.2, which is present on rubygems.org.

(PA-762) Fix locale gem version

---

configs/components/cpp-pcp-client.json
configs/components/facter.json
configs/components/leatherman.json
configs/components/marionette-collective.json
configs/components/puppet.json
configs/components/pxp-agent.json

This updates cpp-pcp-client, facter, leatherman,
marionette-collective, puppet, and pxp-agent to their tagged versions
for the agent 1.10.1 release.

(PA-1044) Update all component SHAs to tags

---

Gemfile

This commit updates puppet-agent to use version 0.11.1 of vanagon, which
is fully compatible with the previously used version, but offers
additional tools and functionality.

(PA-1057) Update vanagon default version to 0.11.1

---

configs/projects/puppet-agent.rb

Previously, we only vendored minitar on Windows, which completely lacks a `tar` command. As it turns out, the version of `tar` on Solaris doesn't support all the options that the PMT wants to use, so we also need minitar there.

(PA-1019) Vendor minitar on solaris

---

configs/components/openssl.rb

Moved the ticket to PA. Corresponds to this earlier PR https://github.com/puppetlabs/puppet-agent/pull/1017 (which had the ticket in Security project).

(PA-1059) Adjusting openssl configuration flags to disable weak ciphers

---

Gemfile

This commit updates puppet-agent to use version 0.11.3 of vanagon, which
is fully compatible with the previously used version, but offers
additional tools and functionality.

(PA-1057) Update vanagon default version to 0.11.3

---

configs/components/runtime.rb

This removes the error: "runtime.sh: line 35: readlink: command not found"
seen when building runtime for Solaris build targets.

(PA-1084) Add path to readlink command to $PATH for Solaris runtime builds

---

ext/build_defaults.yaml

These platforms are no longer supported and we have gone EOL on those agents.

(PA-1035) Remove el-4, fedora-23, ubuntu 12.04 from build_defaults

---

configs/components/ruby-2.1.9.rb
configs/components/ruby-2.3.3.rb

I always forget why we have elevate.exe in puppet-agent. Since many new
projects use puppet-agent as a template, we should have a little more
detail as to why we include it. This way we'll know if we do or do not
want to include it in future projects.

(maint) Add explanation about elevate.exe

---

ext/build_defaults.yaml

This is used in PE promotion and that OS has gone EOL for support

(PA-1035) Remove precise from deb targets

---

acceptance/Gemfile
acceptance/setup/aio/pre-suite/010_Install.rb

Supporting work for the new PA tests in the CI Pipeline.
1. Relax Beaker version restriction to allow latest Beaker Version.
2. Fix puppet Version handling in package name (for osx, sles etc).

(PA-793) Acceptance test fixes for Suite Pipeline

---

configs/components/cpp-pcp-client.rb
configs/components/facter.rb
configs/components/leatherman.rb
configs/components/puppet.rb
configs/components/pxp-agent.rb

This PR contains 3 commits enabling i18n in the major puppet-agent components.
The first affects puppet, the second enables Leatherman's i18n, and the third updates the configuration of the other C++ project to use Leatherman's i18n tooling.

(PA-1023) Add step to generate MO files for puppet-agent components

---

configs/platforms/osx-10.12-x86_64.rb
resources/patches/osx/0001-Add-needs-cxx14.patch

Prior to this commit, macOS 10.12 packaging is failing with the
following homebrew error when installing build dependencies:
```
Error:` Invalid formula:
/usr/local/Library/Taps/homebrew/homebrew-core/Formula/mame.rb
Error: Cannot tap homebrew/core: invalid syntax in tap!
"cxx14" is not a recognized standard
```
This appears to be related to an upstream change that landed recently at
https://github.com/Homebrew/homebrew-core/pull/12146/commits/3a830725fda3b63e7f2753a8de5d68079caf7b1b.
New versions of Homebrew add `needs :cxx14`, but don't allow execution
as root, which is typically how we currently build puppet-agent.
As a workaround, this commit patches our homebrew to backport support
for `needs :cxx14` in brew forumlae.
Shamelessly copypasta-ed from @geoffnichols

(maint) Add `needs :cxx14` support to older homebrew versions

---

configs/components/facter.json
configs/components/leatherman.json

In order to support Ruby 2.4, leatherman removed references to Bignum
and Fixnum (see LTH-124) in favor of Integer, which necessitated
changes in Facter. Since this was an API break, these updates need
to be brought into PA together for validation, so this commit updates
both components simultaneously, instead of via the separate component
pipelines.

(FACT-1624) Update Leatherman and Facter to include Ruby 2.4 fixes

---

configs/components/rubygem-gettext-setup.rb

This version includes the `negotiate_locale!` method that we would like
to use in Puppet to detect the user's locale.

(maint) Update gettext-setup gem to 0.24

---

acceptance/setup/aio/pre-suite/010_Install.rb

Some platforms (e.g. osx, sles), use the SUITE_VERSION instead of SHA in
package name - update package_version to use this.
This is the Commit for Stable to match master

(PA-793) Correct PA package selection

---

configs/components/rubygem-nokogiri.rb

This commit updates the md5um for the precompiled nokogiri gem
for huaweios.

(maint) Update md5sum for precompiled nokogiri

---

configs/components/rubygem-net-ssh.rb

- Note that net-ssh 3.3.0beta1 became a dependency of Beaker 3
(see BKR-40) to address some UTF-8 issues. When that version was
found to cause issues with bundler (based on its version) number,
Beaker updated to 4.0+ in Beaker 3.11.0+.
Given the problems with Unicode handling in the 2.9.2 version of
this gem, bump the dependency before anything is reported by users.
- Note that net-ssh 3 and higher require Ruby 2.  This has no bearing
on agent packages which already ship Ruby 2.1, but could be
problematic for gem installs - therefore only update packages here.
The puppet ext/project_data.yaml has not been updated.
This new requirement will not be a problem within Puppet server as
the loading of the library is guarded behind a feature in the Puppet
code. When net-ssh fails to load there …

(PUP-7425) bump net-ssh to 4.1.0

---

configs/components/ruby-2.4.1.rb
resources/patches/ruby_241/PA-1124_add_nano_server_com_support-8feb9779182bd4285f3881029fe850dac188c1ac.patch

- This patch is from Ruby and has landed on their "trunk", but has
not been added to the 2.4 source tree.  It's possible that it may
not see the light of day until 2.5.
- In earlier technical preview versions of Microsoft Nano Server,
the COM internals were setup to allow calls to OleInitialize to
succeed, despite it being unsupported on Nano Server, for the sake
of vendors recompiling / testing their code with Nano.
OleInitialize, according to MDSN documentation always calls
CoInitializeEx(NULL, COINIT_APARTMENTTHREADED) per
https://msdn.microsoft.com/en-us/library/windows/desktop/ms690134%28v=vs.85%29.aspx
given OLE is not thread-safe.
All COINIT values are specified at:
https://msdn.microsoft.com/en-us/library/windows/desktop/ms678505
- Ruby has traditionally initialized COM by calling …

(PA-1124) Add Nano Server Ruby 2.4 patch

---

acceptance/setup/aio/pre-suite/010_Install.rb

We recently started trying to test against puppetserver nightly builds
instead of released tags. These builds must be downloaded from a
different url than released builds. This commit checks the
SERVER_VERSION param and switches to the correct url when 'latest' has
been specified.

(PA-1140) Add support for downloading puppetserver from nightlies

---

configs/projects/puppet-agent.rb

The config files for Ruby 2.4.1 were adding in a previous commit. This
commit switches to building and using Ruby 2.4.

(PA-1128) Switch to building with Ruby 2.4.1

---

configs/components/ruby-2.4.1.rb

It is unclear whether these sums are actually being used for anything given
successful builds even when they were wrong. But this commit updates
them to be correct for the files they point to, for good measure.

(maint) Update md5 sums for rbconfigs

---

acceptance/Rakefile

The check for the correct URL is now handled in the Install step of the
beaker pre-suite. We no longer need to fail on a misconfiguration here.

(maint) Remove unnecessary failure on server URL from Rakefile

---

acceptance/Rakefile
acceptance/setup/aio/pre-suite/010_Install.rb

Cherry-pick 5988b05ffeb1fa01ba318da9197640e3250df84f and a4c2a3f0ec77a1e64cf208beb69c85ba7bfc8897 from master to pick up acceptance suite changes to download puppetserver from nightlies if requested

(maint) Cherry-pick server installation changes

---

resources/files/ruby_241/rbconfig/rbconfig-arm-linux-gnueabihf.rb
resources/files/ruby_241/rbconfig/rbconfig-i386-pc-solaris2.10.rb
resources/files/ruby_241/rbconfig/rbconfig-i386-pc-solaris2.11.rb
resources/files/ruby_241/rbconfig/rbconfig-powerpc-ibm-aix5.3.0.0.rb
resources/files/ruby_241/rbconfig/rbconfig-powerpc-ibm-aix6.1.0.0.rb
resources/files/ruby_241/rbconfig/rbconfig-powerpc-ibm-aix7.1.0.0.rb
resources/files/ruby_241/rbconfig/rbconfig-powerpc-linux-gnu.rb
resources/files/ruby_241/rbconfig/rbconfig-powerpc64le-linux-gnu.rb
resources/files/ruby_241/rbconfig/rbconfig-ppc64le-redhat-linux.rb
resources/files/ruby_241/rbconfig/rbconfig-s390x-linux-gnu.rb
resources/files/ruby_241/rbconfig/rbconfig-sparc-sun-solaris2.10.rb
resources/files/ruby_241/rbconfig/rbconfig-sparc-sun-solaris2.11.rb

Ruby 2.4 expects the TEENY field in the rbconfig to be the minor version
of the Ruby installed, not 0. This updates our custom configs to set the
TEENY version to 1 accordingly.

(maint) Update rbconfigs to have correct teeny version

---

configs/components/marionette-collective.rb

MCO-783 moved the default *nix mcollective log location from /var/log to
/var/log/mcollective. That directory is not guaranteed to exist, and
mcollective will fail rather than try to create it if it's absent.
Ensure the directory exists via packaging.

(PA-1166) Create mcollective log directory

---

configs/components/libxslt.rb
configs/components/rubygem-nokogiri.rb
resources/patches/libxslt/check-for-integer-overflow.patch
resources/patches/libxslt/fix-heap-overread.patch

We need to patch libxslt with patches from upstream:
https://git.gnome.org/browse/libxslt/commit/?id=08ab2774b870de1c7b5a48693df75e8154addae5
https://git.gnome.org/browse/libxslt/commit/?id=eb1030de31165b68487f288308f9d1810fed6880
Nokogiri tarballs have been updated with the vendored libxslt changes.
tarballs for nokogiri have been updated with the addition of {version}-patch1
to the name so we don't have to overwrite the old tarballs
**Note** This PR does not contain updates to any nokogiri tarballs for other versions of ruby. Those will come in a separate PR.

(PA-1117) Update libxstl with patches

---

configs/components/ruby-stomp.rb
resources/patches/ruby-stomp/connection_loss_reconnect_fix.patch

Previously failed connections would take minutes or hours to detect,
then leave MCO in an unusable state. Patch STOMP to handle failed
connections as soon as the timeout limits are reached and reconnect
cleanly.
The specific problem is an issue with Ruby/OpenSSL interaction, where
it's not thread-safe to close a socket while reading from it (which is
precisely what the Stomp gem does). A simple reproduction of that issue
can be found at https://gist.github.com/richardc/b5a1d4d28c8bbae24cd5.

(PA-1168) Patch STOMP to detect failed connections and reconnect

---

configs/components/rubygem-nokogiri.rb

Update the md5sum of the nokogiri tarball for ruby 2.3.3, now that the source
tarball has been created and added to buildsources

(PA-1117) Update nokogiri tarball for ruby 2.3.3

---

resources/windows/wix/appdatafiles.wxs
resources/windows/wix/customactions.wxs.erb
resources/windows/wix/sequences.wxs.erb
resources/windows/wix/users.wxs.erb

Localise the "Administrators" Group and "Everyone" User id using the
Wix OSInfo service and a custom action, so that file permissions and
user group associations are correct in a localised (e.g. German/Chinese)
environment.

(PA-783) Localise Administrators and Everyone ids

---

Gemfile

This commit updates the Gemfile to use Vanagon 0.12.1, while changing
the version pin to allow new Z releases to be pulled in automatically.

(maint) Update vanagon version to automatically pull in new Z versions

---

resources/windows/wix/customactions.wxs.erb
resources/windows/wix/sequences.wxs.erb

Ensure that this Custom Action is regardless of whether UI is used, i.e.
runs in execute sequence if it hasn't already run in the UI sequence.
Otherwise the properties for localised Admin/Everyone aren't set during
unattended installs causing incorrect permission on the facts.d
directory.

(PA-1189) Add GetLocalisedAccountNames to ex Seq

---

resources/files/aix-wrapper.sh
resources/files/osx-wrapper.sh
resources/files/sysv-wrapper.sh

Without using exec, the shell process for the wrapper script
will just hang around. Using exec replaces the shell process,
saving a bit of memory and cleaning up `ps` output.

(maint) Use exec in command wrapper scripts

---

resources/files/aix-wrapper.sh
resources/files/osx-wrapper.sh
resources/files/sysv-wrapper.sh

Previously, the wrapper scripts tried to calculate where they
were based on $0. Unfortuntely, executing them via a symlink
in an arbitrary path would break this heuristic. Since
we have no plans to change our paths any time soon, this hardcoding
is better than adding even more complex logic to try to track
down the path of the agent.

(maint) Hardcode /opt/puppetlabs in command wrapper scripts

---

configs/components/rubygem-nokogiri.rb

The nokogiri tarball for ruby 2.3.1 has been updated, this commit just updates
the md5sum of the new package

(PA-1117) Update ruby 2.3.1 nokogiri tarball

---

configs/components/facter.json
configs/components/pxp-agent.json

An additional commit had landed on Facter and pxp-agent beyond what
should go out for the 5.0.0 release. This commit sets those component
SHAs to the correct branching point for the release.

(maint) Set facter and pxp-agent SHA to release branch HEADs

---

resources/aix/puppet.service

Previously, the puppet-agent invocation in our service was
calling Ruby, with the path to puppet passed as the script.
Since PA-437, this no longer works, since the path to puppet
is a shell script now, not a ruby file.
There's no good reason for us to be calling puppet indirectly
this way, so we should instead simplify the service config.

(PA-1251) Call puppet agent directly in AIX service

---

ext/build_defaults.yaml

HuaweiOS is only being supported in our LTS series of puppet-agent.

(PA-1254) Remove huaweios from foss_platforms

---

configs/platforms/solaris-10-i386.rb
configs/platforms/solaris-10-sparc.rb

Curl is an external dependency (opencsw), and is already installed
on the builders. Not trying to re-install it every time will help
us to avoid potential issues with the opencsw package repo (such
as the one in the ticket above)

(PA-1263) Do not install curl when building solaris 10 packages

---

acceptance/setup/aio/pre-suite/010_Install.rb

This commit updates the aio install pre-suite to allow installing
an ec2 master dynamically on a el based system without intervention.
Due to the expectations of the nightly puppetserver repo, the nightly
puppet-agent is installed first and then over-written with the
puppet-agent version under test. The specification of a SERVER_VERSION
is also supported.

(PA-1269) Enable EC2 master install

---

configs/components/nssm.rb
configs/components/ruby-selinux.rb

This updates the md5 to reflect what the upstream tarball has. Once this is merged I'll overwrite the file on buildsources (after making a backup of it).

(PA-611) Fix md5 for libselinux tarball and nssm zip archive

---

ext/build_defaults.yaml

Ubuntu 16.10 went EOL in July, so it's time to remove this.

(PA-1359) Remove Ubuntu 16.10 Yakkety from build_defaults

---

configs/components/cpp-pcp-client.json
configs/components/pxp-agent.json

We are not shipping these components as part of the 5.1.0 release

(packaging) Pin cpp-pcp-client and pxp-agent to 5.0.1 release

---

configs/projects/puppet-agent.rb

Enable nxcompat and dynamicbase flags in Windows builds of all puppet and
3rd party exe's, dll's built using puppet-agent.
This is being done to meet some customer's security audit requirements.
**Note**: In addition to this change, git sha references in following component's project files (json files) need to be updated appropriately so as to enable DEP linker settings: cpp-pcp-client, facter, leatherman, pxp-agent. 
Refer to following PRs: 
https://github.com/puppetlabs/facter/pull/1624
https://github.com/puppetlabs/cpp-pcp-client/pull/228
https://github.com/puppetlabs/pxp-agent/pull/620
https://github.com/puppetlabs/leatherman/pull/247

(PA-1406) Enable DEP support in Windows version of Puppet agent binaries

---

configs/components/pxp-agent.rb

pxp-agent log files and spool directory should not be readable by world.
Remove unused modules directory.
Add tasks-cache dir.

(PA-1408) Restrict permissions for pxp-agent

---

resources/windows/wix/service.pxp-agent.wxs.erb

Configure logging with nssm to capture any errors that happen during
startup (i.e. before pxp-agent has configured logging to file).

(PA-1427) Configure logging on nssm for pxp-agent

---

configs/components/nssm.rb
configs/platforms/windows-2012r2-x64.rb
configs/platforms/windows-2012r2-x86.rb
configs/projects/puppet-agent.rb

This commit does some cleanup of the nssm build and msbuild commands. It
cleans things up in the following ways:
* We add a batch file under C:\tools\vsdevcmd.bat that acts as a link to the
vsdevcmd.bat file in visual studio (but without any spaces in the path to
escape)
* We update the project to add a :msbuild setting, that shells out to cmd.exe
and executes vsdevcmd.bat && msbuild
* We use the new :msbuild project setting in the nssm build

(PA-1414) Clean up NSSM/msbuild commands

---

configs/components/nssm.json
configs/components/nssm.rb

This commit updates the nssm component to point to the 2.x branch of
puppetlabs/nssm
This commit also updates the OutDir parameter to msbuild to match msbuild
convention

(PCP-778) Update nssm to use 2.x branch

---

configs/components/nssm.rb

we need to have the OutDir parameter in the msbuild line to be .\out\ when
msbuild gets it's hands on it. However between cygwin and ruby, we need to
escape a few times to get that exact string to msbuild and cmd.exe

(PCP-778) Fix \ escaping in nssm build

---

configs/components/pxp-agent.rb

pxp-agent requires that the modules directory exists, so restore
creating it. Removing it caused test failures on all non-Windows
platforms, as pxp-agent would fail to start.

(PA-1408) Fix test failures with pxp-agent

---

configs/components/libwhereami.rb

Locales shouldn't be included on Cisco - this built cleanly for me on 5 and 7

(maint) Disable locales for libwhereami on cisco

---

ext/build_defaults.yaml

This reverts commit 86e2bbf72f64555154eb58668f074bcc826ac9de.
We want to hold off on enabling SLES 12 Power8 builds just a bit longer.

Revert "(maint) Enable SLES 12 Power8 builds in nightlies"

---

configs/components/ruby-2.4.1.rb
resources/files/ruby_241/rbconfig/rbconfig-powerpc64le-suse-linux.rb

Since this platform was merged-up from the 1.10.x branch which uses
ruby 2.1.9, this commit is also needed to get this platform to build
from the 5.1.x branch.
I have smoke tested an agent built with this commit and verified its ruby environment is working properly with rubygems, including gem installs with native extensions.

(PA-1453) Add ruby 2.4.1 rbconfig for SLES 12 Power8

---

configs/components/rubygem-gettext-setup.rb

This updates gettext-setup to a version where English is the initial
state for the locale, rather than a random locale based on the order in
which translation files were found.

(PUP-7881) Update gettext to fix Japanese error output

---

configs/components/ruby-2.4.1.rb
resources/files/ruby_241/rbconfig/rbconfig-ppc64le-redhat-linux.rb

This resolves problems with RHEL 7 Power8 agents being unable to
build native gem extensions.
I've tested this by building an agent package and smoke testing the agent, including its ruby environment and testing building a gem with native extensions (sqlite3).

(PA-1462) rbconfig fixes for RHEL 7 Power8

---

configs/components/rubygem-gettext-setup.rb

This update includes a fix for incorrect locale loading.

(PUP-7881) Bump gettext-setup to version 0.28

---

configs/components/augeas.rb
configs/components/cpp-pcp-client.rb
configs/components/facter.rb
configs/components/leatherman.rb
configs/components/libxml2.rb
configs/components/libxslt.rb
configs/components/openssl.rb
configs/components/pxp-agent.rb
configs/components/runtime.rb

Updates pl-boost version on Solaris 10 to incorporate a patch fixing a
bug in `unique_path`. Also cleans up multiple dependencies on external
packages so they funnel through Leatherman, making it easier to pick
specific versions.

(PA-1498) Update boost to incorporate Solaris fix

---

configs/components/leatherman.rb

This updates the version of pl-boost to one which includes a patch
we've applied to fix boost::filesystem::unique_path failures.

(PA-1498) Update pl-boost for aix 7.1

---

configs/components/nssm.json
configs/components/puppet.json

This commit updates nssm and puppet components to their new versions for
puppet-agent 1.10.8

(PA-1512) Tag nssm/puppet at updated versions

---

configs/components/openssl.rb
configs/platforms/fedora-f26-x86_64.rb

This commit adds support for fedora 26 to the agent. The only abnormal change
made to make things work was to specify that pl-binutils was _not_ a
requirement for openssl builds on fedora 26 in particular

(PA-1362) Add fedora 26 definition to the agent

---

resources/windows/wix/service.pxp-agent.wxs.erb

Win-10 Creators has an issue with nssm startup that is address by
setting NoAppConsole=1

(PA-1502) Set NoAppConsole=1 for Win-10 Creators

---

configs/components/pxp-agent.rb

Relax permissions on modules dir so non-root agents can read installed
modules, such as pxp-module-puppet. Specific modules could still use
more restrictive permissions to prevent access.

(PA-1527) Allow non-root agents reading modules

---

ext/build_defaults.yaml

This commit removes the following EOL platforms from build_defaults:
AIX 5.3
Fedora 24
HuaweiOS

(PA-1411,PA-1457,PA-1536) Remove EOL platforms from build_defaults

---

configs/projects/puppet-agent.rb

Previously when running facter on a machine with a Power8
architecture, dmesg would show the following line of error:
Program dmidecode tried to access /dev/mem between f0000->100000
The fix is to exclude dmidecode for Power8 architectures.

(PA-1466) Exclude dmidecode component for Power8 architectures

---

configs/components/facter.json
configs/components/hiera.json
configs/components/leatherman.json
configs/components/libwhereami.json
configs/components/marionette-collective.json
configs/components/puppet.json
configs/components/pxp-agent.json

Sets tags for
- facter 3.9.1
- hiera 3.4.2
- leatherman 1.2.1 - the 1.2.x branch beyond 1.2.1 contains only a Travis change, so we didn't tag a v1.2.2
- libwhereami 0.1.2
- mcollective 2.11.3
- puppet 5.3.0
- pxp-agent 1.8.0

(PA-1554) Add component tags for 5.3.0 release

---

configs/components/pxp-agent.rb

Ensures hocon will be built before pxp-agent when we add hocon support.

(PCP-511) Add hocon dependency for pxp-agent

---

configs/components/facter.json
configs/components/puppet.json
configs/components/pxp-agent.json

Sets tags for updated facter 3.9.2 and puppet 5.3.1.
Also pins pxp-agent back to 1.8.0. The diff between 1.8.0 and the version of 1.8.x that went through the pipelines today is [just an acceptance change](https://github.com/puppetlabs/pxp-agent/compare/1.8.0...1.8.x), and doesn't seem worth tagging a 1.8.1 for.

(PA-1555) Set component tags for 5.3.1 release

---

configs/components/facter.rb
configs/components/libwhereami.rb
configs/projects/puppet-agent.rb

libwhereami#master now has hypervisor detectors for Solaris and AIX; this commit builds libwhereami on those platforms - I was able to build the agent successfully on both.

(maint) Build libwhereami on Solaris and AIX

---

configs/components/dmidecode.rb

el-7-aarch64 uses SMBIOS 3.0, which dmidecode 2.1 can't understand; I included dmidecode 3.1 here, since its git history contains all the recommended patches for 3.0. I did a test build of this today and it ran successfully (as did e.g. `facter dmi`) on an aarch64 centos 7 host.

(PA-1624) Update dmidecode to to 3.1 for el-7-aarch64

---

configs/components/curl.rb

Curl 7.56.0 is the latest version of curl, and there are no vulnerabilities listed for it (yet) on curl's site. I built this for several platforms and architectures (including AIX, which requires a special patch) and all seemed to be in order.

(PA-1503) Update to latest curl

---

configs/components/dmidecode.rb

Vanagon has been updated to the same version in 1.10.x as in 5.3.x, so this is possible now.

(maint) Add package mirror for dmidecode

---

configs/components/rubygem-win32-process.rb

- Back on 6/27/2016, the win32-process gem was pinned to 0.7.5 in
gem based workflows (and as a gem dependency for the Puppet gem).
https://github.com/puppetlabs/puppet/commit/d4d6734e5f858b4e3f4db24c356ea7cb9db2d991
However, the corresponding update was never made to the shipping
puppet-agent MSI.
Sync them up

(PA-1569) Bump win32-process gem to 0.7.5

---

configs/components/curl.rb

7.56.1 came out just after we merged the bump to 7.56.0

(PA-1503) Update curl to v7.56.1

---

configs/components/curl.rb

This change from 03c5e03378e61b5d2a63e75391fd7b02db1d1d29 was accidentally lost during a mergeup. It is necessary for curl to build on AIX and Solaris

(PA-1631) Restore PATH when building curl

---

acceptance/lib/puppet/acceptance/common_utils.rb
acceptance/tests/validate_vendored_ruby.rb
configs/components/curl.rb
ext/build_defaults.yaml

Merge remote-tracking branch 'upstream/1.10.x' into 5.3.x
* upstream/1.10.x:
(PA-1503) Update curl to v7.56.1
Revert "(PA-1569) Bump win32-process gem to 0.7.5"
(PA-1638) Use sqlite3 version 1.3.11 for RHEL 5 platforms
bumping pxp-agent to bc09cbeb9cac1d62a8416e2e7882c038427e139f
(PA-1319) Add tests that validate the vendored ruby
(PA-1625) Enable el-7-aarch64 in nightlies
bumping puppet to b4038629e300ab73147b5a62ea9ed1f0b9c45107
bumping facter to 244f034185897482535fb07f3f1fd911e71c410e
bumping puppet to 74ff444293ac19d6150e5d694e8610b60d5c4343
(PA-1569) Bump win32-process gem to 0.7.5

Mergeup 1.10.x -> 5.3.x

---

configs/components/openssl.rb

This cleans up the openssl component config after the merge-up from 1.10.x -> 5.3.x created a control flow hairball that had to be unwound.

Openssl component config cleanup

---

configs/components/openssl.rb

This merges up the openssl component changes needed to ensure aarch64 builds work.

Mergeup 5.3.x to master

---

acceptance/Rakefile

(maint) Always-be-scheduling needs to use a different keyfile for beaker specified by an environment variable in order to facilitate ec2 testing.

(maint) Facilitate EC2 testing using always-be-scheduling

---

resources/windows/wix/properties.wxs.erb

This defaults to always replacing files regardless of their version or
checksum. This really only works for future upgrades, so the
REINSTALLMODE needs to be specified manually when downgrading to a
version of Puppet Agent without REINSTALLMODE set.

(PA-1522) Set REINSTALLMODE=amus

---

acceptance/tests/validate_vendored_ruby.rb

Previously, the test that built a native, sqlite3 gem skipped
Solaris platforms. This commit now includes Solaris 10 and 11.

(PA-1635) Include Solaris 10 and Solaris 11 in ruby tests

---

configs/components/cpp-pcp-client.json
configs/components/facter.json
configs/components/leatherman.json
configs/components/marionette-collective.json
configs/components/puppet.json
configs/components/pxp-agent.json

The components that are supposed to be pinned back were:
(1) Leatherman to 1.2.1 (LTH-147)
(2) PXP-agent to 1.8.0 (PCP-815)
(3) cpp-pcp-client to 1.5.4
The components tagged were:
(1) facter to 3.9.3 (FACT-1786)
(2) mcollective to 2.11.4 (MCO-823)
(3) puppet to 5.3.3 (PUP-8091)

(PA-1658) Set component tags for 5.3.3 release

---

bin/windows-toolset.ps1
configs/components/dmidecode.rb
configs/components/ruby-2.1.9.rb
configs/components/ruby-2.3.1.rb
configs/components/rubygem-nokogiri.rb
configs/platforms/windows-2012r2-x64.rb
configs/platforms/windows-2012r2-x86.rb
configs/projects/puppet-agent.rb

This commit adds `artifactory_url` and `buildsources_url` settings and replaces buildsources.delivery.puppetlabs.net with Artifactory.

(maint) Migrate vanagon projects to use buildsources in Artifactory

---

ext/build_defaults.yaml

This reverts commit 91430869749dcf884c58617c9e054394c4da011f.
According to @shrug - "the internal ship is seriously broken"

Revert "(packaging) Update shipping defaults to work with new puppet5 repos"

---

configs/components/openssl.rb

RC4 is necessary to be able to use NTLMv2 on Windows. Bolt currently uses HTTP
to establish a WinRM connection, which makes it rely on NTLMv2 / RC4.
Puppet doesn't currently have code which uses NTLMv2 natively elsewhere.
Changes tested in PA CI; if any additional testing needed pl let know (and any suggestions on how to do it from a fork of puppet-agent).

(PA-1712) Re-enable rc4 in openssl

---

configs/components/cpp-pcp-client.rb
configs/components/facter.rb
configs/components/pxp-agent.rb
configs/components/ruby-2.4.2.rb
configs/platforms/aix-6.1-ppc.rb
configs/platforms/aix-7.1-ppc.rb

The AIX builds need to include the zlib package to correctly install
zlib-devel.

(PA-1619) Update ruby 2.4.2 to include zlib for AIX

---

acceptance/tests/validate_vendored_ruby.rb

This was updated recently to point to a newer version of pl-gcc which
was never shipped for aix 5.3 since that platform has been EOL'ed. Point
it to the AIX 6.1 package instead.

(PA-1733) Fix url for AIX pl-gcc package

---

ext/build_defaults.yaml

This reverts commit 74cdcdc229acfb1e0f4fb2e46361fd0a968e2eed.
puppet-agent#master has successfully built and promoted using packaging#1.0.x

Revert "Revert "(packaging) Update shipping defaults to work with new puppet5 repos""

---

configs/components/ruby-2.1.9.rb
resources/patches/ruby_219/Remove-O_CLOEXEC-check-for-AIX-builds.patch

This flag (when set) causes errors with accessing /dev/null on AIX.

(maint) Update aix ruby builds to not use O_CLOXEC flag

---

resources/windows/wix/customactions.wxs.erb
resources/windows/wix/sequences.wxs.erb

This was addressed originallin in PA-286 (in Puppet for the Win), but
this particular change didn't make it into the reworked Vanagon code.
So - ensure that if no ENVIRONMENT is set for the install then it should
not be set in puppet.conf, i.e. desired behaviour is:
- On a fresh install with PUPPET_AGENT_ENVIRONMENT not specified,
puppet.conf does not have an environment key.
- On a fresh install with PUPPET_AGENT_ENVIRONMENT=foo specified,
puppet.conf does have a key of environment=foo.
- On an upgrade where puppet.conf has an environment key, the value
stays the same.
- On an upgrade where puppet.conf does not have an environment key,
the key remains out of puppet.conf.

(PA-673) PA ENVIRONMENT should default to blank

---

configs/components/rubygem-fast_gettext.rb

This release of the gem contains a backport of a file read encoding fix
that allows the gem to parse PO files with Unicode characters on more
operating systems.

(PUP-8249) Update fast_gettext to 1.1.1

---

configs/components/curl.rb

Updates curl from 7.56.1 to 7.57.0.
+ The additional `environment` else case here is backported from 5.3.x and master, which had this path setting in their curl components.

(PA-1731) Update curl to v7.57.0

---

configs/components/rubygem-fast_gettext.rb

The fast_gettext emitted a deprecation warning on ruby 2.4 due to
IO#lines. Bump to 1.1.2.

(PA-1781) Bump fast_gettext for ruby 2.4 deprecation

---

configs/components/ruby-2.4.3.rb
resources/patches/ruby_243/windows_socket_compat_error.patch

Running "puppet agent -t --server nowhere" on a non-US Windows generates
an Encoding::CompatibilityError due to a ruby bug[1] fixed in
upstream[2].
This commit cherry-picks that commit so that we generate the correct
localized error message:
証明書をリクエストできませんでした: Failed to open TCP connection to
nowhere:8140 (getaddrinfo: そのようなホストは不明です。 )
[1] https://bugs.ruby-lang.org/issues/14384
[2] https://github.com/ruby/ruby/commit/a41005eb6a99376ea940888bcf97140643d18f61

(PUP-8368) Add upstream ruby patch for Windows socket errors

---

configs/components/cpp-pcp-client.rb
configs/components/curl.rb
configs/components/facter.rb
configs/components/puppet-ca-bundle.rb
configs/components/pxp-agent.rb
configs/components/ruby-2.4.3.rb
configs/platforms/redhat-fips-7-x86_64.rb
configs/projects/puppet-agent.rb

This is being done to allow using puppet agent on FIPS enabled systems.
Vendored openssl is not allowed on FIPS systems as it is not FIPS certified.
System openssl linking is done when building on redhat_fips-7-x86_64 platform.
The rhel7 fips vmpooler image used for building will be FIPS enabled and have 
the appropriate version of openssl-devel package installed on it.
Also adding redhat-fips-7-x86_64 as a build platform.

(PA-1264) Add support to build PA against system openssl on FIPS platforms

---

configs/components/ruby-2.4.3.rb
resources/patches/ruby_243/thread_wakeup_ownership_check.patch

Ruby has patched this, but not yet released a build that contains
it. It's hitting a number of users, so we're pulling in the patch.
The associated Ruby ticket is https://bugs.ruby-lang.org/issues/13794

(PA-1743) Vendor patch for Ruby sched_yield lockup

---

configs/components/cpp-pcp-client.json
configs/components/facter.json
configs/components/hiera.json
configs/components/marionette-collective.json
configs/components/nssm.json
configs/components/pxp-agent.json

These generally match the versions used in the 5.3.4 release branch, with the exception of puppet, leatherman, and libwhereami, all of which use new source branches for the 5.4.x branch of puppet-agent.

(maint) Set component versions for 5.4.0

---

configs/components/hiera.json

7e0cbf18e6179f499517e6841847d401f69df067 is [just an empty commit](https://github.com/puppetlabs/hiera/commit/7e0cbf18e6179f499517e6841847d401f69df067) erroneously generated by our CI - pinning to 3.4.2, since there are no other hiera changes.

(packaging) Pin hiera to 3.4.2 for agent 5.4.0 release

---

configs/components/pxp-agent.json

Sets the pxp-agent ref to 1.8.2, which was tagged in the 5.3.5-release branch today. Other components will be tagged for 5.4.0 later.

Use pxp-agent 1.8.2 tag for PA 5.4.0

---

configs/components/puppet.json

I just cut a puppet [5.4.0-release branch](https://github.com/puppetlabs/puppet/commits/5.4.0-release) to get the cherry-pick of the PUP-2868 revert from 5.4.x into 5.4.0 without including 5.4.x's version bump to 5.4.1. This commit points puppet at that branch's HEAD.

(maint) Bump puppet to revert PUP-2868 in advance of 5.4.0 release

---

configs/components/puppet.rb

Prior to this commit, we saved the output of
`puppet resource service puppet` and then applied it again after
upgrade with `puppet apply`.  This causes custom facts to be
loaded by `puppet apply` which is undesirable when your custom
fact wants to query the package manager.
After this commit, we blank out some puppet settings so that the
agent won't be able to find any custom facts that have been
pluginsynced or if its the agent on a master then custom facts
in the modulepath.

(PA-1402) Avoid loading custom facts during upgrade

---

configs/components/puppet.rb

This Debian package trigger will be produced during package upgrades and
in conjunction with the puppetserver package, can be used to  trigger a
restart of the puppetserver service.

(PA-1130) Add Debian producer trigger puppetserver-restart

---

configs/components/puppet.rb

RPM 4.14.0 contains the following commit: rpm-software-management/rpm@79ca74e. The commit introduces a new feature to RPM when upgrading packages. It is best described as follows. Assume that Package B is an upgraded version of Package A; both share a File C. Before RPM 4.14.0, RPM would create Package B's File C with a unique suffix, and then rename it to Package A's File C for all files (hence the upgrade). However with RPM 4.14.0 and that commit, RPM will instead, for some files, proceed to only update Package A's File C's metadata without doing anything else (from the commit diff and based on http://rpm.org/wiki/Releases/4.14.0) - these files are designated with an FA_TOUCH action. So essentially, RPM 4.14.0 gives you the opportunity to preserve the content of old config. files …

(PA-1890) Copy the old hiera.yaml files instead of renaming them.

---

configs/components/marionette-collective.rb
configs/components/puppet.rb

The first pass at this ticket only fixed the puppet service
management. The same approach is used for mcollective, which also
needs to be fixed up.

(PA-1402) Ensure puppet apply is not called for mcollective service

---

configs/components/virt-what.rb

Updates virt-what from version 1.14 to 1.18, and adds a mirror URL for the source.

(PA-1893) Update virt-what from version 1.14 to version 1.18

---

configs/components/puppet-runtime.json
configs/components/puppet-runtime.rb

Adds puppet-runtime as a vanagon component. This component is currently
unused but (when complete) will replace many of the vendored
dependencies in the agent project.

(PA-1765) Add puppet-runtime component

---

acceptance/tests/validate_vendored_ruby.rb
configs/components/ruby-2.4.3.rb
resources/patches/ruby_243/rubygems_add_puppet_vendor_dir.patch

Puppet has a number of gem dependencies that are shared between using it in a server or client context. These dependencies are currently duplicated in both the agent and server packages, since both need to be able to load Puppet's ruby code.
The problem with this is that adding new dependencies to Puppet requires a dance with server releases, in order to ensure new versions of the puppet code can still run with older servers that do not include the gems, and in order to ensure that the latest server always ships the gems needed to enable all of Puppet's features.
Instead, we are introducing a new vendored gem directory which will contain gems intended to be used on both the agent and server. This will allow us to ship the required gems along with the shared Puppet code, ensuring the …

(PA-1894) Add custom vendor dir for shared rubygems

---

Rakefile

Recently we updated the automation to say 'promoting' in component bump
tickets. We need the commit checker to pass for those commits

(maint) update commit check to include 'promoting'

---

configs/components/rubygem-multi_json.rb
configs/projects/puppet-agent.rb

This commit adds a component for the multi_json gem, which gets
installed in the shared gem directory so it is available to
puppetserver.

(PA-1904) Add multi_json to shared gem directory

---

configs/components/augeas.rb

Prior to this the augeas url and mirror url were identical, which means
that anybody attempting to build Puppet Agent not on our VPN couldn't
download augeas.

(maint) Augeas URL should be external

---

Gemfile
configs/components/cfacter-precompiled-gem.rb
configs/components/cfacter-source-gem.rb
configs/components/cpp-hocon-source.rb
configs/components/facter-source.rb
configs/components/leatherman-source.rb
configs/projects/cfacter.rb
ext/build_defaults.yaml
resources/files/cfacter-gem/Makefile.erb
resources/files/cfacter-gem/cfacter-precompiled.gemspec.erb
resources/files/cfacter-gem/cfacter-source.gemspec.erb
resources/files/cfacter-gem/extconf.rb
resources/files/cfacter-gem/make.bat

This will be a new vanagon project included with the agent. It makes use of 5
components:
* cpp-hocon-source < just the entire cpp-hocon source copied in to place
* leatherman-source < just the entire leatherman project copied in to place
* facter-source < just the entire facter project copied in to place
* cfacter-source-gem < a component with build rules to construct the source gem
from sources and resource files.
* cfacter-precompiled-gem < a component with build rules to actually precompile a gem and package it up
This commit is entirely additive, and should not effect the agent in any way.
The cfacter source gem is a gem that can be installed on a system with new
enough gcc/boost/cmake to give the user access to facter.
the cfacter precompiled gem should be installable right away on …

(PA-1245) Add defs for cfacter-source-gem project

---

configs/components/cfacter-precompiled-gem.rb
configs/projects/cfacter-source.rb

We should be able to independently build the cfacter source and precompiled
so this commit adds the cfacter source project, and then updates the cfacter
project (which builds precompiled gems) to not ship the source gem as
well

(PA-1245) Split cfacter source/precompiled in to seperate projects

---

configs/components/cfacter-precompiled-gem.rb
configs/projects/cfacter.rb
resources/files/cfacter-gem/cfacter-precompiled.gemspec.erb
resources/files/cfacter-gem/extconf.rb

This commit makes a few necessary changes to facilitate the cfacter gem on
windows:
Paths have been updated and settings added to allow the puppet-runtime to
work.
The glob of files for the file list in the precompiled gem has been moved to
an erb template so the windows gem can include both lib/ and bin/ dirs
the windows gem now copies both the lib and bin dirs (since on windows
facter.rb expects to reside in lib/ and call out to bin/)

(FACT-1547) Build working cfacter gem for windows

---

configs/projects/cfacter.rb

This commit updates the precompiled cfacter gem definitions to allow for
building windows 32 bit

(FACT-1547) Add 32 bit windows definitions for cfacter

---

ext/build_defaults.yaml

The 5.5.x series should continue to ship to the puppet5 nightly repo even
though there will be a puppet6 repo, however, the puppet-nightly link should
no longer be changed to link to puppet5-nightly (since that's no longer the
latest changes, puppet6-nightly is)

(maint) disable the 5.5.x branch from changing puppet-nightly link

---

ext/build_defaults.yaml

Simply setting the string to empty will not work, so actually completely
remove it

(maint) Actually remove nonfinal_link_target from build_defaults

---

ext/build_defaults.yaml

This PR is both a mergeup and an additional commit to enable puppet6 nightly repo shipping.

Merge 5.5.x -> master, enable puppet6 nightly repos

---

configs/components/marionette-collective.rb

MCollective configures the Ruby Logger to perform rotation in-process. This
behavior is enabled by default if the file_logger is used with 5 archived logs
retained and rotation occurring after 2 MB of logs. This behavior renders the
logrotate configuration for MCollective redundant. Aside from adding
complexity, certain versions of the logrotate configuration executed a full
restart of the daemon which could wake up daemons that had been disabled and
also created thundering herd issues as logrotate tends to execute around the
same time each day.

(PA-1908) Remove logrotate from MCollective

---

configs/components/marionette-collective.rb

The mcollective state file is not a scrip that returns data, it's a
file that needs to be dumped. Treat it as such.

(maint) Do not try to execute mcollective state file

---

ext/build_defaults.yaml

Note: I'm using 'redhatfips' as the name, as the PE installer expects the tarball to be named 'puppet-agent-redhatfips-7-x86_64.tar.gz' (see the ticket for additional details/context).
Travis is going to complain because I'm using a PE ticket number.

(PE-22679) Add missing repo_location for redhatfips-7-x86_64

---

configs/components/puppet-runtime.rb

I neglected to fix this line in the [mergeup between 1.10.x and 5.3.x this week](https://github.com/puppetlabs/puppet-agent/commit/c3d2cc02de756c073961a52674b0a21f7469ab54) :man_facepalming:

(PA-1949) Fix incorrect runtime tarball name

---

configs/components/leatherman.rb

The pl-boost package versions line up well here so we can eliminate the
conditional between AIX versions.

(PA-1948) Update AIX 6 builds to use updated pl-boost package

---

configs/components/leatherman.rb
configs/components/libwhereami.json
configs/components/puppet-runtime.rb
configs/components/puppet.json
configs/projects/puppet-agent.rb

This mergeup applies the use of puppet-runtime to the master branch - the equivalent project files in puppet-runtime that replace the removed files are [here](https://github.com/puppetlabs/puppet-runtime/blob/master/configs/projects/agent-runtime-master.rb) and [here](https://github.com/puppetlabs/puppet-runtime/blob/master/configs/projects/base-agent-runtime.rb).

Merge up 5.5.x to master

---

configs/platforms/redhatfips-7-x86_64.rb
ext/build_defaults.yaml

Dashes in platform names cause trouble down the line when it comes time
to add the platform to pe_repo, so make this platform name 'redhatfips'.

(PA-1958) Rename redhat-fips platform to redhatfips

---

configs/components/facter.rb
configs/components/leatherman.rb

puppet-runtime now allows shipping multiple rubies at once - the original
rbconfig in `datadir` for cross-compiled platforms and sparc now has a
suffix applied to designate the ruby version. This updates the rbconfig
path accordingly for facter and leatherman.

(maint) Update leatherman/facter rbconfig paths

---

resources/files/puppet-agent.sh

When the user installs puppet-agent, by default, the man pages are not
included in the manpath. This updates the path through the
puppet-agent.sh script in profile.d.

(PA-1847) Add puppet docs to MANPATH

---

configs/projects/puppet-agent.rb

The puppet-agent project inherits its settings from puppet-runtime.
The code checks out from the ref in the puppet-runtime.json file,
but the source is hard-coded to puppetlabs/puppet-runtime. This commit
changes the source to be the url in the puppet-runtime.json file.

(maint) Use the url in the puppet-runtime.json file

---

configs/components/leatherman.json

6773 contains the bump to 1.2.3, which we need in order for the tagging
job to correctly tag leatherman at 1.2.3

(maint) Update leatherman to 6773c8890c4e60b168f52daec0445166a3684902

---

configs/components/pxp-agent.rb

It's highly unlikely that Leatherman or cpp-pcp-client DLLs will be
installed to a Windows system directory. Also, work is underway to move
to statically linking cpp-pcp-client, and this makes doing so
transparently difficult. Only copy common DLLs from OpenSSL and MinGW.

(maint) Avoid unnecessary duplication

---

acceptance/tests/validate_vendored_ruby.rb
configs/components/rubygem-puppet-resource_api.json
configs/components/rubygem-puppet-resource_api.rb
configs/projects/puppet-agent.rb

```
david@davids:~/git/puppet-agent$ sudo dpkg -i output/deb/stretch/PC1/puppet-agent_5.5.0.89.g0c885104-1stretch_amd64.deb
[sudo] password for david:
dpkg: warning: downgrading puppet-agent from 5.5.0.89.g9adc14d0-1stretch to 5.5.0.89.g0c885104-1stretch
(Reading database ... 295203 files and directories currently installed.)
Preparing to unpack .../puppet-agent_5.5.0.89.g0c885104-1stretch_amd64.deb ...
Unpacking puppet-agent (5.5.0.89.g0c885104-1stretch) over (5.5.0.89.g9adc14d0-1stretch) ...
Setting up puppet-agent (5.5.0.89.g0c885104-1stretch) ...
Processing triggers for libc-bin (2.27-2) ...
david@davids:~/git/puppet-agent$ /opt/puppetlabs/puppet/bin/gem list --local | grep resource
puppet-resource_api (1.0.1)
david@davids:~/git/puppet-agent$ cd …
```

(PDK-526) Add puppet-resource_api gem

---

configs/components/rubygem-puppet-resource_api.rb

Previously `gem build` relied on the system Ruby, which is not present
on all platforms - particularly Solaris and Windows. Use puppet-runtime
ruby instead.

(maint) Use built ruby for gem build

---

configs/components/facter-precompiled-gem.rb
configs/components/facter-source-gem.rb
configs/projects/facter-gem.rb
configs/projects/facter-source-gem.rb
resources/files/facter-gem/facter-precompiled.gemspec.erb
resources/files/facter-gem/facter-source.gemspec.erb
resources/files/facter-gem/generate-gemspec.rb

Previously, the facter gem version was being computed in Vanagon. This
required fetching the facter version file from github, which was
leading to us hitting API rate limits.
This commit changes the build to calculate the version on the build
machine, using a small Ruby script. It avoids the need to hit github
and still creates artifacts with the proper version.

(PA-1982) Calculate facter gem version on build host

---

configs/components/facter-precompiled-gem.rb
configs/components/facter-source-gem.rb

The ruby interpreter on Windows does not know how to load our
cygwin-generated temp directory. We need to convert it to a proper
Windows path to allow generating the gemspecs correctly.

(maint) Use cygpath for facter gem build location on windows

---

acceptance/tests/validate_vendored_ruby.rb
configs/components/puppet-runtime.rb
configs/platforms/solaris-10-i386.rb
configs/platforms/solaris-10-sparc.rb

While opencsw.org's mirror service is unavailable, use specific mirror
for Solaris 10 dependency packages.

(maint) Use alternate mirror for Solaris 10 builds

---

configs/platforms/windows-2012r2-x64.rb
configs/platforms/windows-2012r2-x86.rb

We are migrating everything over from nexus to artifactory. This commit changes the url for the nuget build repository and uses the artifactory/nuget api

(PA-1990) migrate nuget from nexus to artifactory

---

acceptance/tests/validate_vendored_ruby.rb
configs/platforms/solaris-10-i386.rb
configs/platforms/solaris-10-sparc.rb

It looks like the GA Tech secondary mirrors have gone offline.
Switching back to the primaries.

(maint) switch solaris to primary opencsw mirrors

---

configs/components/_base-module.rb
configs/components/module-puppetlabs-mailalias_core.json
configs/components/module-puppetlabs-mailalias_core.rb
configs/components/module-puppetlabs-maillist_core.json
configs/components/module-puppetlabs-maillist_core.rb

This commit alters how we're handling modules during the install
process. Prior, we had been installing them from the forge. This commit
changes the install so that we're installing from a github repo. This
allows us to include development versions of modules in the puppet-agent
package, as we do for all other component projects included here.
This commit also modifies mailalias and maillist to read data from
corresponding json files.

(maint) Modules should be installed from gh repo

---

configs/platforms/solaris-10-i386.rb
configs/platforms/solaris-10-sparc.rb

Solaris10 uses the Vanagon provision_with capability to run a moderately
complex shell fragment to provision things. The issue is that if given a
series of shell commands to execute, only the exit status of the last command
run is noticed when determining success.
We have had issues with the mirror server for Solaris10 dropping off the
net, causing build fails. This change provides the ability to fail when
pkgutil fails to find the mirror, which means the build will fail much faster.

(maint) notice when pkgutil can't find a source mirror

---

acceptance/tests/validate_vendored_ruby.rb
configs/platforms/solaris-10-i386.rb
configs/platforms/solaris-10-sparc.rb

We need to revert this while our Sol10Sparc machines are updated to address IMAGES-844.

Revert "(maint) use artifactory for solaris10 mirror"

---

configs/components/_base-module.rb

Removes any hidden files from directories in the `module_vendordir`, including .git/, travis config, etc.
I compared the results of removing hidden files with the the contents of module directories produced by PMT installs, and they seem to be equivalent (from an admittedly small sample). That said, some modules do include nonessential non-hidden things like an `appveyor.yml` even in the PMT-installed versions, so I left those alone for now.

(PA-2062) Remove hidden files from vendored modules

---

configs/platforms/fedora-26-x86_64.rb
configs/platforms/fedora-27-x86_64.rb
ext/build_defaults.yaml

This commit updates the fedora platform configs to not use the 'f' prefix in
versions and, instead, use 'fc<version>' as the dist tag, which is standard for
fedora packages.

(CPR-391) Fedora packages have odd distro tag

---

configs/components/puppet.json

this commit re-pins puppet to 4.10.12 since there were no actual code changes
between the last tag and the current SHA

(maint) Pin puppet to 4.10.12

---

configs/components/puppet.json

this commit pins the puppet component back to 5.3.7 since there are no actual
code changes between 5.3.7 and the current SHA

(maint) Pin puppet to 5.3.7

---

resources/windows/wix/customactions.wxs.erb
resources/windows/wix/sequences.wxs.erb

7cdb9e8 introduced a change to reference directories in CustomAction
tables by their component name, rather than by their directory name.
However, during a repair `[$componentkey]` resolves to an empty string,
resulting in takeown & icacls running from the root drive, damaging
file permissions system-wide.
MSDN documentation https://msdn.microsoft.com/library/aa368609.aspx
suggests that this is because:
Note that if a component is already installed, and is not
reinstalled, removed, or moved during the current installation, the
action state of the component is null and the string
[$componentkey] evaluates to Null.
This commit modifies the custom action logic so that it:
* Uses `[%ProgramData]` which resolves to the value of the ProgramData
environment variable, and should always be …

(PA-2075) Use ProgramData to resolve puppet's data directory

---

configs/components/puppet.json

This commit pins the puppet component to 5.5.2 in preperation of the agent
5.5.3 release

(maint) Pin puppet to 5.5.2

---

Gemfile
README.md
configs/components/puppet-runtime.json
configs/components/puppet-runtime.rb
configs/projects/puppet-agent.rb

Replaces the git ref and url values in puppet-runtime.json with version
and location values instead. This obviates the need to push, tag, and
ship runtime revisions before using them to build an agent; The README
has been updated with instructions on using a local puppet-runtime
output directory as a tarball source instead of Puppet's internal build
sources.

(PA-1995) Use location & version in puppet-runtime.json

---

configs/components/puppet-runtime.rb
configs/projects/facter-gem.rb
configs/projects/facter-source-gem.rb

The puppet-runtime component was changed to expect details about the
puppet-runtime version and location to be recorded as settings in the
project file, but the facter gem projects weren't updated to do the same
-- this corrects the settings and adds a specific error message in the
runtime component for cases where they haven't been set.

(maint) Correct runtime path settings for facter gems

---

configs/components/cpp-hocon.json

Incorporates fixes to substitution from 0.1.7.

(packaging) Bump cpp-hocon to 0.1.7

---

ext/build_defaults.yaml

Other packaging tooling can't determine these automatically yet

(packaging) Explicitly set apt & yum repo names

---

configs/components/facter.json

Merge order in CI went a little south, and this promotion failed -- the SHA is just the current head of facter#master, which merged up successfully today.

(maint) Update facter to 290783ce6688178bf44177c5d7b2fe272230649c

---

configs/platforms/osx-10.12-x86_64.rb
configs/platforms/osx-10.13-x86_64.rb

Other tooling is not ready for a rename of 'apple' to 'mac'

(maint) Revert dmg package path updates

---

ext/build_defaults.yaml

Adds Fedora 28 to build_defaults.yaml -- Also corrects Fedora platform names still using an `f` prefix there (pretty sure this just wasn't caught during the `f` removal efforts previously).

(PA-1865) Add Fedora 28 to build_defaults

---

ext/build_defaults.yaml

AIX 7.1 and 7.2 hosts will use AIX 6.1 packages in puppet 6

(PA-2108) Remove AIX 7.1 repos from build_defaults

---

configs/components/facter.rb

This commits updates facter's java requirement so puppet-agent will
provide the facter jar needed to support running puppetserver on
Ubuntu 18.04.

(maint) Build facter jar on Ubuntu 18.04

---

Gemfile

This commit bumps the packaging gem dependency to be more specific. Without
this, older versions of packaging get pulled in, which don't include necessary
updates for shipping.

(maint) Bump to packaging 0.99.8

---

configs/platforms/windows-2012r2-x64.rb
configs/platforms/windows-2012r2-x86.rb
resources/windows/wix/customactions.wxs.erb
resources/windows/wix/sequences.wxs.erb

- Merge the 7 individual custom actions responsible for setting
permissions, merging them into a single custom action, now called
`ResetDataPermissions`, including:
* takeown against %ProgramData%\PuppetLabs\puppet
* icacls against %ProgramData%\PuppetLabs\puppet to set ownership to Administrators / SYSTEM
* icacls reset against %ProgramData%\PuppetLabs\puppet
* icacls reset against %ProgramData%\PuppetLabs\code
* icacls reset against %ProgramData%\PuppetLabs\facter
* icacls reset against %ProgramData%\PuppetLabs\pxp-agent
* icacls reset against %ProgramData%\PuppetLabs\mcollective
- The existing WixQuietExec64 / WixQuietExec Custom Actions are replaced
with a vbscript custom action.
Note a few important changes:
* Shell.Application is used to resolve the systems constants for …

(PA-2112) Rewrite permissions custom actions in VBScript

---

README.md
configs/components/cpp-hocon.json
configs/components/cpp-hocon.rb
configs/components/cpp-pcp-client.rb
configs/components/facter-precompiled-gem.rb
configs/components/facter.rb
configs/components/leatherman.rb
configs/components/libwhereami.rb
configs/components/pxp-agent.rb
configs/components/runtime.rb

**Do not merge; This is a WIP PR**
Will require https://github.com/puppetlabs/puppet-runtime/pull/77

(PA-2055) Get boost and yaml-cpp from puppet-runtime

---

configs/components/cleanup.rb
configs/components/pxp-agent.rb
configs/projects/puppet-agent.rb

Most headers are removed after building the last C++ component,
pxp-agent, to reduce the size of the final puppet-agent package. Some
donwstream vanagon projects that consume puppet-agent depend on OpenSSL
headers, so keep those.
(The eventual goal here is to produce separate puppet-agent (without headers) and puppet-agent-dev (with headers) packages, but until that time, we've removed as many headers as possible)

(PA-2055) Don't remove OpenSSL headers after building

---

configs/components/cleanup.rb

pe-r10k-vanagon depends on puppet-agent and needs its curl headers for
libgit2.

(maint) Don't remove curl headers after build

---

configs/components/facter.rb
configs/components/pxp-agent.rb

We need to copy openssl dlls around on windows. This commit updates the
names of those dlls since they changed in OpenSSL 1.1
Should be merged at the same time as https://github.com/puppetlabs/puppet-runtime/pull/82

(PA-1941) Fix libnames for new OpenSSL dlls

---

Rakefile
ext/release-lead.rake
ext/smoke/README.md
ext/smoke/helpers.sh
ext/smoke/packages/run-smoke-test.sh
ext/smoke/packages/steps/setup-master.sh
ext/smoke/repos/run-smoke-test.sh
ext/smoke/repos/steps/setup-masters.sh
ext/smoke/steps/run-validation-tests.sh
ext/smoke/steps/setup-agent.sh

This adds improvements to automate engineering release lead duties:
- A rake task for finding platform additions and removals.
- A rake task for checking component versions included at a SHA for puppet-agent.
- A script for smoke testing puppet-agent from pre-release packages.
- A script for smoke testing puppet-agent from released repos.

Add Release Lead helpers

---

resources/windows/wix/customactions.wxs.erb
resources/windows/wix/service.puppet.wxs.erb

After upgrading to ruby 2.5.1 in master, agent MSIs failed to install without `PUPPET_AGENT_STARTUP_MODE=Manual` (we use this in CI, so it wasn't noted until the agents were consumed elsewhere). This is because the WiX template wasn't updated to remove the deprecated `-rubygems` flag when ruby 2.5.1 was introduced. I've also removed an innocuous but unwanted reference to mcollective (which I suspect arrived via automated mergeup from 5.5.x at some point?)
I built this locally and tested the installation on a windows VM; all seems well without manual startup mode now.

(PA-2155) Remove deprecated rubygems flag in WiX templates

---

configs/components/cpp-hocon.rb
configs/components/cpp-pcp-client.rb
configs/components/facter-precompiled-gem.rb
configs/components/facter.rb
configs/components/leatherman.rb
configs/components/libwhereami.rb
configs/components/puppet-runtime.rb
configs/components/puppet.rb
configs/components/pxp-agent.rb
configs/components/runtime.rb
configs/platforms/sles-15-x86_64.rb
configs/projects/puppet-agent.rb

This platform is being built with the default OS toolchain, and doesn't
rely on pl-build-tools packages.

(PA-2157) Add support for sles-15-x86_64

---

configs/platforms/sles-15-x86_64.rb

Was missing the gcc-c++ package in the provisioning pkg list.

(PA-2157) Build dependency fix for sles-15-x86_64

---

configs/components/puppet-runtime.rb

This is required by pxp-agent.

(maint) Add libboost_random dependency for sles-15 agent package

---

configs/components/facter.rb
configs/components/hiera.rb
configs/components/leatherman.rb
configs/components/nssm.rb
configs/components/puppet-runtime.rb
configs/components/puppet.rb
configs/components/pxp-agent.rb
configs/components/runtime.rb
configs/projects/puppet-agent.rb
resources/files/windows/environment.bat
resources/windows/wix/service.puppet.wxs.erb
resources/windows/wix/service.pxp-agent.wxs.erb

This PR updates install paths for Windows agents in puppet6 so that they more closely match the equivalent paths on Unix/Linux-based platforms.
This PR depends on several others:
A puppet-specifications PR is open here detailing the new paths: 
- https://github.com/puppetlabs/puppet-specifications/pull/123
This beaker-puppet PR adds the new paths to the `PATH`:
- ~~https://github.com/puppetlabs/beaker-puppet/pull/64~~ Merged and released
This puppet-runtime PR must be merged and must promote to puppet-agent#master before this PR can be merged:
- ~~https://github.com/puppetlabs/puppet-runtime/pull/94~~ Merged and promoted
PRs below must be merged at the same time as this PR:
- https://github.com/puppetlabs/puppet/pull/7068
- https://github.com/puppetlabs/pxp-agent/pull/723

(PA-1923) Update Windows install paths to more closely match equivalent *nix paths

---

resources/windows/wix/shortcuts.wxs.erb

This commit updates the script used for "Start Command Prompt with Puppet" to
start in the appdata directory rather than C:\Windows\system32 (which is
where the script would start by default with no changes)

(PA-619) open puppet command prompt in puppet appdata dir

---

configs/components/cpp-hocon.json
configs/components/hiera.json
configs/components/libwhereami.json
configs/components/rubygem-puppet-resource_api.json

This cleans up a few things that were still pointed to master branches
instead of the older branches that we'd decided to stick with for
6.0.0.

(maint) SHA/tag pinning for 6.0.0

---

configs/components/puppet.json

We had one change land late that we're not comfortable with the risk
of shipping untested. We're pinning back to just before that change.

(packaging) Pin puppet for 6.0.0 release

---

ext/smoke/repos/steps/setup-masters.sh
ext/smoke/steps/setup-agent.sh

This has been tested to work correctly with both puppet5 and puppet6
collections. It also includes a change in the command line to sign
all certs that was made in puppet6.

(maint) Fix hardcoded smoke test references to puppet5 collection

---

configs/components/runtime.rb
configs/components/virt-what.rb
configs/platforms/el-7-ppc64.rb
configs/projects/puppet-agent.rb
resources/files/ruby_243/rbconfig/rbconfig-ppc64-redhat-linux.rb

This patch adds support for RHEL 7 on big-endian powerpc systems. In particular, it has been built for a POWER8 environment running RHEL 7.5. Changes are focused on including ppc64 in all areas of the config which currently target ppc64le.
This is an alternative to #1524. @ScottGarman I reworked my original 5.5.x changes into a clean commit instead of rebasing my other branch that targeted 6.x.
Thanks,
Phil

(PA-2158) Add el-7-ppc64 build support for 5.5.x

---

configs/platforms/debian-8-armel.rb
configs/platforms/debian-8-armhf.rb
configs/platforms/el-7-s390.rb

Add a note to the platform config for community-supported OS platforms.
And yes, the "s390" platform was never officially supported, just the "s390x" ones.

(maint) Mark platforms which are community-supported

---

configs/components/module-puppetlabs-augeas_core.json

PUP-9112 changed :undef/nil handling in puppet6, which broke the augeas
provider. This was fixed in MODULES-7814, so bump the module to 1.0.2.

(maint) Bump augeas_core module to 1.0.2

---

.travis.yml

(maint) Increase the clone depth to 150 for Travis CI
The default clone depth of 50 can cause Travis CI to fail if more
than 50 commits of work have landed since the last tag. Many of the
commits in the puppet-agent repo correspond to automated component
promotions, so this threshold is a bit low. This commit increases
the clone depth to 150.

(maint) Increase the clone depth to 150 for Travis CI

---

resources/windows/wix/service.pxp-agent.wxs.erb

Previously, NSSM would restart the pxp-agent service if it fails
for any other reason besides an invalid service configuration.
If the failure happens when the service is starting up, then
there's a chance that the restart is stuck in an infinite loop.
We've seen this happen in Puppet 6.
This commit configures NSSM to restart the service on an exit code
of 1, and stop for all other exit codes. An exit code of 1 likely
corresponds to a crash or an unexpected failure, so restarting the
service here makes sense. The other exit codes correspond to failures
in the setup, so stopping the service for those exit codes also makes
sense. Note that pxp-agent returned an exit code of 3 during the
infinite loop scenario, so the changes here should fix that.

(PA-2241) Rewrite the pxp-agent service's AppExit configuration

---

acceptance/tests/ensure_puppet-agent_paths.rb
acceptance/tests/env_windows_installdir_fact.rb

This test is specific to setup that happens as a part of the
puppet-agent package. We should have this test live as a part of the
puppet-agent acceptance tests

(maint) Move puppet-agent tests out of puppet

---

acceptance/tests/validate_vendored_modules.rb
configs/components/module-puppetlabs-scheduled_task.json

This commit updates the reference to the `scheduled_task` module to 1.0.0 in
anticipation of the first supported release of that module.

(MODULES-7753) Update scheduled_task ref for 1.0.0

---

acceptance/tests/ensure_puppet-agent_paths.rb

The test was migrated from puppet to puppet-agent in 5.5.x, but we
removed mco in 6, so remove the expectation for those binaries.

(maint) Remove mco reference

---

Rakefile
ext/release-lead.rake

This adds two rake tasks that help with release lead duties.
- Platform differences:
`release_lead:platform_diff`: Given two puppet-agent SHAs or tags,
this task reports which platforms have been added and retired between
the first and the second. Example execution:
```
bundle exec rake release_lead:platform_diff[tag,SHA]
```
- Checking components:
`release_lead:check_components`: Outputs all component statuses at a
given SHA or tag by checking out that git reference, cloning all
linked components, and running `git describe` on each, reporting the
tag and any commits since the last tag. Example execution:
```
bundle exec rake release_lead:check_components[SHA]
```

(maint) Add helper functions for release lead work to 5.5.x

---

acceptance/tests/ensure_SCL_python_pip_works.rb
resources/files/sysv-wrapper.sh

When users want to make use of python (and other tools) from the redhat
software collections, those packages _do_ require that the LD_LIBRARY_PATH be
set to include directories containing those packages.
Since we unset LD_LIBRARY_PATH we have broken any customer using RHSCL
packages. This commit updates the wrapper script for puppet and friends to
search through each existing path in LD_LIBRARY_PATH for any path that starts
with /opt/rh/ (the canonical place for these packages to be installed) and
keep those paths in LD_LIBRARY_PATH as puppet and friends' run

(PUP-8351) Update bash wrappers to keep LD_LIBRARY_PATH with RHSCL

---

acceptance/tests/windows_eventlog.rb

This test depends on puppetres.dll to be properly registered on the test
machine. Since this dll registry happens as a part of installing the
puppet-agent package, we should be testing this functionality here,
rather than as a part of the puppet acceptance test suite.

(maint) Move windows eventlog test out of puppet

---

resources/files/sysv-wrapper.sh

On Solaris 10, /bin/sh uses the legacy Bourne shell syntax. This means
that some of the more advanced syntax like '$()' or 'export VAR=VALUE'
do not work.

(maint) Fix sysv-wrapper.sh to work with Solaris 10

---

configs/components/puppet.rb

eyaml is a commonly used executable. It is included with the
vendored hiera-eyaml gem.

(PA-2129) Include the eyaml executable in the bin directory

---

configs/components/leatherman.json

1.5.2 was manually tagged, and the bump to 1.5.3 put up too quickly
afterwards. That meant that the no-promote version bump commit was run
through CI at the same time as the promotable code change, and was
pulled in since there was at least one not-no-promote commit in the
run.

(maint) Pin leatherman back to 1.5.2

---

ext/build_defaults.yaml

The conflict in configs/components/puppet.json was resolved by maintaining the
state of the current branch. The conflict in ext/build_defaults.yaml was
resolved by taking changes from 5.3.x.

(maint) Merge 5.3.x -> 5.5.x

---

configs/components/rubygem-puppet-resource_api.json

This commit updates the embedded resource_api dependency to the latest
released version.

(maint) Bump puppet-resource_api to 1.6.2

---

acceptance/tests/validate_vendored_ruby.rb
configs/projects/puppet-agent.rb

Solaris uses SMF(https://www.oracle.com/technetwork/articles/servers-storage-admin/intro-smf-basics-s11-1729181.html) for managing services instead of the init script start-up mechanism. 
SMF does not require a PID files for managing a service.
If there is a helper script that requires a PID file and is passed to SMF instead of the application itself, the creation of the PID dir/file should be handled in the script. Example: https://github.com/puppetlabs/puppet/pull/7176/files#diff-6a024706b7725919079035ac75eb7621R29
this mechanism is similar as an init script for other platforms:
https://github.com/puppetlabs/pxp-agent/blob/master/ext/redhat/pxp-agent.init#L39

(maint) piddir not required on solaris

---

ext/smoke/helpers.sh
ext/smoke/repos/steps/setup-masters.sh
ext/smoke/steps/setup-agent.sh

Also move some exit status captures to be adjacent to the command of interest,
and make some exit code processing consistent.

(maint) fix regex to allow for build numbers other than 1

---

docker/Makefile

We should use `git fetch --unshallow` instead of `git pull --unshallow`
so we aren't merging. We should also use recursively expanded variables
for variables relating to versions so that they are set following the
execution of the 'prep' command.

(maint) Fixups for version determination in CI

---

configs/projects/puppet-agent.rb

There's no difference at this point between the 6.0.x and master runtimes, but we should use the matching version.

(maint) Use 6.0.x-specific puppet-runtime for agent 6.0.x

---

acceptance/tests/validate_vendored_ruby.rb
configs/components/cpp-pcp-client.rb
configs/components/facter.rb
configs/components/leatherman.rb
configs/components/puppet.rb
configs/components/pxp-agent.rb
configs/components/runtime.rb
configs/platforms/aix-6.1-ppc.rb
configs/platforms/aix-7.1-ppc.rb

There are some issues with the supporting changeset in beaker-puppet, so we need to revert this for now.  
Reverts puppetlabs/puppet-agent#1553

Revert "(maint) Use yum to install build/test dependencies on AIX"

---

acceptance/tests/ensure_SCL_python_pip_works.rb

The ensure_SCL_python_pip_works test uses redhat SCL packages to perform a
python 'pip' install so we can test that the pip provider still works with SCL
python.
However, the test uses actual SCL packages on centos and those are only
available for 64 bit platforms.
This commit updates the test to confine to 64 bit centos, and
https://tickets.puppetlabs.com/browse/PA-2386 has been opened to make the test
not rely on actual SCL packages in the future.

(maint) Confine SCL pip test to 64 bit centos

---

.travis.yml

This also uses the `--no-document` option as `--no-rdoc` and
`--no-ri` were removed in bundler 2.

(maint) update for bundler 2

---

docker/.gitignore
docker/Gemfile
docker/puppet-agent-alpine/spec/dockerfile_spec.rb
docker/puppet-agent-ubuntu/spec/dockerfile_spec.rb

This is the last project still referencing this gem, which we're
replacing in favor of the Docker CLI.

(MAINT) Remove puppet_docker_tools

---

configs/components/leatherman.rb
configs/platforms/osx-10.12-x86_64.rb

Homebrew has changed their boost to have a hard dependency on ICU,
which breaks our build. This pins to the last boost relaesed before
that change.

(maint) Pin homebrew boost

---

.gitignore

VANAGON-132 allows for platform- and project-specific build_metadata files; This
adjusts the .gitignore file to ignore any and all of them.

(maint) Update gitignore for build_metadata

---

configs/components/cpp-hocon.rb
configs/components/cpp-pcp-client.rb
configs/components/facter.rb
configs/components/leatherman.rb
configs/components/libwhereami.rb
configs/components/pxp-agent.rb
configs/platforms/fedora-29-x86_64.rb

This change cleans up the build on fedora 29 to use gcc 8

(PA-2362) Update fedora 29 to use GCC 8

---

configs/platforms/osx-10.12-x86_64.rb
configs/platforms/osx-10.13-x86_64.rb
configs/platforms/osx-10.14-x86_64.rb

agent packages > 6.0.x are built with a precontstructed boost in
puppet-runtime, rather than including libraries from a package
installed from brew
A recent mergeup from 5.5.x re-introduced the old boost package
installation, so this commit removes it.

(maint) Remove boost installation from build setup

---

configs/platforms/osx-10.12-x86_64.rb
configs/platforms/osx-10.13-x86_64.rb
configs/platforms/osx-10.14-x86_64.rb

In this commit: https://github.com/Homebrew/homebrew-core/commit/4c9da082d3cc20664ca78615b3ca26c62467ed19 homebrew has made icu4c a mandatory dependency for boost. The build for Leatherman fails if boost is compiled with icu4c enabled. To fix this issue we've pointed to the previous version of boost homebrew formula here: https://github.com/puppetlabs/puppet-agent/commit/6272f2608b36c25665f1422f9bd84accdc88dff0
A couple of days ago, Homebrew has removed dependencies for old compiles (cxx14): https://github.com/Homebrew/homebrew-core/commit/80584e1ba06664c2610707dc71c308f82b13895a breaking our builds:
`17:11:52 Error: boost: "cxx14" is not a recognized standard`
This is a temporary fix to get the builds passing until we find a better solution for this. The following Jira item has been …

(maint) Update brew formula for boost

---

ext/smoke/README.md
ext/smoke/helpers.sh
ext/smoke/packages/run-smoke-test.sh
ext/smoke/repos/run-smoke-test.sh

The smoke test scripts originally required a hostname only, and
incorrectly appended a domain when given an FQDN. This adjusts them to
only append a domain if needed.

(maint) Allow use of FQDNs in smoke test scripts

---

azure-pipelines.yml
docker/ci/build.ps1

- The 'latest' moniker is not used anywhere in Azure builds or tests
and could cause undesirable container usage when running the tests
from the 'pupperware' repo, so remove that part of the process
- Cleanup old containers / images
Output from cleanup
```
runing Containers
Total reclaimed space: 0B
Found puppet/puppet-agent-ubuntu images:
6.0.5 4719ef1b51ef 2019-02-09 01:50:51 +0000 GMT
6.2.0 ac5fc328a823 2019-02-06 19:05:49 +0000 GMT
latest ac5fc328a823 2019-02-06 19:05:49 +0000 GMT
6.1.0 74a2752e20f3 2019-01-11 22:35:38 +0000 GMT
6.0.4 e0303b20fa47 2019-01-11 22:28:12 +0000 GMT
Filtering removal candidates...
Removing Old puppet/puppet-agent-ubuntu Image 6.1.0 (74a2752e20f3) Created On 01/11/2019 22:35:38
Untagged: puppet/puppet-agent-ubuntu:6.1.0
Untagged: puppet/puppet-agent:6.1.0 …
```

(maint) Don't take Azure containers latest

---

configs/components/facter.rb

Just retargeting #1647 at 1.10.x here

(maint) Bump java to 1.7.1 on sles 11

---

configs/components/puppet-resource_api.json

Jenkins doesn't know how to do this automatically for resource_api.

(packaging) Update resource_api to refs/tags/v1.7.0.

---

ext/smoke/repos/run-smoke-test.sh

The script was updated to use helpers, but the sourcing of those helpers was missed.

(maint) add sourcing the helpers script to the repos run-smoke-test.sh

---

configs/components/leatherman.rb

This resolves CI failures introduced by the use of `add_compile_definitions` for leatherman on Solaris 10 and 11 (cmake 3.2.3 does not support this function).

(maint) Update pl-cmake on Solaris to version 3.12.4

---

.gitignore
ext/smoke/helpers.sh
ext/smoke/packages/run-smoke-test.sh
ext/smoke/packages/steps/setup-master.sh
ext/smoke/repos/run-smoke-test.sh
ext/smoke/repos/steps/setup-masters.sh
ext/smoke/steps/run-validation-tests.sh
ext/smoke/steps/setup-agent.sh

These three commits update the scripts in `ext/smoke` to address a few bugs and papercuts encountered during the 6.3.0 release:
- Guesses the puppet collection based on the puppet-agent version when no collection is explicitly specified (this allows us to stop hard-coding the default collection and keep the same code for 5.5.x and later branches)
- Passes collection arguments through from runner to helper scripts when they do exist
- Uses the `puppetserver ca` command for cert interaction when dealing with puppet >= 6

Several fixes to smoke test scripts

---

configs/components/facter.rb
configs/components/leatherman.rb
configs/components/pxp-agent.rb

Our Solaris Sparc builds are no longer finding our vendored openssl
libraries. This adds the explicit paths to our libssl.so and
libcrypto.so to cmake's linker flags to workaround this problem.

(PA-2499) Fix ssl linking issues for cmake based component builds

---

ext/build_defaults.yaml

This commit adds el-8-x86_64 to the set of `platform_repos`, which is used by
the packaging repo to build puppet-agent tarballs.

(maint) Add el-8-x86_64 to platform_repos

---

ext/build_defaults.yaml

this was accidentally removed in the merge-up from 1.10.x to 5.5.x: https://github.com/puppetlabs/puppet-agent/pull/1666/files
This PR readds this platform to build_defaults

(maint) readd redhatfips-7

---

ext/build_defaults.yaml

This change removes the Cumulus platform from ext/build_defaults.yaml.
Cumulus is not removed from acceptance/tests/validate_vendored_ruby.rb or
configs/platforms/cumulus-2.2-amd64.rb.

(PA-2561) Remove Cumulus Platform from build_defaults.yaml only

---

ext/smoke/steps/setup-agent.sh

`puppet cert clean  ${agent_vm}` is executed before the agent is setup. Because of this, the command exists with an error:
```
[root@r135q90bp2lvnym ~]# puppet cert clean ra35q90bp2lvnym.delivery.puppetlabs.net
Warning: 'puppet cert' is deprecated and will be removed in a future release.
(location: /opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/application.rb:370:in `run')
Error: Could not find a serial number for ra35q90bp2lvnym.delivery.puppetlabs.net
```
This PR ignores the error for `puppet cert clean  ${agent_vm}` that is executed before the agent setup

(maint) don't fail tests if agent is not registered.

---

ext/build_defaults.yaml

This was merged to the master branch after stop-ship/release branching for 6.4.0, and is needed in the 6.4.x branch, too.

cherry-pick "(maint) Update build_defaults.yaml rpm_targets for el-8"

---

ext/build_defaults.yaml

The 1.10.x release series is on extended support for a single customer.
This customer doesn't use OS X.
There is a PR to remove OS X from the pipeline: https://github.com/puppetlabs/ci-job-configs/pull/5781
This commit removes the OS X from the nightly ship because it will try to ship packages that were not built.

(maint) do not ship OS X 1.10.x to the nightly repos

---

docker/ci/build.ps1
docker/puppet-agent-alpine/Dockerfile
docker/puppet-agent-alpine/windows-build/Dockerfile

- This will give access to `dig` for diagnosing networking problems
and should only impact container size minimally

(maint) Add Alpine container bind-tools package

---

ext/build_defaults.yaml

We have removed sles-11 from 2016.4, dropping it here too to
unblock promotion for support escalation.

(maint) Remove sles-11 from rpm_targets so pe promotion works.

---

resources/files/aix-wrapper.sh

Prior to this commit, we cleared LD_LIBRARY_PATH on Linux based
agents, but not AIX.  This meant that customers with that set
globally on their system were subject to library loading errors.
With this commit, we clear the LD_LIBRARY_PATH just as we do on
Linux agents.

(PA-2668) Add LD_LIBRARY_PATH to environment cleanup in AIX wrapper

---

README.md
configs/projects/puppet-agent.rb

In the final steps of puppet-agent builds, the 'cleanup' component
removes many files that are unnecessary in finished packages, including
headers for libraries like boost.
This change introduces a new environment variable, $DEV_BUILD, that,
when set, will make vanagon skip the cleanup so that all files
(including headers) are retained in the final package. This is useful
for C++ some development workflows.
(This just hooks up an environment variable to control the existing `:dev_build` setting)

(maint) Allow for keeping headers with DEV_BUILD

---

acceptance/Gemfile

vcloud hyperisor is needed by the imaging pipelines so adding this to
the Gemfile.

(MAINT) Add Beaker vcloud hyperisor to Gemfile

---

configs/components/facter.rb
configs/components/hiera.rb
configs/components/puppet.rb

Between ruby 2.1 and 2.4, gem stopped being able to properly process
gemspecs if they did not match the pattern <gem>-<version>.gemspec. This
code updates the installation of the puppet, facter, and hiera gems to
include the version calculated from the git sources.

(PA-2670) Update puppet, facter, and hiera to include version in gemspec

---

configs/components/puppet-runtime.rb

Find utility is used by the `module tool`. Since some
Fedora minimal distributions could come without `find`
we add this as an dependecy to the `puppet-runtime`

(PA-2629) Add dependecy on `find` for puppet-agent

---

configs/components/cpp-hocon.rb
configs/components/cpp-pcp-client.rb
configs/components/facter.rb
configs/components/leatherman.rb
configs/components/libwhereami.rb
configs/components/puppet.rb
configs/components/pxp-agent.rb
configs/components/runtime.rb
configs/platforms/fedora-30-x86_64.rb
configs/projects/puppet-agent.rb

This commit contains the following changes:
- Add Fedora 30 to configs/platforms
- Build puppet-agent on Fedora 30 without pl-build-tools dependencies
Depends on:
- https://github.com/puppetlabs/pxp-agent/pull/750
- https://github.com/puppetlabs/puppet/pull/7543
- https://github.com/puppetlabs/puppet-runtime/pull/181

(PA-2677) Add Fedora 30 (amd64) to puppet-agent

---

configs/projects/facter-gem.rb
configs/projects/facter-source-gem.rb
configs/projects/puppet-agent.rb

PR that introduce 6.4.x runtime: https://github.com/puppetlabs/ci-job-configs/pull/5693

(maint) Use agent-runtime-6.4.x instead of master

---

resources/files/puppet-agent.sh

If 'set -u' is set in shell or bash then unset variables will exit non-zero. For scripts which need to use puppet and have this set we must ensure that puppet.sh can be sourced cleanly.

(PA-2692) Handle unset vars in /etc/profile.d/puppet.sh

---

ext/build_defaults.yaml

This commit removes `trusty-amd64 xenial-amd64` from
deb_targets and `sles-12-x86_64` from rpm_targets
Since we are not building deb/sles-12 packages.

(maint) Remove sles-12 and deb_targets

---

configs/platforms/debian-8-amd64.rb
configs/platforms/debian-8-i386.rb

A bug was introduced in the `python3.4` Jessie package, which is being tracked here: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=931044
This causes packaging jobs to fail on Debian 8 (Jessie), since package `devscripts` which is installed on this platform depends on `python3.4`.
Until this gets fixed, we need to confine `python3.4` and its dependencies to the previous version (3.4.2-1).

(PA-2752) Temporarily confine python3.4 on Jessie

---

docker/Makefile

This PR ignores the hadolint error code DL3028 that was added 4 days ago.
DL3028(https://github.com/hadolint/hadolint/wiki/DL3028) is similar to DL3008(https://github.com/hadolint/hadolint/wiki/DL3008) that is already in our ignore list

(maint) ignore hadolint DL3028

---

configs/platforms/debian-8-amd64.rb
configs/platforms/debian-8-i386.rb

This reverts commit 708091fbf48f78850700fceb5d10df212d967c1b.
Debian has [fixed](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=931097#10) the python3.4 installation bug, and published a new working version: 3.4.2-1+deb8u4. We can safely revert this workaround.

(PA-2752) Revert python3.4 version lock on Jessie

---

resources/windows/wix/customactions.wxs.erb

Previously, stderr was redirected to stdout after the file redirection, which is the incorrect order.
This commit redirects stderr after the file redirection.
@glennsarti, I applied your fix from the JIRA ticket. From an UNIX standpoint the order looks fine to me, however I fail to parse the additional redirect after 2>&1 in your initial suggestion:
```
Dim exitCode : exitCode = wshShell.Run(Command & " > """ & tempFilePath & """ 2>&1 > ", 0, True)
```
I removed it, can you confirm this looks right?

(PA-2691) Redirect stderr to stdout in MSI action

---

resources/files/aix-wrapper.sh
resources/files/osx-wrapper.sh
resources/files/sysv-wrapper.sh

Prior to this commit, Puppet subcommands that delegated to external
scripts or binaries, such as `puppet-query` or `puppet-infra`, would
show up as "not found" if `/opt/pupptlabs/bin` was not on the `PATH`.
This could commonly happen:
- Immediately after installation of Puppet or PE as the shell needs
to be re-started or re-freshed to pick up the effect of
`/etc/profile.d/puppet-agent.sh`
- When running `sudo puppet` in an environment where `/etc/sudoers`
has the `env_reset` option enabled (it is enabled by default).
This commit updates the wrapper scripts to ensure `/opt/puppetlabs/bin`
is on the `PATH` in addition to unsetting various environment variables
that affect where the linker looks for shared libraries.

(PA-2750) Ensure /opt/puppetlabs/bin is on the PATH

---

resources/files/puppet-agent.sh

Whoever implemented `MANPATH` apparently didn't do it like `PATH`.
By default, `MANPATH` is not set and man relies on paths specified in `/etc/man_db.conf`. When setting `MANPATH` to a single path, the default paths are overridden with this variable.
To make it work we need to prepend a colon to the exported variable, so that the search path gets extended instead of being replaced.
This is a regression introduced by https://github.com/puppetlabs/puppet-agent/pull/1728.
Thanks @KervyN for noticing and supplying a working version.

(PA-2768) Extend manpath instead of overriding it

---

resources/files/aix-wrapper.sh
resources/files/osx-wrapper.sh
resources/files/sysv-wrapper.sh

The bourne shell on Solaris 10 is not familiar
with the current export syntax:
`export PATH="${PATH:+${PATH}:}/opt/puppetlabs/bin"`
Updated the wrapper scripts to set the PATH and then export.

(PA-2769) Fix PATH set by wrapper scripts

---

azure-pipelines.yml

Don't trigger Azure twice when a PR is made from the main repo (not a
fork).

(MAINT) Prevent Azure double builds

---

acceptance/tests/test_manpage_clobber.rb

Since puppet-agent messes with MANPATH, this checks for path clobbering
by querying a system manpage along with the puppet manpage to ensure we
did not override the system man path.

(PA-2774) Add sanity check for manpages

---

ext/smoke/repos/steps/setup-masters.sh

When looking for the expected packages, the release field was hardcoded
to '1' for all packages. While for most packages this will work, release
packages often have multiple releases over their lifetime, so the test
was failing to pick up the release package. This updates the regex to
include the release field and allow that to be `[0-9]+`.

(maint) Fix repo smoke tests

---

resources/windows/wix/filter.xslt.erb
resources/windows/wix/registryEntries.wxs.erb

Changed the Windows Registry: Computer\HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\EventLog\Application\Puppet\EventMessageFile from [INSTALLDIR]puppet\bin\puppetres.dll to %SystemRoot%\System32\EventCreate.exe
This will create custom events and will not use puppetres.dll, as puppet/lib/puppet/util/windows/eventlog.rb does the same thing regarding events.
Now the EventCreate.exe will get locked and loaded into svchost.exe and will not
interfere with puppet-agent upgrade.
Note this fix will fix future puppet-agent versions, but to install the
fixed version when you have the bug, you have to use a workaround and
install puppet-agent with the msi_move_locked_files flag set to true.

(PA-2701) Fix DHCP restart on puppet-agent upgrade

---

ext/smoke/packages/run-smoke-test.sh

This commit updates the package smoke test script to send the version
parameters used to Artifactory. This will allow us to fetch the same parameters
for use in the repo smoke test that's run after the release.

(CPR-709) Send package smoke test params to Artifactory

---

ext/smoke/packages/run-smoke-test.sh

This commit updates the repo smoke test script to send parameters to Artifactory
as json instead of yaml. This allows us to make use of bash tools, like jq, that
already exist on the Jenkins workers that will consume these params.

(maint) Save smoke test params as json

---

configs/platforms/osx-10.12-x86_64.rb
configs/platforms/osx-10.13-x86_64.rb
configs/platforms/osx-10.14-x86_64.rb

* commit 'b2e59a5ac9ab2bd46b437ffaf6b82276b297e7be':
(PA-2893) pin boost to 1.60 on osx
(maint) Update puppet-runtime to 201909040
Conflicts:
configs/platforms/osx-10.14-x86_64.rb

(maint) Merge b2e59a5 to 6 0 x

---

configs/platforms/ubuntu-18.04-amd64.rb

Because of the install command from https://github.com/puppetlabs/vanagon/blob/master/lib/vanagon/platform/deb.rb#L102 and a new version of curl we end up with an interctive message:
```
There are services installed on your system which need to be restarted when
certain libraries, such as libpam, libc, and libssl, are upgraded. Since these
restarts may cause interruptions of service for the system, you will normally be
prompted on each upgrade for the list of services you wish to restart.  You can
choose this option to avoid being prompted; instead, all necessary restarts will
be done for you automatically so you can avoid being asked questions on each
library upgrade.
Restart services during package upgrades without asking? [yes/no]
```
This commits adds `DEBIAN_FRONTEND=noninteractive` …

(maint) fix curl install in ubuntu

---

configs/components/cpp-hocon.rb
configs/components/cpp-pcp-client.rb
configs/components/facter.rb
configs/components/leatherman.rb
configs/components/pxp-agent.rb

This is more future proof than disabling specific warnings based on OS version.

(maint) Disable cpp warnings on macOS

---

Gemfile

This commit updates the minimum packaging dependency to 0.99.43. This includes
support for windowsfips. Lately, bundler has begun installing old versions of
packaging in CI, so this update ensures that we use up-to-date packaging.

(maint) Update minimum packaging version

---

docker/Makefile

- Need a bundle update to be able to pull the pupperware spec_helper
(this primarily impacts local dev)

(maint) Make sure Docker test bundle is fresh

---

ext/build_defaults.yaml

This was already cherry-picked in master to speed up the process, since we need windowsfips just in master

(PA-2840) fix windowsfips build_details definition

---

azure-pipelines.yml
docker/Gemfile
docker/Makefile

Allows us to speed up calls to bundler by specifying groups to operate on.

(maint) Group gem dependencies

---

configs/components/module-puppetlabs-augeas_core.json
configs/components/module-puppetlabs-cron_core.json
configs/components/module-puppetlabs-host_core.json
configs/components/module-puppetlabs-mount_core.json
configs/components/module-puppetlabs-scheduled_task.json
configs/components/module-puppetlabs-selinux_core.json
configs/components/module-puppetlabs-sshkeys_core.json
configs/components/module-puppetlabs-yumrepo_core.json
configs/components/module-puppetlabs-zfs_core.json
configs/components/module-puppetlabs-zone_core.json

git:// urls use the default git protocol and are plaintext. To increase
the security during builds, I am switching it to https. This prodives
transport encryption and makes man in the middle attacks harder. The PR
is related to https://tickets.puppetlabs.com/browse/MODULES-8255 but
does not completely resolve it.

(MODULES-8255) switch vendored module git urls from git to https

---

configs/platforms/solaris-11-i386.rb
configs/platforms/solaris-11-sparc.rb

This PR removes solarisstudio publisher from Solaris 11 VMs. This publisher is not used in the agent pipeline

(maint) Remove solarisstudio

---

docker/Makefile
docker/ci/build.ps1

Verified Travis
> docker build --pull --build-arg vcs_ref=044948767d23656426c74e1a99506d94b63b3e7c --build-arg build_date=2019-10-27T07:02:52 --build-arg version=6.10.1 --file puppet-agent-ubuntu/Dockerfile --tag puppet/puppet-agent-ubuntu:6.10.1 puppet-agent-ubuntu
> docker build --pull --build-arg vcs_ref=044948767d23656426c74e1a99506d94b63b3e7c --build-arg build_date=2019-10-27T07:02:52 --build-arg version=6.10.1 --file puppet-agent-alpine/Dockerfile --tag puppet/puppet-agent-alpine:6.10.1 /home/travis/build/puppetlabs/puppet-agent/docker/..
~Azure builds behave differently on this repo, and don't emit the same info.~
Added extra commit for Azure to get:
> docker build --pull --build-arg vcs_ref=044948767d23656426c74e1a99506d94b63b3e7c --build-arg build_date=--build-arg version=6.10.1 …

(maint) Emit docker build command line

---

configs/components/cpp-hocon.rb
configs/components/cpp-pcp-client.rb
configs/components/facter.rb
configs/components/leatherman.rb

Harden Linux ELF binaries by compiling with PIE (Position Independent Executables) support, stack canary and full RELRO.
We only do this on platforms that use their default OS toolchain since pl-gcc versions are too old to support these flags.
Relevant flags are:
CPPFLAGS="-D_FORTIFY_SOURCE=2"
CFLAGS="-fstack-protector-strong -fno-plt"
LDFLAGS="-z,relro,-z,now"
The relevant settings are inherited from puppet-runtime, here we make sure we are putting them in the right places.
To be merged after a runtime with https://github.com/puppetlabs/puppet-runtime/pull/245 is promoted.

(PA-2986) Update GCC compiler/linker flags

---

configs/components/cfpropertylist.json
configs/components/cfpropertylist.rb
configs/projects/puppet-agent.rb

This commit removes CFProperty List component from puppet-agent as the
CFProperty List gem will be installed by puppet-runtime.

(PA-2780) CFPropertyList in wrong folder for PA

---

acceptance/tests/selinux.rb

This PR removes the SELinux test for running on the following platforms:
- ubuntu-14 - We do not provide Ruby SELinux on Ubuntu 14.04
- fedora 28 - Ticket: https://tickets.puppetlabs.com/browse/PA-3069
- el6 - require selinux workes on CentOS 6 and RedHat6 but fails on Amazon Linux 6. Ticket: https://tickets.puppetlabs.com/browse/PA-3068

(maint) ignore selinux test on ubuntu14, fedora28 and el6

---

.github/workflows/docker.yml
acceptance/tests/selinux.rb
configs/platforms/el-8-x86_64.rb
docker/Makefile
docker/distelli-manifest.yml
resources/windows/wix/localization/puppet_en-us.wxl
resources/windows/wix/ui/WarningDlg.wxs
resources/windows/wix/ui/WixUI_PuppetInstallDir.wxs.erb

* upstream/6.4.x:
(maint) Update puppet to 0cef45942416e8c1d53f669af136aa3dda521e20
(maint) ignore selinux test on ubuntu14, fedora28 and el6
(maint) Update puppet-runtime to 202001090
(maint) Update puppet-runtime to 202001090
(PA-3067) Add selinux test
(packaging) Bump to version '5.5.19' [no-promote]
(maint) remove distelli-manifest.yml
(maint) Makefile simplification
(maint) standardize makefile with master branch
(maint) Add github action for docker build
(PA-3018) Add warning for Win2008
(maint) Update puppet-runtime to 202001070

(maint) Merge up 6.4.x to master

---

configs/components/leatherman.rb

in cross compiled environment, boost could configure randomizer based on kernel sources on host that can be newer that the kernel running on target leading to errors at run-time:
```
terminate called after throwing an instance of 'boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<boost::uuids::entropy_error> >'
what():  getrandom
Aborted
```
See https://github.com/boostorg/uuid/issues/91

(maint) force posix boost random provider

---

configs/components/leatherman.rb

in cross compiled environment, boost could configure randomizer based on kernel sources on host that can be newer that the kernel running on target leading to errors at run-time:
```
terminate called after throwing an instance of 'boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<boost::uuids::entropy_error> >'
what():  getrandom
Aborted
```
See https://github.com/boostorg/uuid/issues/91

(maint) force posix boost random provider [cherry-pick] -> master

---

configs/components/leatherman.rb

in cross compiled environment, boost could configure randomizer based on kernel sources on host that can be newer that the kernel running on target leading to errors at run-time:
```
terminate called after throwing an instance of 'boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<boost::uuids::entropy_error> >'
what():  getrandom
Aborted
```
See https://github.com/boostorg/uuid/issues/91

(maint) force posix boost random provider [cherry-pick] -> 6.4.x

---

configs/platforms/osx-10.15-x86_64.rb
ext/build_defaults.yaml

(PA-2994) Add macOS 10.15 platform definition

---

configs/platforms/el-5-i386.rb
configs/platforms/el-5-x86_64.rb

The build-tools repository was added in 2014: https://github.com/puppetlabs/puppet-agent/commit/b6153b66ebd550192b57122da71ef14726dad864, the reason is unknown but looking through the history it seems that it has been replaced by pl-build-tools and was not removed from the build process.
This PR removes build-tools as it is no longer used for the build process and the endpoint was removed causing the build to fail:
```
23:04:31 Executing 'yum install -y --nogpgcheck  pl-gettext e2fsprogs-devel pl-cmake util-linux pl-gcc ' on 'root@[REDACTED]'
23:04:31 Warning: Permanently added '[REDACTED],[REDACTED]' (RSA) to the list of known hosts.
23:04:31 Loaded plugins: fastestmirror, security
23:04:31 Loading mirror speeds from cached hostfile
23:04:32 …
```

(maint) remove build-tools repository from el-5

---

configs/components/cpp-hocon.rb
configs/components/cpp-pcp-client.rb
configs/components/facter.rb
configs/components/leatherman.rb
configs/components/libwhereami.rb
configs/components/puppet.rb
configs/components/pxp-agent.rb
configs/components/runtime.rb
configs/platforms/ubuntu-20.04-amd64.rb
configs/projects/puppet-agent.rb

some conditions were rewritten to make adding new OSs not
needing pl-build-tools easier
this PR depends on:

(PA-3131) add support for Ubuntu 20.04

---

configs/platforms/ubuntu-20.04-amd64.rb

this is needed since `apt-get install devscripts` updated libc to a version that is not compatible
with the version installed by default om vmpooler images.
To overcome this:
- `devscripts` package in no longer upgraded (since is already installed)
- `libc6` marked as hold to detect early packages trying to update it
This workaround should be removed when image is updated with released iso version

(maint) remove descripts update

---

configs/platforms/ubuntu-20.04-amd64.rb

Reverts puppetlabs/puppet-agent#1881
devscripts are mandatory for building the puppet-agent.

Revert "(maint) remove descripts update"

---

configs/components/nssm.json

2.25.0 was tagged at 4951a7870b68c6f90f35745fecc1c0a42dc00401: https://github.com/puppetlabs/nssm/compare/2.24.2...2.25.0

(maint) Update nssm to 2.25.0

---

configs/components/facter-precompiled-gem.rb
configs/components/leatherman.rb
configs/platforms/windows-2012r2-x64.rb
configs/platforms/windows-2012r2-x86.rb
configs/platforms/windowsfips-2012r2-x64.rb

following artifactory update to 6.18.1, the version advertized as
latest changed to previous one for pl-toolchain package and now we
need to specifically request the latest version at least until issue
is checked/fixed on artifactory side

(maint) pin pl-toolchain version - 5.5.x (cherry-pick)

---

configs/components/facter-precompiled-gem.rb
configs/components/leatherman.rb
configs/platforms/windows-2012r2-x64.rb
configs/platforms/windows-2012r2-x86.rb
configs/platforms/windowsfips-2012r2-x64.rb

following artifactory update to 6.18.1, the version advertized as
latest changed to previous one for pl-toolchain package and now we
need to specifically request the latest version at least until issue
is checked/fixed on artifactory side

(maint) pin pl-toolchain version - master (cherry-pick)

---

configs/components/facter-precompiled-gem.rb
configs/components/leatherman.rb
configs/platforms/windows-2012r2-x64.rb
configs/platforms/windows-2012r2-x86.rb

following artifactory update to 6.18.1, the version advertized as
latest changed to previous one for pl-toolchain package and now we
need to specifically request the latest version at least until issue
is checked/fixed on artifactory side

(maint) pin pl-toolchain version - 1.10.x

---

.travis.yml
docker/Makefile

Turns on Buildkit to improve Docker build performance
Builds on #1889 
This turns out to be trickier than I originally anticipated, so I'm moving this effort to a separate PR.
From what I can tell, removing `gcr.io` from `daemon.json` and restarting Docker doesn't resolve the problem (as described in https://github.com/moby/buildkit/issues/606#issuecomment-453959632)
I solved this once before in https://github.com/puppetlabs/docker-pe-postgres/pull/18 ... there is a 30s penalty to upgrading Docker.
Another solution in Travis is to use the container that runs buildkit - i.e. https://travis-ci.community/t/docker-builds-are-broken-if-buildkit-is-used-docker-buildkit-1/2994/4
Some more ideas are here -- https://blog.alexellis.io/building-containers-without-docker/

(maint) Enable linux docker buildkit

---

docker/puppet-agent-alpine/Dockerfile

1.5.x branch of leatherman was incorrectly promoted to Puppet Agent master.
This branch was part of the 6.0.x release. Since we're no longer providing builds for this release the branch was deleted causing the PR tests to fail.

(maint) Use letherman master for PA master

---

.travis.yml

* pl/1.10.x:
(maint) increase the travis clone depth
(maint) Update puppet-runtime to 202004280
(maint) Add ability to load upstream metadata
Conflicts:
configs/projects/puppet-agent.rb
Conflict was resolved by keeping `agent_branch = '5.5.x'` on 5.5.x branch

(maint) Merge 1.10.x to 5.5.x

---

ext/build_defaults.yaml

deb_targets should only contain the deb platforms
that are supported as a master.

(maint) remove ubuntu 14.04 from deb_targets

---

docker/Makefile
docker/puppet-agent-alpine/Dockerfile
docker/puppet-agent-ubuntu/Dockerfile

This PR ensures that the base docker images are available before building the Puppet Agent containers.
On travis `--pull` build argument seems to be causing the following transient error:
```
#3 [internal] load metadata for docker.io/library/alpine:3.9
#3 ERROR: docker.io/library/alpine:3.9 not found
#9 [internal] load build context
#9 transferring context: 10.45kB done
#9 DONE 0.0s
#4 [build 1/3] FROM docker.io/library/alpine:3.9
#4 resolve docker.io/library/alpine:3.9 0.0s done
#4 ERROR: docker.io/library/alpine:3.9 not found
```

(maint) pull docker images before build

---

.travis.yml
azure-pipelines.yml
docker/Makefile

- Focal fossa time!
- No need to upgrade Docker for buildkit as image has 19.03 already,
so this should remove ~30s of setup time
- Switch to Ruby 2.6.6 for specs, which is known good and installed
- docker-compose in the 19.03 release included here is 1.23.1, so
continue to upgrade it on Travis to 1.25.5
- Separate out Travis operations so that logs have timings for lint, build and test

(maint) Switch Travis to Ubuntu 20.04 builder

---

configs/components/cpp-hocon.json
configs/components/cpp-hocon.rb
configs/components/cpp-pcp-client.rb
configs/components/facter.rb
configs/components/leatherman.rb
configs/components/libwhereami.rb
configs/components/pxp-agent.rb

This commit updates build configuration to prepare for boost 1.73.0. Two
changes were made:
1. Added -DBoost_NO_BOOST_CMAKE=ON to all cmake builds. That setting
will force cmake to ignore new cmake functions from boost > 1.70 that break
builds. See
https://cmake.org/cmake/help/v3.0/module/FindBoost.html#boost-cmake for more
details.
2. cpp-hocon has been updated to the HEAD of master to pick up
https://github.com/puppetlabs/cpp-hocon/commit/caab275509826dc5fe5ab2632582abb8f83ea2b3

(PA-3244) Changes to allow boost build 1.73.0

---

Rakefile
resources/files/aix-wrapper.sh
resources/files/osx-wrapper.sh
resources/files/sysv-wrapper.sh

As puppet-agent is delivered with his own ruby, ignore external ruby
envirment variables

(PA-3248) clean ruby env

---

configs/components/nssm.rb
configs/components/pxp-agent.rb
resources/windows/wix/customactions.wxs.erb
resources/windows/wix/sequences.wxs.erb
resources/windows/wix/service.pxp-agent.wxs.erb

Before this fix, if the puppet-agent upgrade on Windows was performed
while nssm.exe was loaded by EventLog service, many services, including
critical ones lihe dhcp/dns clients were restarted, leading to unreachable
machines.
With this commit we deliver dedicated nssm executable for pxp-agent
(nssm-pxp-agent.exe) and we remove windows registry references to old
nssm.exe in a WiX custom action.

(PA-3263) fix nssm lock - 5.5.x

---

configs/components/nssm.rb
configs/components/pxp-agent.rb
resources/windows/wix/customactions.wxs.erb
resources/windows/wix/sequences.wxs.erb
resources/windows/wix/service.pxp-agent.wxs.erb

Before this fix, if the puppet-agent upgrade on Windows was performed
while nssm.exe was loaded by EventLog service, many services, including
critical ones lihe dhcp/dns clients were restarted, leading to unreachable
machines.
With this commit we deliver dedicated nssm executable for pxp-agent
(nssm-pxp-agent.exe) and we remove windows registry references to old
nssm.exe in a WiX custom action.

(PA-3263) fix nssm lock - master

---

configs/components/facter-ng.json

This is needed because the existing ref does not exist on facter 4.x(is on facter-ng) and the promote check fails.

(maint) update facter-ng to 66866b320444ab530d58d91d46ef6ddf5fd3fd1c

---

configs/components/facter-ng.json

This reverts commit acac8ca70a797004414b861f322998d44541afa7, reversing
changes made to 5995eb4eeb3f7701d13a660c1ad7950210b98197.
This is needed because Vanagon does not support two different components form the same repo.

Revert "Merge pull request #1920 from gimmyxd/maint/bump_facter-ng"

---

configs/projects/puppet-agent.rb

This will make building with non-tagged runtimes (or locally built
artifacts) possible.
This was made possible by
https://github.com/puppetlabs/vanagon/pull/651.

(maint) Use an alternative filename for the build metadata

---

acceptance/tests/ensure_puppet_facts_can_use_facter_ng.rb

`augeas` is not provided in Puppet AIO on windows, as such it should be excluded from the test on all windows versions.

(maint) Fix facterng acceptance test on windows

---

acceptance/tests/ensure_puppet_facts_can_use_facter.rb

Update facter accetance test to exclude augeas on windows as it is not provided on Windows. Implies the same change as #1939 but for the `next` branch.

(maint) Fix facter accetance test on windows

---

acceptance/lib/puppet/acceptance/fact_dif.rb
acceptance/tests/ensure_facter_3_and_facter_4_output_matches.rb

Compare Facter 3 with Facter 4 output. We are able to exclude facts via the `EXCLUDE_LIST `. The excluded fact name can also be a regex because there are fact names that are built dynamically.

(FACT-2738) Write acceptance test that compares Facter 3 and Facter 4 output

---

acceptance/tests/ensure_facter_3_and_facter_4_output_matches.rb

Fact `sshecdsakey` is not implemented on AIX. Added it to ignore list.

(FACT-2738-fix) Add `sshecdsakey` fact to ignore list

---

configs/components/runtime.rb
configs/projects/puppet-agent.rb

Now that we merged all Ruby 2.7 blockers we can finally switch to the `main` runtime for puppet-agent#main.
This should be the same as the other agent runtimes, with Ruby bumped to 2.7.1 and the remaining win32 gems (service, process, dir, security) removed.

(PA-3349) Switch to `main` runtime for puppet-agent#main

---

resources/windows/wix/customactions.wxs.erb
resources/windows/wix/sequences.wxs.erb

Before this fix, if the registry key `HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Installer\UserData\S-1-5-18\Components`
is not existing, installer will fail on Windows
(this is the case on few Google Cloud Windows Server images)
After this fix, nssm custom action:
- tries to remove nssm component from registry only if the `...\Components` key exists
- fails if nssm component is found in registry and cannot be removed (can happen if
UAC is enabled and current user is not Administrator).

(PA-3351) fix registry handling in nssm custom action (5.5.x)

---

resources/windows/wix/condition.wxs.erb
resources/windows/wix/ui/WixUI_PuppetInstallDir.wxs.erb

This PR blocks the installation of the Puppet Agent msi on Windows versions older than 2012.
The change is done only on the Platform 7 stream.

(PA-3364) Disable Puppet Agent installation on Windows 2008 and 2008R2

---

acceptance/tests/ensure_puppet-agent_paths.rb
configs/components/puppet.rb
resources/windows/wix/appdatafiles.wxs

In [PUP-10627](https://github.com/puppetlabs/puppet/pull/8277) the `last_run_summary.yaml` file location (to `/opt/puppetlabs/puppet/public` on Linux and `C:\ProgramData\PuppetLabs\puppet\public` on Microsoft Windows) and permissions (to `0755`) changed and this commit aligns the puppet component to those changes. It also sets accordingly the new cli config parameter called `publicdir`.
TODO before merging this:

(PA-3253) Aligns with last_run_summary.yaml file puppet changes

---

configs/platforms/osx-10.14-x86_64.rb
configs/platforms/osx-10.15-x86_64.rb

osx provisioning fails as boost 1.60 was disabled on homebrew (https://github.com/Homebrew/homebrew-core/commit/d18d380bbbf90808088460cd244c828171263196)

(maint) do not provision boost on osx (5.5.x)

---

configs/components/module-puppetlabs-sshkeys_core.json
configs/components/module-puppetlabs-zfs_core.json

passing ad-hoc: https://jenkins-master-prod-1.delivery.puppetlabs.net/view/puppet-agent/view/ad-hoc/job/platform_puppet-agent-extra_puppet-agent-integration-suite_adhoc-ad_hoc/859/

(PA-3363) Bump sshkeys_core to 2.1.0 and zfs_core to 1.1.0

---

acceptance/tests/ensure_puppet_facts_can_use_facter_ng.rb

The `ensure_puppet_facts_can_use_facter_ng.rb` test fails because of a Facter 4 debug message on `rhel5`. We will be able to reenable the test once we release a new version of Facter.

(maint) Ignore facterng acceptance test on rhel5

---

acceptance/lib/puppet/acceptance/fact_dif.rb
acceptance/tests/ensure_facter_3_and_facter_4_output_matches.rb

- Improve comparison of strings that contain multiple elements divided by `,`. The new implementation splits the string and tries to find each element, ignoring the order.
- Exclude the fact compare test from `rhel5` as it is not supported by Facter 4. 
- Update `EXCLUDE_LIST` list.

(FACT-2747) Add missing legacy facts.

---

acceptance/tests/ensure_puppet-agent_paths.rb
configs/components/puppet.rb

Omit the default legacy auth.conf in puppet-agent packages for new installs.
During an upgrade, the old file will be left as-is and ignored.

(maint) Omit legacy auth.conf from puppet-agent packages

---

acceptance/tests/ensure_puppet_facts_can_use_facter_ng.rb

This test was skipped because of a bug in Facter. As the bug was fixed and a new version of Facter was released, this test can be enabled again.

(maint) Enable acceptance test for Rhel5

---

configs/components/puppet.rb

PUP-3721[1] included an additional parameter in the `puppet resource`
command output which had the side effect of changing the indentation of
the output. As such, attempting to match `ensure =>` no longer works.
This causes agent upgrades on RPM-based SysV platforms and AIX to no
longer start the puppet service after the upgrade finishes.
Make the regex more permissive in order to account for any number of
spaces between `ensure` and `=>`.
[1] https://github.com/puppetlabs/puppet/commit/7a92874522d6540157168fd025174bba3b816c64

(PA-3405) Fix puppet resource output matching

---

configs/platforms/el-8-aarch64.rb

(PA-3388) add native platform redhat-8-aarch64

---

acceptance/tests/ensure_facter_3_and_facter_4_output_matches.rb

Remove checking diffs between Facter 3 and Facter 4 until Facter 4 is released.

(maint) remove RHEL 8 AARCH from Facter diff tests

---

resources/files/puppet-agent.sh

Not maybe a very common case in general, but for example easy to spot when in WSL.

(maint) Work correctly also if PATH contains spaces

---

configs/components/leatherman.json

The last leatherman tag was done on a `[no-promote]` commit and caused puppet-agent to not promote it (seen in `leatherman.json`). This commit bumps letherman to the latest tag.

(maint) Bump leatherman version to 1.4.13

---

resources/windows/wix/appdatafiles.wxs
resources/windows/wix/customactions.wxs.erb
resources/windows/wix/properties.wxs.erb
resources/windows/wix/sequences.wxs.erb

Add `PUPPET_SERVER_PORT` installer property to be used to
configure puppet `serverport` setting

(PA-3401) Provide MSI property to configure serverport setting

---

acceptance/tests/ensure_puppet_facts_can_use_facter.rb

https://github.com/puppetlabs/puppet/pull/8313 added the `puppet facts show`
action using Facter 4 and https://github.com/puppetlabs/puppet/pull/8402 updated it
to be the default for `puppet facts`.
After the format was changed, to resemble
Facter 4 output, the test needs to be also adapted
for the new output.

(maint) update puppet facts test

---

configs/components/facter.rb

In Agent 6 we create the `install_root/facter/facts.d` directory during installation time.
This PR enables this on Puppet Agent 7

(maint) ensure facter/facts.d directory is created

---

configs/components/module-puppetlabs-cron_core.json
configs/components/module-puppetlabs-zfs_core.json

The `puppetlabs-zfs_core` module version `1.2.0` and `puppetlabs-cron_core` module version `1.0.5` got released and this commit bumps their version accordingly in puppet agent.

(maint) Bump zfs_core and cron_core modules version

---

acceptance/tests/ensure_puppet-agent_paths.rb

This PR updates the path test to also check that:
* C:\ProgramData\PuppetLabs\facter\facts.d - on Windows
* /opt/puppetlabs/facter/facts.d - on *nix
exist

(maint) test facter directories

---

acceptance/tests/validate_vendored_ruby.rb

we are missing `sqlite3-devel` package from our sles-12-ppc64el repo mirror
skip the test until mirroring is fixed

(maint) skip `validate_vendored_ruby` test on sles-12-ppc64el

---

acceptance/tests/ensure_puppet-agent_paths.rb
acceptance/tests/validate_vendored_ruby.rb
resources/windows/wix/customactions.wxs.erb
resources/windows/wix/sequences.wxs.erb
resources/windows/wix/ui/PuppetInstallDirDlg.wxs

Merge remote-tracking branch 'upstream/master' into main
* upstream/master:
(PA-3440) add new property PUPPET_SERVER it should behave like alias to existing PUPPET_MASTER_SERVER
(maint) skip `validate_vendored_ruby` test on sles-12-ppc64el
(maint) test facter directories
(maint) Update puppet to 3a701d147c2b7130962527922a842893d31a104d
(maint) Bump zfs_core and cron_core modules version
(maint) Bump facter version to the newest released one.
Conflicts:
acceptance/tests/ensure_puppet-agent_paths.rb
configs/components/facter-ng.rb
ensure_puppet-agent_paths test conflict was due to indentation changes in
cb16fb805 in main. This commit preserves the indentation and addition of
`facts.d` test from master, while preserving the publicdir test and removal of
rest_authconfig.
facter-ng component …

(maint) Merge master to main

---

configs/components/facter.json

Previous version did not have lib/facter/version.rb bumped.
This bumps facter to 4.0.46. 4.0.45 was never released.

(packaging) Bump facter to d405b8c0

---

README.md

This commit removes remaining harmful terminologies from `README.md` file.

(maint) Remove harmful terminology from README.md

---

configs/platforms/aix-7.1-ppc.rb

This is intermediary step of AIX6.1 removal on 5.5.x

(PA-3435) update platform to build AIX7.1 runtime on 5.5.x

---

ext/smoke/steps/setup-agent.sh

Puppet collections 6 and higher should use the `puppetserver` command to sign certs.

(PA-3452) Update cert sign command for smoke script

---

ext/build_defaults.yaml

See https://github.com/puppetlabs/puppet-agent/pull/2021.

(maint) Remove repo_link_target for puppet6

---

docker/puppet-agent-alpine/Dockerfile

Adding `-DENABLE_CXX_WERROR=OFF` will disable compiler warnings and
we will be able to build with newer compiler versions

(maint) remove gcc/g++ version pin

---

configs/platforms/el-6-i386.rb
configs/platforms/el-6-x86_64.rb

Because CentOS 6 went end of life[1], the upstream repos are no longer available, the PR sets the build VMs to RedHat 6  instead of CentOS 6
1. https://phoenixnap.com/kb/centos-6-eol

(maint) build el-6 on redhat instead of centos

---

acceptance/tests/validate_vendored_ruby.rb

Somehow the Solaris host still has an uncompressed tarball from a previous run
causing the `gunzip` command to fail:
gzip: sol-11-i386-compiler.tar already exists; not overwritten
Use `gunzip -f` so we overwrite an existing tarball and delete the tarball after
extracting its contents.

(maint) Overwrite existing tarball

---

acceptance/tests/ensure_facter_3_and_facter_4_output_matches.rb

Exclude the blockdevice size and vendor facts from the facter 3/4
acceptance tests, until we release a new Facter version containing
https://github.com/puppetlabs/facter/pull/2238.

(maint) Exclude some legacy blockdevice facts

---

Gemfile
configs/components/puppet.rb
configs/components/pxp-agent.rb
configs/platforms/debian-8-amd64.rb
configs/platforms/debian-8-armel.rb
configs/platforms/debian-8-armhf.rb
configs/platforms/debian-8-i386.rb
configs/platforms/debian-9-amd64.rb
configs/platforms/debian-9-i386.rb

Needs https://github.com/puppetlabs/vanagon/pull/684 and vanagon release
Systemd check was updated to the one used in systemd service provider.

(PA-2028) Update to support running debian under systemd or sysv

---

configs/components/puppet.rb
configs/components/pxp-agent.rb

while solving original commit rebase conflicts, the 1.10.x windows
service definition was selected which is no longer working on 6.x
this commit should fix the windows service definition

(PA-2028) fix windows services definition for puppet and pxp-agent

---

ext/smoke/helpers.sh

smoke tests are failing using pgdg-redhat-repo-42.0-9 since the
upstream repo is no longer maintaining 9.4 postgres version
bumping to package pgdg-redhat-repo-42.0-11 solves the issue

(maint) bump pgdg-redhat-repo package

---

configs/components/facter-ng.json
configs/components/facter-ng.rb

In order to be able to use the latest commit from
facter#main we need to have facter-ng as a git
component.
Things to do before merging this:

(PA-3570) convert facter-ng to a git component

---

acceptance/tests/ensure_facter_3_and_facter_4_output_matches.rb

Filter out facts that are only on Facter 4
- macosx_productversion.*
- os.macosx.version
https://tickets.puppetlabs.com/browse/FACT-2914
https://tickets.puppetlabs.com/browse/FACT-3031
```
tests/ensure_facter_3_and_facter_4_output_matches.rb passed in 29.13 seconds
Test Suite: tests @ 2021-04-23 15:49:26 +0300
- Host Configuration Summary -
- Test Case Summary for suite 'tests' -
Total Suite Time: 29.13 seconds
Average Test Time: 29.13 seconds
Attempted: 1
Passed: 1
Failed: 0
Errored: 0
Skipped: 0
Pending: 0
Total: 1
```
Fixes the following failure:
```
Test Case tests/ensure_facter_3_and_facter_4_output_matches.rb reported: #<Beaker::DSL::Outcomes::FailTest: 
00:30:05.312 Facter 3 and Facter 4 outputs have the fallowing differences:  {"macosx_productversion_major"=>{:new_value=>"\"11\"", …
```

(maint) filter facts on macOS 11 

---

resources/windows/wix/properties.wxs.erb
resources/windows/wix/registryEntries.wxs.erb
resources/windows/wix/sequences.wxs.erb

Previously using PUPPET_SERVER .msi property would
not correctly set puppet server.
Now it is correctly linked.
PUPPET_MASTER_SERVER also works.

(PA-3667) PUPPET_SERVER .msi property

---

.travis.yml
docker/puppet-agent-alpine/Dockerfile

- Instead of incurring the upgrade cost to Travis 20.10, use the
existing 19.03 version.
In practice, upgrading Docker in Travis turned out to be unreliable.
To enable buildx requires installing the plugin from the github
releases page. Using the experimental cli flag was supposed to enable
the plugin for 19.03, but didn't seem to work in the Travis env.
- Also adds missing generation of named buildx builder to 6.x branch

(maint) Use Docker 19.03 in Travis again

---

configs/components/facter-ng.rb

We changed the restrictions for Ruby version in
facter-ng.gemspec[1] which requires changes to the
sed pattern used on cross platforms.
Updated the pattern to delete the entire line if it
matches `spec.required_ruby_version`.
[1] puppetlabs/facter@2ba2c20

(maint) update sed pattern for cross compiled

---

configs/platforms/el-8-ppc64le.rb

RedHat recently updated their repos and the cmake version pulled is newer (3.18.2). This uses a libarchive method that is not available on 3.3.2 which is the one that comes with the box.
`cmake: symbol lookup error: cmake: undefined symbol: archive_write_add_filter_zstd`
This can either be fixed by updating the libarchive package to 3.3.3, or by pinning cmake to the previous working version (3.11.4). Pin cmake for now.

(maint) Pin cmake on el-8-ppc64le

---

configs/platforms/el-8-aarch64.rb

Same fix as [PR#2103](https://github.com/puppetlabs/puppet-agent/pull/2103) but for el-8-aarch64
RedHat recently updated their repos and the cmake version pulled is newer (3.18.2). This uses a libarchive method that is not available on 3.3.2 which is the one that comes with the box.
cmake: symbol lookup error: cmake: undefined symbol: archive_write_add_filter_zstd
This can either be fixed by updating the libarchive package to 3.3.3, or by pinning cmake to the previous working version (3.11.4). Pin cmake for now.

(maint) Pin cmake on el-8-aarch64

---

.rubocop.yml
Gemfile
configs/platforms/fedora-34-x86_64.rb
ext/build_defaults.yaml

* 6.x:
(PA-3604) Add Fedora 34 x86_64 platform definition
(maint) Update leatherman to 9b13c5c9cf712e7bc6bb892df08b1acce69a4af6
(VANAGON-85) add output_dir to mac OS
(maint) Update puppet to 8d21da1425750d1ae7b399e67c7d7a4e2da33d31
(maint) Update puppet to 8fc33e8b55ec4d178364d837d18336f7d7331e27
(VANAGON-85) add inherit_from_default to OS X 11
(VANAGON-85) Move platform definitions into core vanagon. Inherit definitions from a default platform.
(PA-3605) Add Fedora 34 x86_64 to build_defaults.yaml
VANAGON-85 changes will be handled in a separate PR.

(maint) Merge up 6.x to main

---

configs/platforms/el-8-x86_64.rb

Due to `cmake: symbol lookup error: cmake: undefined symbol: archive_write_add_filter_zstd`

(maint) pin cmake to 3.11.4

---

configs/platforms/solaris-11-i386.rb
configs/platforms/solaris-11-sparc.rb

Solaris packages should not be shipped in folders
per architecture, they are all in the same location.
```diff
--- from_file
+++ failing 1e31c88b6b8478749420c1944f355057d54c4717
@@ -1,4 +1,4 @@
-passing  84b6df9aacf984149f36a0372d6bac6728be4206
+failing 1e31c88b6b8478749420c1944f355057d54c4717
aix
apple
@@ -135,7 +135,7 @@
./el/8/puppet6/x86_64:
./fedora:
-30  31  32
+30  31  32  34
./fedora/30:
puppet6
@@ -160,6 +160,14 @@
x86_64
./fedora/32/puppet6/x86_64:
+
+./fedora/34:
+puppet6
+
+./fedora/34/puppet6:
+x86_64
+
+./fedora/34/puppet6/x86_64:
./redhatfips:
7
@@ -215,6 +223,11 @@
puppet6
./solaris/11/puppet6:
+i386  sparc
+
+./solaris/11/puppet6/i386:
+
+./solaris/11/puppet6/sparc:
./windows:
```

(VANAGON-85) fix solaris 11 location

---

configs/platforms/el-8-aarch64.rb
configs/platforms/el-8-ppc64le.rb
configs/platforms/el-8-x86_64.rb

https://github.com/puppetlabs/puppet-agent/pull/2108 locked cmake to 3.11.4 to overcome an issue with libarchive 3.3.2.
The issue was fixed in libarchive 3.3.1 bugs.centos.org/view.php?id=18212
depends on https://github.com/puppetlabs/vanagon/pull/697

(maint) install `libarchive` on el-8

---

configs/components/facter-ng.json

On main we do not use the facter-ng component.
This probably got merged-up by jenkins

(maint) remove facter-ng.json

---

acceptance/tests/ensure_macos_executables_are_signed.rb
configs/projects/puppet-agent.rb

builds available for main branch on under `9933b8fa7b66de8f99fe7dafc71e4cb8f1878e75` ref
depends on: https://github.com/puppetlabs/vanagon/pull/700
```
Ensure puppet executables are codesigned on mac OS
* test /opt/puppetlabs/bin/puppet
host (host) 09:08:20$ codesign -vv /opt/puppetlabs/bin/puppet
/opt/puppetlabs/bin/puppet: valid on disk
/opt/puppetlabs/bin/puppet: satisfies its Designated Requirement
host (host) executed in 3.15 seconds
* test /opt/puppetlabs/puppet/bin/puppet
host (host) 09:08:23$ codesign -vv /opt/puppetlabs/puppet/bin/puppet
/opt/puppetlabs/puppet/bin/puppet: valid on disk
/opt/puppetlabs/puppet/bin/puppet: satisfies its Designated Requirement
host (host) executed in 1.01 seconds
* test /opt/puppetlabs/puppet/bin/pxp-agent
host (host) 09:08:25$ codesign -vv …
```

(PA-3756) codesign entry-points on mac OS

---

configs/components/wrapper-script.rb
resources/aix/pxp-agent.service

This was something we forgot to do as part of PA-437. Note that we'll
also need the wrapper script for Solaris and OSX; their service scripts
will be updated accordingly in the pxp-agent repo.
Signed-off-by: Enis Inan <enis.inan@puppet.com>

(PCP-890) Use wrapper script when starting pxp-agent for AIX

---

configs/components/puppet.json

Bump puppet to e89bc9f1e0 to pull in the commit from https://github.com/puppetlabs/puppet/commit/bbc6d413ce048712388699d54f0fe466e2b972e8

(maint) Update puppet to e89bc9f1e0

---

configs/components/puppet.json

Bump puppet to c9407626cb to pull in the commit from https://github.com/puppetlabs/puppet/commit/bbc6d413ce048712388699d54f0fe466e2b972e8
Actual commit https://github.com/puppetlabs/puppet/commit/c9407626cbf62b776ca60f9d814d76691e9f293f

(maint) Update puppet to c9407626cb

---

configs/components/cpp-hocon.rb
configs/components/cpp-pcp-client.rb
configs/components/facter.rb
configs/components/hiera.rb
configs/components/leatherman.rb
configs/components/libwhereami.rb
configs/components/pl-ruby-patch.rb
configs/components/pxp-agent.rb
configs/components/runtime.rb
configs/platforms/osx-11-arm64.rb

Add support for building the puppet-agent project for macOS 11 ARM64 (M1) via cross-compilation from an x86 host.
ARM64 package (shipped to the wrong directory but fixed it afterwards): http://builds.delivery.puppetlabs.net/puppet-agent/291a6e60a792848ebe95aa11ad6b6d922759823b/artifacts/apple/11/puppet6/x86_64/puppet-agent-6.19.1.483.g291a6e60a-1.osx11.dmg
How to confirm:
```sh-session
> curl -O http://builds.delivery.puppetlabs.net/puppet-agent/291a6e60a792848ebe95aa11ad6b6d922759823b/artifacts/apple/11/puppet6/x86_64/puppet-agent-6.19.1.483.g291a6e60a-1.osx11.dmg
> hdiutil attach puppet-agent-6.19.1.483.g291a6e60a-1.osx11.dmg
> xar -xf /Volumes/puppet-agent-6.19.1.483.g291a6e60a-1.osx11/puppet-agent-6.19.1.483.g291a6e60a-1-installer.pkg
> tar xvf …
```

(PA-3829) Add macOS 11 arm64 platform

---

ext/smoke/helpers.sh

The previous URL for the pgdg repo does not provide the repo anymore.
Update to a working URL and to the latest version which is the only one available.

(PA-3854) Fix pgdg repo location in smoke test

---

configs/components/hiera.rb
configs/components/pl-ruby-patch.rb
configs/platforms/osx-11-arm64.rb
ext/smoke/helpers.sh

Merged up from 6.x:
-   (maint) Update facter-ng to f4094d9624d0984d861656e7e205a978f86fb84d
-   (maint) Update puppet to 1d6f9e61ef4c3350f55ef60a4ab66eaabbca7d4b
-   (maint) fix compilation
-   (maint) Update facter-ng to b2d2757ec7a54da0341563b83b1abda7dbe460ec
-   (maint) Fix release-lead.rake to properly clone both facter and facter-ng
-   (maint) Update puppet-runtime to 202107140
-   (PA-3854) Fix pgdg repo location in smoke test
-   (PA-3829) Add macOS 11 arm64 platform
Conflicts:
- 	configs/components/facter.rb
- 	configs/components/pl-ruby-patch.rb
- 	configs/components/puppet.json
- 	configs/components/pxp-agent.rb
Conflict was due to macOS 11 arm64 platform addition.

(maint) Merge up `6.x` into `main`

---

resources/windows/wix/customactions.wxs.erb
resources/windows/wix/properties.wxs.erb
resources/windows/wix/sequences.wxs.erb
resources/windows/wix/ui/WixUI_PuppetInstallDir.wxs.erb

Add `Enable Long Path Names` checkbox at the ExitDialog window, which adds the LongPathsEnabled registry key, and sets its value to 1
Picture of the new option:
Also added command line option to enable long path names (`ENABLE_LONG_PATHS`), and updated the powershell logic to check if the registry was already set correctly.

(PA-3843) Add option to enable long path names in the Windows Installer

---

configs/components/facter.rb

This commit aligns Puppet Agent 7 with Puppet Agent 6 and packages `facter_interactive.bat` and `run_facter_interactive.bat`. The files already existed on the repository before this commit but they were not packaged.
----
Manually tested these changes using:
1. Checking existence of files (cmd):
```cmd
➜ cd "C:\Program Files\Puppet Labs"
➜ dir *facter_interactive* /s /p
Volume in drive C is Windows
Volume Serial Number is 60DE-2A91
Directory of C:\Program Files\Puppet Labs\Puppet\bin
09/14/2021  07:52 AM                87 facter_interactive.bat
09/14/2021  07:52 AM               136 run_facter_interactive.bat
2 File(s)            223 bytes
Total Files Listed:
2 File(s)            223 bytes
0 Dir(s)  49,301,872,640 bytes free
➜ puppet --version
7.11.0
```
2. Trying `START ➜ Puppet ➜ Run …

(PA-3700) Add `facter_interactive.bat` and `run_facter_interactive.bat` in Puppet Agent 7

---

ext/smoke/helpers.sh

The previous URL for the pgdg repo returns 404 Not Found.
Updated with a newer version and updated certificates
with `yum install -y ca-certificates` as it could not
verify download.postgresql.org's certificate

(maint) Pgdg repo location + certificate fix

---

.rubocop.yml
configs/components/facter-precompiled-gem.rb
configs/components/leatherman.rb

* Opt into new cops via `NewCops`
* Ignore the duplicate `platform.is_windows?` branch as all `build_requires` are
defined first, followed by defining commands.
* Add parenthesis to fix Lint/AmbiguousOperatorPrecedence

(maint) Enable new cops

---

configs/components/puppet.rb

Commit f66fdcb95 enabled several rubocops, but the `puppet` component didn't
fail until the change was merged to `main`.

(maint) Ignore duplicate branch

---

ext/smoke/helpers.sh

The package version has changed, this changes the URL accordingly.

(maint) Updates postgres URL for smoke test

---

acceptance/tests/validate_vendored_ruby.rb

When building on solaris, gcc si set to /opt/pl-build-tools/bin/
https://github.com/puppetlabs/puppet-runtime/blob/2a73942cf6a65a2f201c292e3bd1014685a66cda/configs/components/_base-ruby.rb#L30
but when running tests it will need gcc provided by pl-build-tools installed in /opt/pl-build-tools/i386/bin/
Created a sim_link in case something else uses gcc from /opt/pl-build-tools/bin/

(maint) sim_link gcc for solaris

---

configs/components/facter.rb

See https://github.com/puppetlabs/puppet-agent/commit/a036837f89fa6e7477963aee6a5c8add968693f1 for an example of the last time this was needed.
I don't _think_ this is necessary in 7.x anymore, with the move to Facter 4. The config file looks totally different now.

(FACT-3101) Build Facter for JRuby on debian 11

---

configs/components/facter.json
configs/components/puppet.json

This change had to be done again since the vanagon component
promotion script was not updated and it changed back sources
from https:// to git://
depends on https://github.com/puppetlabs/ci-job-configs/pull/8196

(maint) change components sources git:// to https://

---

acceptance/tests/facter_output/puppet_facts_output.rb

Change the fact collection script to respect facterdb conventions, and obfuscate certain facts.
- call `facter -p` instead of `puppet facts`
- include legacy facts
- construct filename using the appropriate facts
- obfuscate a predefined list of facts

(FACT-3065) Update fact collection script

---

configs/components/facter.json
configs/components/hiera.json
configs/components/puppet-resource_api.json

Replacing Git protocol since it will no longer be supported.

(maint) PA-4182 replace git:// with https://

---

ext/build_defaults.yaml

redhatfips-8 as an rpm target is needed by puppet-enterprise-vanagon to build PE packages.

(RE-14411) Add redhatfips-8 as an rpm target

---

Gemfile

Support for el-9 was added to packaging in 0.105.0; update the Gemfile to reflect that

(maint) Pick up rhel 9 packaging support

---

acceptance/util/puppet_facts_output.rb

Previously we were directly shelling out to cygwin on Windows boxes, causing the facter command to fail with:
bash: facter: command not found
Fortunately, there's a helper `facter` method that properly namespaces the executable for the target platform:
cmd.exe /c facter --show-legacy -p -j

(maint) Fix fact collection script on Windows

---

configs/platforms/el-8-x86_64.rb

With recent EOL of centos-8 builds have started to fail using centos-8.
This PR switches centos-8-x86_64 for redhat-8-x86_64.

(maint) In el-8-x86 platform switch centos-8 for redhat-8-x86_64

---

.github/workflows/snyk_monitor.yaml

Adds workflow for snyk monitoring pushes to 6.x or main. Note the workflow only needs to exist in the default branch (`main`) but it will be triggered on pushes to `6.x`.
Also use the newish `GITHUB_REF_NAME` environment variable to determine the current branch which we use as the `target-reference` in snyk, so dependencies are grouped by the branch.

(PA-4317) Snyk monitor pushes to 6.x and main

---

.github/workflows/snyk_monitor.yaml
Rakefile

Update travis rake commits task to exclude commits in the base branch that are not in the PR branch, see https://github.com/puppetlabs/puppet-agent/pull/2213/commits/f693074fdc3060f9ed6d663aeef1901cc35ff634 for details.
Add missing '=' after `--target-reference`

(PA-4317) Add missing '='

---

configs/components/puppet-runtime.json
configs/components/pxp-agent.json

* upstream/6.x:
(maint) Update puppet to 8f5e224a37373cd94a188619c7167735c89a01b9
(PA-4224) Update build_defaults.yaml to include macOS 12 Monterey
(PA-4223) Add macOS 12 Monterey
(maint) Update puppet-runtime to 202203150
Conflicts:
ext/build_defaults.yaml
Deleted SLES11 and Solaris 10 since those are supported in 6.x but not main
Added macOS 12 to main

(maint) Merge 6.x to main

---

ext/smoke/helpers.sh
ext/smoke/packages/steps/setup-master.sh

The Postgres 9.6 packages were removed from the repoes we are using.
Since on main, the puppetdb states postgres 11 is a requirement, lets just
bump to that.
This allows the `run-smoke-test.sh` script to pass now.

(maint) Update smoke testing of platform components to postgres 11

---

configs/platforms/osx-12-x86_64.rb
ext/build_defaults.yaml

We are encountering some issues with our build tools on macOS 12
and are temporarily removing support on just the 6.x branch
until we can resolve them.

(maint) Removes macOS 12 support

---

configs/components/libwhereami.rb
configs/platforms/osx-12-x86_64.rb

MacOS 12 fails to build libwhereami due to a flag not being added in that
component. We've added the flag to other components so this looks like an oversight.
Also adds back the platform definition for osx-12-x86_64.

(PA-4337) Update libwhereami special_flags for MacOS

---

configs/platforms/osx-12-x86_64.rb

Previously we were putting the puppet7's agent in a file path that had puppet6. This PR fixes that.

(maint) Fix the output_dir for the osx-12 agent

---

ext/release-lead.rake

GitHub deprecated git URLs in March 2022. This updates a git
URL in the release-lead rake task to HTTPS
This is not present in `6.x`, so this PR targets `main`

(maint) Updates git URL to HTTPS in release rake

---

ext/smoke/helpers.sh
ext/smoke/packages/steps/setup-master.sh

Mirroring what was done in ef2ba5b, PostgreSQL 9.6 packages are
no longer available from the repositories we use for smoke tests
and PuppetDB has used PostgreSQL 11 for many versions.

(maint) Update smoke tests to PostgreSQL 11

---

configs/components/cpp-hocon.rb
configs/components/cpp-pcp-client.rb
configs/components/facter.rb
configs/components/leatherman.rb
configs/components/libwhereami.rb
configs/components/pxp-agent.rb
configs/platforms/osx-12-arm64.rb

Add support for building the puppet-agent project for macOS 12
Monterey ARM64 (M1) via cross-compilation from an x86-64 host.
Blocked on https://github.com/puppetlabs/pxp-agent-vanagon/pull/49, adding the "don't merge" label til that PR is merged and I can rebase with the updated pxp-agent-vanagon component (for main) and test

(PA-4463) Add macOS 12 Monterey ARM64 (M1) support

---

configs/platforms/ubuntu-22.04-aarch64.rb
configs/platforms/ubuntu-22.04-amd64.rb

The default settings (as set in vanagon) for ubuntu-22.04 include 'make'. That
is a hard requirement that we need to make sure is installed. We didn't include that
in our platform definition here, but we do in the defaults. So lets just inherit those.

(maint) Change ubuntu-22.04 to inherit from defaults

---

ext/build_defaults.yaml

We have recently added a new CPU architecture (M1/ARM64) to macOS
builds, which have historically only used one architecture
(x86-64). This commit adds additional directory structure to
separate builds into their respective CPU architectures.

(PA-3918) Adds architecture to macOS ship paths

---

acceptance/tests/env_windows_installdir_fact.rb

The `puppet facts` command used to default to the `find` action which returned a
Puppet::Node::Facts object, so the test had to dig into its 'values'. In Puppet
7, the default action was changed to `show` which returns just the fact values[1].
Also increase the risk level due to Windows 11
[1] https://github.com/puppetlabs/puppet/commit/cac467756b3eb70fe0c2b0a07ed108714b383ff1

(maint) Update test to work with new puppet facts show behavior

---

acceptance/tests/ensure_facter_3_and_facter_4_output_matches.rb

https://github.com/voxpupuli/beaker/pull/1744, https://github.com/voxpupuli/beaker/pull/1745 must be merged first in order to test Windows 11.
Ignore the fact diff between facter 3 and 4 for os.release.full and related facts

(maint) Ignore os.release.major related fact diffs on Window 11

---

acceptance/tests/ensure_facter_3_and_facter_4_output_matches.rb

gce.project.attributes.sshKeys fact in facter 4 is not the same as it is in facter 3.
This PR adds that to the exclusion list and once we fix that we can then remove that
fact from the exclusion list in the test.

(FACT-3136) Add exclude to facter 3 and 4 output test

---

configs/components/hiera.rb

Hiera, facter and puppet rely on `ruby install.rb` to install their respective
files into the already built ruby from puppet-runtime. Normally we can just use
that ruby, but when cross-compiling we can't. When using ruby@2.5, brew install
from our homebrew tap instead of upstream, because it's been disabled upstream.
I think `build_requires` is specified in the hiera component, because it's
installed before puppet. Once we're no longer cross compiling on macOS we can
drop that requirement.

(PA-4620) Use our homebrew tap for ruby@2.5

---

acceptance/tests/validate_vendored_ruby.rb

Starting with version 1.5.0 of the sqlite3 gem, it bundles in libsqlite3, which breaks our tests. This commit adds a flag (`--enable-system-libraries`) to continue to use system libsqlite3.

(maint) Updates sqlite3 install command

---

acceptance/tests/validate_vendored_ruby.rb

After executing the sqlite3 install command, an error where the requested platform is "x64-unknown" in https://api.rubygems.org/quick/Marshal.4.8/sqlite3-1.5.0-x64-unknown.gemspec.rz. Updating ruby gems before installing sqlite3 resolves this error.
Since this error only occurs in the puppet-agent#6.x suite pipeline, this change will only be going into 6.x and **SHOULD NOT** be merged up to main.

(maint) Add ruby gem update before sqlite3 install

---

ext/build_defaults.yaml

As the first step in removing Debian 9 support from puppet-agent, this commit removes Debian 9 from ext/build_defaults.yaml to stop shipping built Debian 9 agents to our internal nightly repositories.

(PA-4576) Removes Debian 9 from build_defaults

---

acceptance/tests/augeas_validation.rb

We had an escaped bug that broke Augeas for a certian OS type. This test will catch that in the future.

(PA-4686) Add acceptance test to validate Augeas package and resource type

---

configs/components/cpp-hocon.rb
configs/components/cpp-pcp-client.rb
configs/components/facter.rb
configs/components/leatherman.rb
configs/components/libwhereami.rb
configs/components/puppet.rb
configs/components/pxp-agent.rb
configs/components/runtime.rb
configs/platforms/debian-9-amd64.rb
configs/platforms/debian-9-i386.rb
configs/projects/puppet-agent.rb

Debian 9 ("stretch") hit end the end of its LTS support in June
2022. This commit removes Debian 9 from all Vanagon platforms, components, and projects.

(PA-4576) Removes Debian 9 from Vanagon config

---

README.md

This commit removes the Mac installer section from the README, which has not been offered or maintained for a while, and updates the MAINTAINERS convention (which is no longer used) to CODEOWNERS.

(maint) Updates README

---

ext/build_defaults.yaml

Ubuntu 14.04 (Trusty Tahr) reached end of mainstream support in
2019. This commit stops us from shipping Ubuntu 14.04 nightly builds internally.

(PA-4585) Stop shipping Ubuntu 14.04

---

configs/components/module-puppetlabs-augeas_core.json
configs/components/module-puppetlabs-cron_core.json
configs/components/module-puppetlabs-host_core.json
configs/components/module-puppetlabs-mount_core.json
configs/components/module-puppetlabs-scheduled_task.json
configs/components/module-puppetlabs-selinux_core.json
configs/components/module-puppetlabs-sshkeys_core.json
configs/components/module-puppetlabs-yumrepo_core.json
configs/components/module-puppetlabs-zfs_core.json
configs/components/module-puppetlabs-zone_core.json
configs/components/puppet-resource_api.json

Avoid making unauthenticating requests for manually promoted components. The other components, like puppet, facter, etc need to be handled in the promotion scripts first.

(maint) Use ssh for manually promoted components

---

configs/projects/puppet-agent.rb
ext/build_defaults.yaml

This PR adds Solaris 10 (x86_64) to build_defaults as a pe platform. Additionally, it disables the Style/RedundantStringEscape RuboCop in puppet-agent.rb that is causing the RuboCop PR checks to fail.

(PA-4736) Add Solaris 10 (x86_64) to build_defaults

---

configs/platforms/solaris-10-i386.rb

This commit adds Solaris i386 platform, copied over from the 6.x branch.

(PA-4734) Add Solaris 10 i386

---

configs/components/cpp-hocon.json
configs/components/cpp-pcp-client.json
configs/components/facter.json
configs/components/hiera.json
configs/components/leatherman.json
configs/components/libwhereami.json
configs/components/nssm.json
configs/components/puppet.json
configs/components/pxp-agent.json
configs/platforms/solaris-10-i386.rb
configs/platforms/solaris-10-sparc.rb
configs/projects/puppet-agent.rb

Cloning components via https in CI is not authenticated, so it's subject to github rate limiting. To avoid that, always use the SSH protocol.

(maint) Use SSH protocol when cloning

---

configs/components/pl-ruby-patch.rb
configs/platforms/solaris-10-sparc.rb

Also fix the solaris-10-x86_64 output dir, was pointing at puppet6. Added back in some logic to the pl-ruby-patch for the older version of ruby that is on solaris-10.

(PA-4749) Add solaris-10-sparc

---

.github/workflows/checks.yaml
.github/workflows/docker.yml
.github/workflows/snyk_monitor.yaml

Puppet 6.x will be end of life on February 28, 2023 and Puppet 7.x will become the long term support (LTS) branch. In preparation for this, a new Puppet-Agent 7.x branch will be created and Puppet-Agent's GitHub Actions & protection rules must be updated. This PR updates Puppet-Agent's GitHub Actions to account for 7.x being the new LTS branch.

(PA-4700) Update github actions branch for 7.x branch

---

.github/workflows/checks.yaml
.github/workflows/docker.yml
.github/workflows/snyk_monitor.yaml

The promotion from 7.x overwrote our changes. Revert back to main. This change will ensure the file conflicts in any future merge.

(maint) Update github action branches for main

---

acceptance/tests/validate_vendored_ruby.rb

Rubygems drops compatibility with Ruby 2.5 starting with version 3.4.0. This commit forces the test validating vendored Ruby to use the last version of Rubygems to support Ruby 2.5, Rubygems 3.3.26.

(maint) Limits Rubygems update for compatibility

---

configs/platforms/windowsfips-2012r2-x64.rb

The wix314-binaries.zip release is no longer available upstream, so I packaged the most recent wix314-binaries.zip I could find (from openvpn) and pushed that to artifactory with the build number 6526.
Here's a diff of what changed between `3.14.0.3205` and `3.14.0.6526`: 
https://github.com/wixtoolset/wix3/compare/20b3ded92859cf401a60d93f39a2e68cacb4867d..6b461364c40e6d1c487043cd0eae7c1a3d15968c

(maint) Bump wix 3.14.0.6526

---

configs/projects/puppet-agent.rb

The merge up from 7.x brought in 9a69f5809667be734f3f48e5f5e076989346de97 causing us to ship agent-runtime-7.x in puppet-agent#main. Pin back to agent-runtime-main.

(maint) Use agent-runtime-main (again)

---

configs/components/facter.rb
configs/components/pl-ruby-patch.rb
configs/components/puppet-runtime.rb
configs/projects/puppet-agent.rb

When patching the host ruby on cross compiled platforms the regex
incorrectly matched either 2.0 or 3.2.0. This was fixed in
puppet-runtime already, see commits:
puppetlabs/puppet-runtime@0ee61dced158aefd917352f0fd542b4e7c5b70d6
puppetlabs/puppet-runtime@90567fb1fc5d8376222edf813cb1ffeb146df640
---
The hiera component was deleted in commit 7c931cda2, but the hiera component had
a side effect of installing ruby@x.y when cross compiling macOS. So later
attempts to patch it via `pl-ruby-patch` failed. This moves the build
requirement to the `puppet-runtime` component, similar to how we handle
cross-compiled Linux and Solaris.
---
For cross-compiled builds for Linux, Solaris and macOS, we rely on pl-ruby,
OpenCSW ruby20 and homebrew ruby@x.y. And this commit makes it more explicit how
those …

(PA-4646) Restore homebrew dependency on ruby@x.y when cross-compiling macOS

---

configs/components/facter.rb
configs/components/hiera.rb
configs/components/pl-ruby-patch.rb
configs/components/puppet-runtime.rb
configs/projects/puppet-agent.rb

Backports https://github.com/puppetlabs/puppet-agent/pull/2328 to 7.x
Apply ruby regex fix from puppet-runtime
Move ruby@x.y build requirement from hiera to puppet-runtime
Building against all current 7.x build targets in https://jenkins-platform.delivery.puppetlabs.net/view/vanagon-generic-builder/job/platform_vanagon-generic-builder_vanagon-packaging_generic-builder/1926/
and https://jenkins-platform.delivery.puppetlabs.net/view/vanagon-generic-builder/job/platform_vanagon-generic-builder_vanagon-packaging_generic-builder/1927/

(PA-4646) Backport pl-ruby-patch fixes

---

configs/platforms/osx-11-arm64.rb
configs/platforms/osx-12-arm64.rb

See VANAGON-214
Updates osx-\*-\*.rb platform defintions to inherit from vanagon, except for [osx-10.15-x86_64, which already does](https://github.com/puppetlabs/puppet-agent/blob/6.x/configs/platforms/osx-10.15-x86_64.rb).

(maint) Inherit macOS platform defaults from vanagon

---

configs/platforms/osx-10.15-x86_64.rb
configs/platforms/osx-11-arm64.rb
configs/platforms/osx-11-x86_64.rb
configs/platforms/osx-12-arm64.rb

* Inherit from vanagon
* preserve puppet7 collection in `output_dir` (for now)
* preserve brew install cmake pkg-config yaml-cpp on macOS 12 ARM
* exclude facter-ng component and other component bumps

(maint) Merge 6.x to 7.x

---

configs/platforms/osx-10.15-x86_64.rb
configs/platforms/osx-11-arm64.rb
configs/platforms/osx-11-x86_64.rb
configs/platforms/osx-12-arm64.rb

* Inherit from vanagon
* Ignore hiera.rb component (it was removed in main) and component bumps
* We removed the calls to ` plat.output_dir` in d62958d804e7208b2e536280a972113fa45303c0, so preserve that in main
* Preserve `brew install cmake pkg-config yaml-cpp` for macOS 12 ARM

(maint) Merge 7.x to main

---

configs/components/module-puppetlabs-augeas_core.json
configs/components/module-puppetlabs-cron_core.json
configs/components/module-puppetlabs-host_core.json
configs/components/module-puppetlabs-mount_core.json
configs/components/module-puppetlabs-scheduled_task.json
configs/components/module-puppetlabs-selinux_core.json
configs/components/module-puppetlabs-sshkeys_core.json
configs/components/module-puppetlabs-yumrepo_core.json
configs/components/module-puppetlabs-zfs_core.json
configs/components/module-puppetlabs-zone_core.json
configs/components/shellpath.rb

This commit updates the references for all core module Vanagon components, enabling compatibilty with Puppet 8 and other minor changes.

(MODULES-11371) Update core module references

---

configs/platforms/solaris-11-i386.rb
configs/platforms/solaris-11-sparc.rb

This commit changes the URL for the package repository/publisher for Solaris 11 platforms to Puppet's new server.

(maint) Update Solaris 11 publisher

---

.rubocop.yml
acceptance/tests/ensure_facter_values_for_custom_overrides_core_top_fact.rb
acceptance/tests/ensure_facter_values_for_external_overrides_core_top_fact.rb
acceptance/tests/ensure_facter_values_for_external_overrides_custom_overrides_core_top_fact.rb
acceptance/tests/ensure_facter_values_for_json_custom_fact.rb
acceptance/tests/ensure_facter_values_for_json_external_fact.rb

In Beaker, the assert_not_match method was removed in commit voxpupuli/beaker@6282311 in favor of MiniTest::Assertions#refute_match. This change was released in Beaker 5.0.0.
This commit updates all instances of the assert_not_match with refute_match in preparation for a future switch to Beaker 5.

(maint) Update assert_not_match to refute_match

---

ext/smoke/packages/steps/setup-master.sh

Puppet Server and PuppetDB dropped Java 8 support for Puppet 8. This commit updates the package smoke tests to use a newer and supported version of Java.

(maint) Update package smoke tests to use supported Java

---

acceptance/tests/validate_vendored_openssl.rb
configs/components/openssl-fips.json
configs/components/openssl-fips.rb
configs/projects/puppet-agent.rb
resources/patches/openssl/openssl-fips.cnf.patch

* Adds fips.so shared library component to puppet-agent on RHEL 7 & 8 FIPS
* Runs `openssl fipsinstall` as a post-install task and enables the fips provider
* Adds beaker tests to verify openssl version and status of the fips provider
Also see the [OpenSSL 3.0.0 FIPS provider](https://github.com/puppetlabs/openssl-fips/blob/main/README.md).
Open Issues:

(PA-5398) Add fips shared library

---

configs/platforms/osx-11-x86_64.rb
configs/platforms/osx-12-arm64.rb
configs/platforms/osx-12-x86_64.rb
ext/build_defaults.yaml

The packaging rake task attempts to create tarball of all the signed repos using the `platform_repos` data in this repo: https://github.com/puppetlabs/packaging/blob/609cbceac5ba5d8dad7b4408c8e17d8e1e2de0a9/lib/packaging/repo.rb#L93
This fails since some platforms we're never going to support in Puppet 8 and some platforms aren't supported yet. So delete the former and comment out the latter.

(maint) Prune platforms

---

acceptance/Gemfile
acceptance/tests/validate_vendored_openssl.rb
configs/components/openssl-fips.rb
configs/projects/puppet-agent.rb
resources/files/windows/environment.bat
resources/windows/wix/customactions.wxs.erb
resources/windows/wix/sequences.wxs.erb

* Include the fips.dll provider in the fips build for Windows
* Execute a deferred custom action to run `openssl fipsinstall` and update `openssl.cnf` to point to the new generated `fipsmodule.cnf`
* Set more `OPENSSL_*` environment variables to ensure we're only loading configuration and shared libraries from trusted locations.
Passed adhoc CI https://jenkins-platform.delivery.puppetlabs.net/view/puppet-agent/view/ad-hoc/job/platform_puppet-agent-extra_puppet-agent-integration-suite_adhoc-ad_hoc/1114/
I made changes to the beaker tests after the adhoc pipeline passed and manually tested the beaker test using the previously built puppet-agent MSI [f46d202](https://github.com/puppetlabs/puppet-agent/pull/2347/commits/f46d20258e6c016ca2808243594c83968f5b4d0b)
```
❯ bx beaker exec …
```

(PA-5399) Install and configure the fips provider on Windows

---

configs/components/module-puppetlabs-yumrepo_core.json

This commit update the puppetlabs-yumrepo_core module from v1.2.0 to v2.0.0. This new version includes the addition of the `target` parameter.

(maint) Update yumrepo_core to v2.0.0

---

configs/components/puppet-runtime.rb
configs/components/pxp-agent.rb

This commit addresses issues identified by the RuboCop Style/RedundantRegexpArgument cop and changes two instances of String.sub to use 'C:' instead of /C:/.

(maint) Fix RedundantRegexpAgrument cop

---

ext/build_defaults.yaml

updated build defaults for macos13 intel chipset

(PA-4596) update build defaults for macos13(x86-64)

---

acceptance/tests/validate_vendored_ruby.rb
configs/components/puppet-resource_api.json
configs/components/puppet.rb
configs/platforms/aix-7.2-ppc.rb

* Since AIX 7.1 is EOL, we build on 7.2
* Disable gettext build machinery on AIX, because we [disable_i18n by default](https://github.com/puppetlabs/puppet/blob/1f413e9b044a5933a31792bc1510a7a63d69f348/lib/puppet/defaults.rb#L212) and if it's enabled, fast_gettext will default to strings in https://github.com/puppetlabs/puppet/blob/main/locales/puppet.pot
* The beaker tests for installing gems with native extensions needs to be updated to support AIX 7.2, so skip for now. Filed https://tickets.puppetlabs.com/browse/PA-5654 to fix that.
Adhoc https://jenkins-platform.delivery.puppetlabs.net/view/puppet-agent/view/ad-hoc/job/platform_puppet-agent-extra_puppet-agent-integration-suite_adhoc-ad_hoc/1126/
Please merge https://github.com/puppetlabs/ci-job-configs/pull/9005 after this.
Due to the …

(PA-5651) Add AIX 7.2 for Puppet 8

---

ext/build_defaults.yaml

Previously, we were shipping AIX rpms to the internal build server and agent
downloads, but we weren't creating the AIX repo tarball:
puppet-agent/<version>/repos/puppet-agent-aix-7.2-power.tar.gz
Nor was the AIX RPM included in the all agents tarball during
Execute pl:jenkins:pack_all_signed_repos_individually
Adding aix-7.2-power to the `platform_repos` enables both of those things.
Also some discussion in https://perforce.slack.com/archives/G049EJF2Z2A/p1689703744853649 about why we're removing `pe_platforms`

(PA-5661) Ship AIX 7.2 repo tarball and add rpm to all agent tarball

---

configs/components/puppet.rb
configs/platforms/osx-13-arm64.rb

Adhoc pipeline https://jenkins-platform.delivery.puppetlabs.net/view/puppet-agent/view/ad-hoc/job/platform_puppet-agent-extra_puppet-agent-integration-suite_adhoc-ad_hoc/1130/

(PA-4777) Add macOS 13 (ARM) platform definition to puppet-agent

---

ext/build_defaults.yaml

When we introduced https://github.com/puppetlabs/puppet-agent/commit/d62958d804e7208b2e536280a972113fa45303c0 it looks like it caused some breakage in the shipping of the  agent. This attempts to fix the path.

(maint) Fix up Solaris i386 path in built_defaults

---

acceptance/tests/validate_vendored_ruby.rb

b34411c pinned Rubygems to 3.3.26 to maintain compatibility with Ruby 2.5, which was used for Puppet 6. As Puppet 6 hit end-of-life in February 2023, we no longer need this pin.

(maint) Revert Rubygems pin

---

configs/components/puppet-resource_api.json

This commit updates the puppet-resource_api component to the latest release, 1.8.18, which includes fixes for Ruby 3.2 (see PA-5641).
This change was already completed in 7.x with 9bfac06.

(maint) Update resource_api component

---

acceptance/tests/validate_vendored_ruby.rb
configs/components/puppet-runtime.rb

This PR comprises cleanup related to operating systems no longer supported in Puppet 8 and a workaround for the now-EOL Puppet 6.

(maint) Legacy cleanup

---

configs/platforms/solaris-11-i386.rb
configs/platforms/solaris-11-sparc.rb

This commit adds the output_dir command to both Solaris 11 platform templates to override the default output directory. Without this change, an extra directory for the architecture is used, i.e. /solaris/11/puppet8/ i386/ instead of /solaris/11/puppet8

(PA-5702) Override default output dir for Solaris 11

---

ext/build_defaults.yaml

build defaults updated for macos-13 intel
NOTE : DO NOT MERGE UNTIL BUILD_TARGETS are merged

(PA-4596) add macos-13-x86_64 to build defaults

---

configs/projects/puppet-agent.rb

We natively compile puppet-runtime and pxp-agent-vanagon on Solaris 11 SPARC, because we were not able to install a new enough gcc on x86_64 to cross compile.
However, we only have 2 Solaris 11 SPARC hosts and we don't need gcc to build puppet-agent. We just need a runnable ruby to execute `gem install` and `ruby install.rb`. The latter is used when installing puppet and facter components.
So override the `host_ruby`, etc settings that are inherited from puppet-runtime to point to pl-build-tools ruby. As a result we're "cross-building" puppet-agent#main on Solaris 11 SPARC, just like we're doing in 7.x.
Note we only run facter tests on `solaris-*-SPARC` due to this combination filter https://github.com/puppetlabs/ci-job-configs/blob/11830ab1410a9dec347c052a3091e991bfd2b8dc/resources/script …

(PA-5656) Override gem commands for Solaris 11 SPARC

---

ext/build_defaults.yaml

This causes the solaris11-sparc puppet-agent package to be included in puppet-agent-all.tar.gz which is shipped to:
http://agent-downloads.delivery.puppetlabs.net/<PE VER>/puppet-agent/8.X.X.X/puppet-agent-all.tar.gz

(PA-5663) Add Solaris 11 SPARC to ext/build_defaults.yaml

---

configs/components/puppet-resource_api.json

This PR backports the resource_api bump made in https://github.com/puppetlabs/puppet-agent/pull/2383

(CAT-761) Update puppet-resource_api version

---

acceptance/tests/validate_vendored_ruby.rb

The validate_vendored_ruby.rb test is failing on AIX when trying to compile native extensions for the sqlite3 gem. The gcc version used in this test (gcc 5.2.0) does not recognize the `warnflags` used in rbconfig.rb. This is because a newer gcc (gcc 10) was used when when creating rbconfig.rb.
This commit removes the `warnflags` in rbconfig.rb on AIX.

(PA-5654) Remove warnflags from rbconfig.rb on AIX

---

ext/smoke/repos/steps/setup-masters.sh
ext/smoke/steps/setup-agent.sh

We no longer maintain release packages in the puppetN subdirectories.
Update smoke tests to toplevel location.

(maint) point release package to root of yum.p.c

---

ext/smoke/helpers.sh

The latest release of puppetlabs-puppetdb depends on a version of firewall that doesn't support puppet8.
I intentionally didn't target 7.x, because it's only an issue with puppet8 and the puppetdb/firewall modules.
There are two 2 smoke tests described in https://github.com/puppetlabs/puppet-agent/tree/main/ext/smoke#overview
`./packages/run-smoke-test.sh suave-easement.delivery.puppetlabs.net retentive-creed.delivery.puppetlabs.net  8.2.0 8.2.1 8.1.0`
`./repos/run-smoke-test.sh coy-pageantry.delivery.puppetlabs.net tart-breeze.delivery.puppetlabs.net astral-roomful.delivery.puppetlabs.net faulty-repeater.delivery.puppetlabs.net 8.2.0 8.2.1 8.1.0`

(PUP-11939) Don't manage firewall in smoke test

---

configs/platforms/el-9-aarch64.rb

puppet-agent build: https://jenkins-platform.delivery.puppetlabs.net/view/vanagon-generic-builder/job/platform_vanagon-generic-builder_vanagon-packaging_generic-builder/2341/

(PA-5002) Add Red Hat 9 (ARM64) platform definition to puppet-agent#7.x

---

acceptance/Gemfile

beaker-hostgenerator released 2.0 earlier this year, and since that release all new platforms, features, and fixes have been going into 2.x releases.
This commit updates the acceptance Gemfile to depend on beaker-hostgenerator ~> 2 instead of ~> 1.1.

(maint) Update beaker-hostgenerator version

---

ext/build_defaults.yaml

updated build_defaults to allow RHEL9 aarch64 to ship to internal nightlies

(PA-5004) Added RHEL9 ARM for nightlies ship

---

.github/workflows/checks.yaml

The Checkout GitHub Action v3 uses Node 16, which hit end-of-life on September 11, 2023.
This commit updates all instances of the Checkout Action from v3 to v4.

(PA-5802) Update Checkout GitHub Action

---

configs/platforms/debian-11-aarch64.rb

[vanagon-generic-builder_vanagon](https://jenkins-platform.delivery.puppetlabs.net/job/platform_vanagon-generic-builder_vanagon-packaging_generic-builder/BUILD_TARGET=debian-11-aarch64,SLAVE_LABEL=k8s-worker/2398/console)
[puppet-agent_7.26.0.62.g7f8069ff2-1bullseye_arm64.deb](https://builds.delivery.puppetlabs.net/puppet-agent/7f8069ff2d52fd60f9250ea84a1333e640ae7b22/artifacts/deb/bullseye/puppet7/puppet-agent_7.26.0.62.g7f8069ff2-1bullseye_arm64.deb)

Add Debian 11 (ARM) platform definition to puppet-agent#7.x

---

configs/platforms/debian-11-aarch64.rb

The build using vanagon generic builder is available at: https://builds.delivery.puppetlabs.net/puppet-agent/ccc3f45d4269c93b7fe5d6b619cf4f754620aac0/artifacts/?C=M&O=D

(PA-5743) Add debian-11 AARCH 64 platform definition file

---

configs/components/openssl-fips.rb

`#add_postinstall_action` puts scriptlets in the `%posttrans` section of an rpm spec file. This action must complete before restarting puppet, so prefer the `#add_postinstall_required_action` from vanagon to ensure it completes before restarting puppet.

(PA-5786) Use postinstall_required_action for fips

---

acceptance/tests/selinux.rb

Prior to this PR, the SELinux acceptance test was set to low priority, causing the test to be skipped.
However, we've seen multiple regressions on SELinux behavior in puppet-agent, so we should always run this test to catch them early.
This PR updates the SELinux acceptance test to high priority, ensuring that it's always run.

(PA-5632) Set SELinux test to high

---

.github/workflows/jira.yml

This commit adds a friendly name to the GitHub Actions workflow that exports GitHub issues to Jira.

(PA-5932) Add name to Jira workflow

---

configs/platforms/amazon-2023-aarch64.rb
configs/platforms/amazon-2023-x86_64.rb

Added platform file for amazon 2023 aarch64 & amd64 for 7.x branch

[PA-5570] Added platform file for amazon 2023 aarch64 & amd64 for 7.x

---

ext/build_defaults.yaml

Updated Build Defaults YAML to enable Amazon Linux for Internal Nighties

PA-5572 : Updated build defaults to enable amazon linux for internal nightlies

---

ext/build_defaults.yaml

Updated build defaults YAML to enable Amazon Linux 2023 for Internal Nightlies for 7.x branch

PA-5572: Update build defaults yaml to enable amazon linux 2023 for internal nightlies for 7.x

---

configs/platforms/osx-14-x86_64.rb

Build: [2524](https://jenkins-platform.delivery.puppetlabs.net/job/platform_vanagon-generic-builder_vanagon-packaging_generic-builder/BUILD_TARGET=osx-14-x86_64,SLAVE_LABEL=k8s-worker/2524/console)
artifact: [c8cd808b4cdbedf9346a69002607c9482845657a](http://builds.delivery.puppetlabs.net/puppet-agent/c8cd808b4cdbedf9346a69002607c9482845657a/artifacts/?C=M&O=D)

(PA-5881) Add macOS 14 (Intel) platform definition to puppet-agent-main

---

configs/platforms/osx-14-x86_64.rb

[build](https://jenkins-platform.delivery.puppetlabs.net/job/platform_vanagon-generic-builder_vanagon-packaging_generic-builder/BUILD_TARGET=osx-14-x86_64,SLAVE_LABEL=k8s-worker/2525/console)
[Artifact](http://builds.delivery.puppetlabs.net/puppet-agent/903ceea7ef242cb8508b56562636d08d390c27a5/artifacts/?C=M&O=D)

(PA-5882) Add macOS 14 (Intel) platform definition to puppet-agent-7.x

---

configs/platforms/osx-14-arm64.rb

Vanagon generic build: https://jenkins-platform.delivery.puppetlabs.net/view/vanagon-generic-builder/job/platform_vanagon-generic-builder_vanagon-packaging-ship-repos_generic-builder/1348/
Artifacts: https://builds.delivery.puppetlabs.net/puppet-agent/10a0673747bca7fbdc20f10915a23e15271d9597/artifacts/apple/14/puppet8/arm64/

(PA-5907) Add macOS 14 (ARM) platform definition to puppet-agent-main

---

configs/components/module-puppetlabs-scheduled_task.json

This commit bumps the scheduled_task module from 3.1.1 to 3.2.0. The primary change is managing the description field for a scheduled task.

(maint) Bump scheduled_task module

---

.github/workflows/checks.yaml
acceptance/tests/validate_vendored_ruby.rb

When Rubygems attempts to run `gem update --system` under Ruby 2.7, it errors when pulling in rubygems-update >= 3.5.0, which drops support for Ruby < 3.0.
This commit pins rubygems-update to 3.4.22, the last version that supports Ruby 2.7.

Pin rubygems-update for Ruby 2.7

---

.github/workflows/checks.yaml

Prior to this commit, the checks GitHub Action was running on Ruby 2.7. This version of Ruby went end-of-life in early 2023 and libraries (such as rubygems-update) have started to drop support, causing errors with the action.
This commits that Ruby version to 3.2 to match what we're using in puppet-agent main/8.x.

Update Ruby version in checks

---

acceptance/tests/validate_vendored_ruby.rb

The validate_vendored_ruby test started failing on AIX 7.2 when loading the
gemspecs from artifactory:
GET https://rubygems.org/specs.4.8.gz
304 Not Modified
GET https://artifactory.delivery.puppetlabs.net/artifactory/api/gems/rubygems/specs.4.8.gz
304 Not Modified
[FATAL] failed to allocate memory
It appears the new behavior is triggered when using the new safe marshall code
introduced in rubygems-update[1]:
...
10813880: 11338039: kopen("/root/.local/share/gem/specs/rubygems.org%443/specs.4.8", 0440000002) = 9
10813880: 11338039: kopen("/opt/puppetlabs/puppet/lib/ruby/site_ruby/3.2.0/rubygems/safe_marshal.rb", 0440000004) = 9
...
10813880: 11338039: kopen("/root/.local/share/gem/specs/artifactory.delivery.puppetlabs.net%443/artifactory/api/gems/rubygems/specs.4.8", 0440000004) = 10 …

Use older rubygems-update on AIX 7.2

---

acceptance/tests/validate_vendored_ruby.rb

The test started failing on RHEL8 ARM with:
$ env GEM_HOME=/opt/puppetlabs/puppet/lib/ruby/vendor_gems env PATH="/opt/puppetlabs/puppet/bin:${PATH}" gem install sqlite3 -v 1.7.0 -- --enable-system-libraries
ERROR:  Error installing sqlite3:
The last version of sqlite3 (= 1.7.0) to support your Ruby & RubyGems was 1.7.0. Try installing it with `gem install sqlite3 -v 1.7.0` and then running the current command again
sqlite3 requires Ruby version >= 3.0, < 3.4.dev. The current ruby version is 2.7.8.225.
The sqlite3 gem dropped "native gem support for 2.7" in 1.7.0. So pin to the version just prior to that.

Pin sqlite3 rubygem to 1.6.9

---

acceptance/tests/validate_vendored_ruby.rb

We have started to see test failures on AlmaLinux due to outdated keys when validating packages. This commit updates tests to upgrade the AlmaLinux release package to pull in new keys to allow other packages to be installed.

Upgrade AlmaLinux release package

---

acceptance/tests/ensure_puppet-agent_paths.rb
acceptance/tests/ensure_puppet_facts_can_use_facter.rb
acceptance/tests/test_manpage_clobber.rb
acceptance/tests/windows_eventlog.rb

Previously in Beaker, you could use standalone stdout and stderr methods to access output from remote machines.
These methods were deprecated in 2013 with https://github.com/voxpupuli/beaker/commit/28b2510 and dropped entirely in https://github.com/voxpupuli/beaker/commit/73a31c7.
This commit removes these updates from puppet-agent tests in favor of calling stdout and stderr methods on Result objects.

Update stdout and stderr methods

---

acceptance/Gemfile

I manually ran tests on RHEL8:
```
$ bundle exec rake ci:test:setup SHA=8.4.0 HOSTS=redhat7-64a
$ bundle exec beaker exec tests
...
Test Suite: tests @ 2024-02-14 07:44:30 -0800
- Host Configuration Summary -
- Test Case Summary for suite 'tests' -
Total Suite Time: 260.68 seconds
Average Test Time: 7.90 seconds
Attempted: 33
Passed: 29
Failed: 0
Errored: 0
Skipped: 4
Pending: 0
Total: 33
```
This will need to be backported to 7.x

(PA-6087) Use Beaker 5 and friends

---

configs/platforms/fedora-36-x86_64.rb

Installing binutils on F36 from the rawhide repos started failing:
Downloading Packages:
(1/8): jansson-2.13.1-9.fc40.x86_64.rpm          97 kB/s |  44 kB     00:00
(2/8): binutils-gold-2.41-32.fc40.x86_64.rpm    1.1 MB/s | 782 kB     00:00
(3/8): glibc-common-2.39-2.fc40.x86_64.rpm      3.5 MB/s | 383 kB     00:00
(4/8): binutils-2.41-32.fc40.x86_64.rpm         6.5 MB/s | 6.2 MB     00:00
(5/8): glibc-2.39-2.fc40.x86_64.rpm             4.2 MB/s | 2.2 MB     00:00
(6/8): glibc-gconv-extra-2.39-2.fc40.x86_64.rpm 7.5 MB/s | 1.7 MB     00:00
(7/8): glibc-langpack-en-2.39-2.fc40.x86_64.rpm 4.3 MB/s | 694 kB     00:00
(8/8): libstdc++-14.0.1-0.6.fc40.x86_64.rpm     3.9 MB/s | 872 kB     00:00
--------------------------------------------------------------------------------
Total …

Use F36 repos instead of rawhide

---

configs/components/pxp-agent.rb
configs/platforms/sles-11-x86_64.rb

- Add SLES-11 (Intel) definition file
- Since tar command on the SLES-11 VM doesn't understand --skip-old-files option due to it being an older version, do not use that option while installing puppet-runtime (pxp-agent.rb)

(PA-6004) Add SLES-11 (Intel) support

---

configs/components/module-puppetlabs-augeas_core.json
configs/components/module-puppetlabs-cron_core.json
configs/components/module-puppetlabs-host_core.json
configs/components/module-puppetlabs-mount_core.json
configs/components/module-puppetlabs-selinux_core.json
configs/components/module-puppetlabs-sshkeys_core.json
configs/components/module-puppetlabs-yumrepo_core.json
configs/components/module-puppetlabs-zfs_core.json
configs/components/module-puppetlabs-zone_core.json

This commit updates all core modules. The notable changes from these new modules are mainly:
- Removal of concurrent-ruby as a dependency to avoid issues with Puppet
- Support for Amazon Linux

Update core modules

---

acceptance/util/puppet_facts_output.rb

The `output` method is no longer available to the test case. Instead access the output from the result that's yielded to the method.
This job is running against my fork: https://jenkins-platform.delivery.puppetlabs.net/view/puppet-agent/view/puppet-facts/job/platform_puppetfacts_puppet-agent-puppetfacts-suite_adhoc/55/ Ignore the AIX failures, I specified the wrong TEST_TARGETS for the 7.x pipeline

Update the acceptance:facts rake task for beaker 5

---

resources/windows/wix/license/LICENSE.rtf

This license is displayed when installing the puppet-agent MSI.
win32-* gems were removed in puppet 7.0
Added license info for other gems. Some gems like fast_gettext are dual licensed (MIT & Ruby), so I just picked one.
This is a follow up to https://github.com/puppetlabs/puppet-runtime/pull/817

Update Windows license

---

configs/platforms/amazon-7-aarch64.rb

Build [amazon-7-aarch64](https://jenkins-platform.delivery.puppetlabs.net/job/platform_vanagon-generic-builder_vanagon-packaging_generic-builder/BUILD_TARGET=amazon-7-aarch64,SLAVE_LABEL=k8s-worker/2922/consoleFull)
[artifacts](https://builds.delivery.puppetlabs.net/puppet-agent/975c70c45046d1d2798aee5e01e01a4a2b46fc31/artifacts/)

(PA-6264) Add Amazon Linux2 platform definition to puppet-agent-main

---

configs/platforms/amazon-7-aarch64.rb

Vanagon Generic Build : https://jenkins-platform.delivery.puppetlabs.net/job/platform_vanagon-generic-builder_vanagon-packaging_generic-builder/BUILD_TARGET=amazon-7-aarch64,SLAVE_LABEL=k8s-worker/2959/

(PA-6265) Added AL2 in platform definition for 7.x

---

acceptance/tests/validate_vendored_openssl.rb

- Opensslfips was bumped to 3.0.9 from 3.0.0 in https://github.com/puppetlabs/openssl-fips/pull/8
- Update the expected opensslfips version to be 3.0.9 for all fips platforms in acceptance tests.

(PA-6480) Update opensslfips version check test to expect 3.0.9

---

configs/platforms/amazon-2-aarch64.rb
configs/platforms/amazon-7-aarch64.rb
ext/build_defaults.yaml

Amazon 7 is an implementation detail, the actual OS is named Amazon 2
Blocked on https://github.com/puppetlabs/pxp-agent-vanagon/pull/121
This will need to be backported to 7.x

Rename Amazon 7 to 2

---

configs/components/puppet-runtime.rb

When building puppet-agent-7.x on macOS 11 & 12, we now install ruby@2.7 from our homebrew-puppet tap.
vanagon generic : https://jenkins-platform.delivery.puppetlabs.net/view/vanagon-generic-builder/job/platform_vanagon-generic-builder_vanagon-packaging_generic-builder/3020/

(PA-6676) Install ruby@2.7 from internal source

---

.github/workflows/checks.yaml

A recent update to the Ubuntu GitHub Action runner added Ruby 3.2 to the image. This causes conflicts when we try to install Ruby 3.2 with the setup-ruby action.
This commit bumps the Ruby version used in the checks action from 3.2 to 3.3.
See also puppetlabs/puppet-runtime@f25d32c

Bump Ruby in checks action to 3.3

---

configs/components/module-puppetlabs-zfs_core.json

We'll want to backport this to 7.x as well.

Bump zfs_core to 1.6.1

---

configs/platforms/windows-2012r2-x64.rb
configs/platforms/windows-2012r2-x86.rb
configs/platforms/windowsfips-2012r2-x64.rb

We use '--ignore-dependencies' flag to install wixtoolset since it depends on DotNet3.5 which breaks when installing: wixtoolset/issues#5523. Seems we don't need it for our use case, we can leave it out.

(PA-6543) Bump wixtoolset to 3.14.1 in puppet-agent main

---

configs/platforms/windowsfips-2012r2-x64.rb

- The '--fail' options will return error code 1 if artifactory resource is not found. If not given, then for unsuccessful response from artifactory, the response is saved in the output file as html. Here, curl returns exit code 0 which is not interpreted as an error, so the build proceeds. The build then tries to unzip this html which throws an error that is rather difficult to debug.
- The '--retry' flag will guard against transient failures if any.

(PA-6543) Add more curl options when downloading WIX zip

---

configs/platforms/windows-2012r2-x64.rb
configs/platforms/windows-2012r2-x86.rb
configs/platforms/windowsfips-2012r2-x64.rb

We use '--ignore-dependencies' flag to install wixtoolset since it depends on DotNet3.5 which breaks when installing: https://github.com/wixtoolset/issues/issues/5523. Seems we don't need it for our use case, we can leave it out.

(PA-6543) Bump wix to 3.14.1 for puppet-agent 7.x

---

configs/platforms/windowsfips-2016-x64.rb

- Unlike windowsfips-2012r2 VMs, 7z is not available at location "C:\Program Files" in windowsfips-2016 VMs, so install 7z from chocolatey.
- Latest choco version does not work on windowsfips-2016 but version 1.4.0 does. So, just like we're using 1.4.0 in puppet-runtime and pxp-agent-vanagon, we use it here as well.

(PA-6329) Add Windows 2016 FIPS platform definition to puppet-agent main

---

ext/build_defaults.yaml

Homebrew recently dropped support for OpenSSL 1.1 because it's end-of-life. However, our cross-compiled macOS platforms (11 and 12 on ARM) still depend on OpenSSL.
While we work on hosting our own OpenSSL 1.1 formula (see PA-7103), this commit disables building on those platforms for now.

Temporarily disable cross-compiled Mac platforms

---

ext/build_defaults.yaml

Due to an issue with macOS 12 ARM and XCode (see ITHELP-102634), we are temporarily disabling building and shipping that platform.

Temporarily disable macOS 12 ARM
