configs/components/openssl.rb
configs/platforms/solaris-10-i386.rb
configs/platforms/solaris-10-sparc.rb

(RE-6121) Update to latest openssl

---

Gemfile
configs/components/puppet.rb
resources/files/README
resources/files/ftdetect/ftdetect_puppet.vim
resources/files/ftplugin/ftplugin_puppet.vim
resources/files/indent/indent_puppet.vim
resources/files/syntax/syntax_puppet.vim

This PR will add vim syntax files in the P-A packaging under puppet/share/vim/puppet-vimfiles

Pa 121/add vim syntax files

---

configs/components/curl.rb
configs/components/openssl.rb
configs/components/puppet-ca-bundle.rb
configs/components/ruby-stomp.rb
configs/components/ruby.rb
configs/components/rubygem-deep-merge.rb
configs/components/rubygem-ffi.rb
configs/components/rubygem-hocon.rb
configs/components/rubygem-minitar.rb
configs/components/rubygem-net-ssh.rb
configs/components/rubygem-win32-dir.rb
configs/components/rubygem-win32-eventlog.rb
configs/components/rubygem-win32-process.rb
configs/components/rubygem-win32-security.rb
configs/components/rubygem-win32-service.rb
configs/components/runtime.rb
configs/platforms/windows-2012r2-x64.rb
configs/platforms/windows-2012r2-x86.rb
configs/projects/puppet-agent.rb

This pull request updates the current windows work in the windows feature branch to reduce the windows specific branching we have, and also to conform with recent updates to vanagon.

(maint) Update paths to reduce windows specific variation

---

configs/platforms/el-4-i386.rb
configs/platforms/el-4-x86_64.rb
configs/platforms/el-5-i386.rb
configs/platforms/el-5-x86_64.rb
configs/platforms/el-6-i386.rb
configs/platforms/el-6-x86_64.rb
configs/platforms/el-7-x86_64.rb

This reverts commit 99db82c7f0250b069be635ecb8a21669c28cab9f.

Revert "(maint) Bring out platform configs into the brave new world"

---

configs/components/openssl.rb

This is to address CVE-2016-0701

(RE-6446) Update to OpenSSL 1.0.2f

---

bin/windows-env.ps1
configs/components/windows_ruby.json

This is to address CVE-2016-0701

(RE-6447) Use updated ruby for windows

---

configs/components/facter.rb

When running facter on windows, we need a few batch scripts. This commit
adds them

(FACT-1321) Install windows batch scripts for facter

---

configs/components/facter.rb
configs/components/hiera.rb
configs/components/marionette-collective.rb
configs/components/puppet.rb
configs/components/pxp-agent.rb

We need to keep windows packaging consistent. This includes a few places
where we need to special case where things are installed

(maint) Ensure windows packaging is consistent

---

configs/components/facter.rb

This reverts commit 92b85f093167fd311712b9c0212d71637af8fe96.

Revert "(FACT-1321) Install windows batch scripts for facter"

---

configs/projects/puppet-agent.rb

This commit adds in a base set of wix variables for processing templates

(maint) Add initial set of wix vars

---

configs/components/leatherman.json

(PA-237) Update to Leatherman 0.4.1

---

resources/windows/wix/registryEntries.wxs.erb

These will over-ride the generic set of registry entries in Vanagon

(RE-6743) Add Puppet-Agent registry entries

---

configs/components/cpp-pcp-client.json
configs/components/leatherman.json

Merge the release branch back to stable

140 release branch merge

---

configs/projects/puppet-agent.rb

The previous version of this change had incorrect LDFLAGS defined for OS X
and not all components safely strip bad values. This has been corected, and
a comment about how LDFLAGS should be set for OS X has been added.
The cascading if/else for setting CFLAGS could lead to more than one situation
no LDFLAGS are set or the standard LDFLAGS are duplicated in each conditional.
We can improve this by setting broad, generally correct defaults and then only
adding to them or changing them as needed. This also eases the pressures that
likely led to a cascading if/else statement.

(PA-181) Simplify/correct CFLAGS and LDFLAGS logic again

---

resources/windows/wix/componentgroup.wxs.erb
resources/windows/wix/shortcuts.wxs.erb

Populate [INSTALLDIR]bin wih shortcuts to .bat files in [INSTALLDIR]puppet\bin

(RE-6758) Setup bin Shortcuts directory

---

resources/windows/wix/appdatafiles.wxs
resources/windows/wix/customactions.wxs
resources/windows/wix/sequences.wxs.erb

This is direct cut over of parts of https://github.com/puppetlabs/puppet_for_the_win/blob/master/wix/puppet.wxs as specific static files pertaining to the special case for config files in CommonAppDataFolder

Re 6470/enable special case of config files in the app data folder

---

configs/components/leatherman.json

Brings in LTH-94 fix for runtime errors on AIX.

(maint) Bump Leatherman to 0.6.2

---

configs/components/facter.rb

We need to build a facter jar for use with puppetserver. This requires
that we install java in order to create that jar.

(maint) Add JDK Support for Xenial and f23

---

bin/build-cpp-pcp-client.ps1
bin/build-facter.ps1
bin/build-leatherman.ps1
bin/build-pxp-agent.ps1
bin/build-windows.rb
configs/components/leatherman.json
configs/components/leatherman.rb

To support PCP-372, enable building shared libraries for Leatherman on
Windows.

(PA-305) Build shared Leatherman libraries on Windows

---

configs/components/leatherman.json

One of Leatherman's unit tests fails inconsistently. Bump Leatherman SHA
to pickup a change that disables that test.

(maint) Bump Leatherman to avoid test failure

---

LICENSE
README.md
configs/projects/puppet-agent.rb

Update references from puppetlabs to puppet

(PA-285) Branding name change

---

configs/components/cpp-pcp-client.rb
configs/components/curl.rb
configs/components/facter.rb
configs/components/leatherman.rb
configs/components/libxml2.rb
configs/components/libxslt.rb
configs/components/openssl.rb
configs/components/puppet-ca-bundle.rb
configs/components/pxp-agent.rb
configs/components/ruby-augeas.rb
configs/components/ruby-shadow.rb
configs/components/ruby.rb
configs/components/runtime.rb
configs/components/virt-what.rb
configs/platforms/sles-12-s390x.rb
configs/projects/puppet-agent.rb

This is a zLinux platform for SLES 12 running on IBM's s390x arch.

(PA-312) Add sles-12-s390x as a platform

---

configs/components/leatherman.json

Update the leatherman version to 0.6.3 to reflect the new release

(maint) Update to leatherman 0.6.3

---

configs/components/leatherman.json

This is needed for puppetlabs/facter#1333

(maint) Update to leatherman 0.7.1

---

configs/components/cpp-pcp-client.rb
configs/components/facter.rb
configs/components/leatherman.rb
configs/components/pxp-agent.rb

Reverts puppetlabs/puppet-agent#678

Revert "(maint) Enable tests, use check on all CMake projects"

---

configs/components/leatherman.json

(maint) Update Leatherman to 0.7.2

---

configs/components/openssl.rb
configs/components/ruby-selinux.rb
configs/platforms/el-6-s390x.rb

This platform is for RHEL running on IBM z-series

(PA-315) Add el-6-s390x platform

---

configs/components/cpp-pcp-client.json
configs/components/facter.json
configs/components/hiera.json
configs/components/leatherman.json
configs/components/marionette-collective.json
configs/components/pxp-agent.json

for everything except for puppet, pending a fix/tests

(maint) Set component tags for 1.5.2 release

---

configs/components/cpp-pcp-client.rb
configs/components/facter.rb
configs/components/leatherman.rb
configs/components/puppet-ca-bundle.rb
configs/components/pxp-agent.rb

Merge stable to master to pick up some fixes

Merge stable to master

---

configs/components/facter.rb

Reverts puppetlabs/puppet-agent#708
This test was not catching most cases where problems exist. More work required.

Revert "(PA-392) Ensure linking against PL libs"

---

configs/components/libxslt.rb
configs/platforms/el-7-s390x.rb

This is for RHEL 7 running on IBM z-series.

(PA-318) Add el-7-s390x platform

---

configs/components/facter.json

This reverts commit 6cc061ef43bdd201b8f7d42414b1a15e786563b2.
See FACT-1442

Revert "bumping facter to fbc52a015e94028986ed562edd12da7315c89d28"

---

configs/components/leatherman.json

Introduces the fix for LTH-99.

(maint) Update Leatherman to 0.7.4

---

configs/components/marionette-collective.rb
configs/components/ruby.rb
resources/windows/wix/service.pxp-agent.wxs.erb

~~This PR requires https://github.com/puppetlabs/pxp-agent/pull/448~~

(RE-7587) (RE-7593) Windows fixes to mco and pxp-agent

---

configs/components/leatherman.json

(maint) Update Leatherman to 0.8.1

---

configs/components/puppet.json

This commit sets the puppet sha to HEAD of puppet/master in anticipation of
puppet agent 1.6.0

Update puppet SHA for updated 1.6.0 release

---

configs/components/leatherman.json

(maint) Bump Leatherman to version 0.9.0

---

configs/platforms/osx-10.12-x86_64.rb

Many thanks to Heath Seals for getting this working. The agent builds with this and can apply a few test manifests.

(PA-463) Add OS X 10.12 (Sierra) platform

---

configs/components/puppet.json

Update puppet.json file w/4.7.0 tag in anticipation of upcoming release.

(PA-527) Update puppet ref to 4.7.0

---

configs/components/leatherman.json

Brings in minor changes needed for extending logging in PCP-556.

(maint) Bump Leatherman to 0.9.1 release

---

configs/components/curl.rb
configs/components/openssl.rb

This bumps curl to 7.50.3 and openssl to 1.0.2j

(PA-573 and PA-575) Bump curl and openssl

---

configs/components/leatherman.json

This is required before [FACT-1356](https://tickets.puppetlabs.com/browse/FACT-1356) can be merged.

(maint) Bump leatherman to 0.9.2

---

resources/windows/wix/condition.wxs.erb
resources/windows/wix/localization/puppet_en-us.wxl
resources/windows/wix/ui/Puppet32bitWarningDlg.wxs
resources/windows/wix/ui/WixUI_PuppetInstallDir.wxs.erb

(maint) Merge LTS-1.7 to stable

---

resources/windows/wix/condition.wxs.erb
resources/windows/wix/localization/puppet_en-us.wxl
resources/windows/wix/ui/Puppet32bitWarningDlg.wxs
resources/windows/wix/ui/WixUI_PuppetInstallDir.wxs.erb

(maint) Merge Stable to Master

---

configs/projects/puppet-agent.rb

(PA-678) Fixup the comment and pe-r10k version to improve clarity.

---

configs/components/leatherman.json

Bump leatherman in master to the 0.10.0 release which brings in the following new features & changes:
- Solaris implementation of the `create_detached_process` execution option (execution of child processes in separate contracts) (LTH-120)
- Renamed `create_new_process_group` execution option to `create_detached_process` to make the concept more broadly applicable (LTH-120)

(PA-736) Bump leatherman in master to 0.10.0

---

configs/components/leatherman.json

Reverts puppetlabs/puppet-agent#916
This appears to break building with Facter. /cc @mruzicka

Revert "(PA-736) Bump leatherman in master to 0.10.0"

---

configs/components/leatherman.json

Bump leatherman in master to the 0.10.1 release which brings in the following new features, changes & fixes:
- Fix to only apply large file support flags to Leatherman.execution (LTH-120)
- Solaris implementation of the create_detached_process execution option (execution of child processes in separate contracts) (LTH-120)
- Renamed create_new_process_group execution option to create_detached_process to make the concept more broadly applicable (LTH-120)

(PA-736) Bump leatherman in master to 0.10.1

---

.gitignore
.rubocop.yml
README.md
acceptance/Gemfile
acceptance/README.md
acceptance/Rakefile
acceptance/config/aio/options.rb
acceptance/config/nodes/aix-53-power.yaml
acceptance/config/nodes/aix-61-power.yaml
acceptance/config/nodes/aix-71-power.yaml
acceptance/config/nodes/huaweios-6-powerpc.yaml
acceptance/config/nodes/solaris-10-sparc.yaml
acceptance/config/nodes/solaris-11-sparc.yaml
acceptance/lib/helper.rb
acceptance/lib/puppet/acceptance/common_utils.rb
acceptance/lib/puppet/acceptance/install_utils.rb
acceptance/lib/puppet/acceptance/temp_file_utils.rb
acceptance/setup/aio/pre-suite/010_Install.rb
acceptance/setup/aio/pre-suite/015_PackageHostsPresets.rb
acceptance/setup/aio/pre-suite/020_InstallCumulusModules.rb
acceptance/setup/aio/pre-suite/021_InstallAristaModule.rb
acceptance/setup/aio/pre-suite/045_EnsureMasterStartedOnPassenger.rb
acceptance/setup/common/pre-suite/000-delete-puppet-when-none.rb
acceptance/setup/common/pre-suite/025_StopFirewall.rb
acceptance/setup/common/pre-suite/040_ValidateSignCert.rb
acceptance/setup/common/pre-suite/110_SetPEPuppetService.rb
acceptance/tests/ensure_version_file.rb
configs/components/curl.rb
configs/components/leatherman.json

Notable updates:
- acceptance testing framework
- Leatherman bump to 10.1
- curl bump to 7.51.0

Merge LTS->stable

---

configs/platforms/fedora-f25-i386.rb
configs/platforms/fedora-f25-x86_64.rb

Builds correctly. Will update with runtime smoke testing shortly.

(PA-709) Add Fedora 25 platform (i386, x86_64)

---

configs/platforms/ubuntu-16.10-amd64.rb
configs/platforms/ubuntu-16.10-i386.rb

Builds correctly. Will update with runtime smoke testing shortly.

(PA-715) Add Ubuntu 16.10 platform (i386, x86_64)

---

ext/build_defaults.yaml

These targets should match the PE master platforms.

(maint) Fix targets for puppet-agent

---

configs/components/cpp-pcp-client.json

(maint) Bump cpp-pcp-client to 1.2.1

---

configs/components/facter.json
configs/components/puppet.json
configs/components/pxp-agent.json

For the upcoming puppet-agent 1.7.2 release

(PA-817) Pin facter, pxp-agent, puppet to tags

---

configs/components/leatherman.json

This commit updates the leatherman version to 0.10.2, which contains a
fix for a race condition on Solaris.

(maint) Bump leatherman to 0.10.2

---

configs/components/leatherman.json

Bump leatherman in stable to the 0.11.0 release which brings in the following enhancements:
- Add an option to use thread-safe forking in leatherman::execution (LTH-126)

(PA-943) Bump leatherman in stable to 0.11.0

---

configs/components/hiera.json
configs/components/marionette-collective.json
configs/components/pxp-agent.json

For the upcoming 1.9.2 release

(PA-954) Pin Hiera, MCO, pxp-agent to tags

---

configs/components/rubygem-gettext-setup.rb
configs/components/rubygem-locale.rb

This brings some updates to gettext-related tooling.

Merge stable -> master

---

Gemfile

This reverts commit 9715e493478e6c2ba45558a5a97facdbd6984815.

Revert "(PA-1057) Update vanagon default version to 0.11.1"

---

resources/windows/wix/localization/puppet_en-us.wxl

- Note in the Windows installer that master config is optional and
that Puppet will work standalone using this installer.

(PA-1132) Update Windows installer message

---

configs/components/puppet.json

Update the puppet component with a new tag for the 1.10.3 release

(PA-1198) Update puppet component with 4.10.3 tag

---

configs/components/hiera.rb
configs/components/puppet.rb
resources/windows/wix/appdatafiles.wxs
resources/windows/wix/properties.wxs.erb

This supersedes #1076 
Adding an additional commit to this to address preserving the hiera yaml files for windows.

(PA-1139 PA-1169) Install Hiera 5 config files

---

configs/components/leatherman.json
configs/components/puppet.json

This updates the puppet component ref to a SHA containing docs fixes,
and updates the leatherman component ref to the 1.0.0 tag.

(maint) Update puppet and leatherman component refs

---

acceptance/tests/ensure_hiera_config_version.rb

Check that the puppet and production hiera.yaml files
list version 5 for a new install

(PA-1169) add version check for hiera.yaml files

---

configs/components/facter.rb
configs/components/puppet-ca-bundle.rb
configs/platforms/fedora-f24-i386.rb
configs/platforms/fedora-f24-x86_64.rb
configs/platforms/fedora-f25-i386.rb
configs/platforms/fedora-f25-x86_64.rb
ext/build_defaults.yaml

Reverts puppetlabs/puppet-agent#1103

Revert "(CPR-391) Fedora packages have odd distro tag"

---

configs/components/augeas.rb
configs/platforms/debian-9-amd64.rb
configs/platforms/debian-9-i386.rb

It blends, I've done pretty thorough smoke testing with the agent packages this can generate.

(PA-1339) Add Debian 9 "Stretch" x86 platforms

---

configs/components/puppet.json

Update the puppet component to the 4.10.6 tag for the 1.10.6 release

(PA-1349) Update puppet component to tag

---

configs/components/curl.rb
configs/components/leatherman.rb
configs/projects/puppet-agent.rb
resources/patches/curl/curl-7.55.1-aix-poll.patch

Supports pxp-agent work that requires curl.

(PA-1447) Build curl on all platforms

---

configs/components/augeas.rb
resources/patches/augeas/src-pathx.c-parse_name-correctly-handle-trailing-ws.patch

This commit updates augeas to add a patch that resolves the security issues in
CVE-2017-2555

(PA-1417) Apply security fix for CVE-2017-2555 to augeas

---

configs/components/facter.rb
configs/components/libwhereami.json
configs/components/libwhereami.rb
configs/projects/puppet-agent.rb

No need to merge yet - still testing builds.

(PA-1460) Add libwhereami as a facter component

---

configs/components/augeas.rb

This commit updates the augeas component to 1.8.1

(PA-1417) Update augeas to 1.8.1

---

configs/components/ruby-2.4.1.rb
resources/files/ruby_241/rbconfig/rbconfig-powerpc64le-suse-linux.rb

This pulls up needed commits to get the sles 12 power8 platform to build.

Mergeup 5.1.x to 5.2.x

---

resources/windows/wix/service.pxp-agent.wxs.erb

Setup PATH and RUBYLIB to include all components for the pxp-agent
service on Windows.

(PA-1523) Update PATH/RUBYLIB for pxp-agent on Windows

---

configs/components/rubygem-win32-process.rb

Reverts puppetlabs/puppet-agent#1196

Revert "(PA-1569) Bump win32-process gem to 0.7.5"

---

configs/components/rubygem-win32-process.rb

Reverts puppetlabs/puppet-agent#1233
Originally reverted to wait for green CI, this is the original PR

(PA-1569) Bump win32-process gem to 0.7.5""

---

acceptance/tests/validate_vendored_ruby.rb

Previously, the vendored ruby tests failed on i386 and SPARC for Solaris 10,
and only i386 for Solaris 11 on the puppet-agent master pipelines. This
was due to the fact that the 5.3.x and master pipelines ship Ruby 2.4.2
with the agent. Unfortunately gcc 3.4.x, used on the failing Solaris
machines, does not work with Ruby 2.4.2. However gcc 4.x, used on
Solaris 11 SPARC (the passing case), does. This commit uses gcc 4.x for
all the Solaris platforms.

(PA-1699) Use gcc 4.x to compile sqlite3 gem on Solaris

---

configs/components/cpp-pcp-client.json
configs/components/leatherman.json
configs/components/marionette-collective.json
configs/components/pxp-agent.json

Merges the 5.3.3 tag so future builds will be "newer" than the last release.

Merge 5.3.3 release into 5.3.x branch

---

ext/build_defaults.yaml

This reverts commit 1bc5fba82baa5d4de7b5f58f51c3498730fb4e98.

Revert "Revert "(packaging) Update shipping defaults to work with new puppet5 repos""

---

configs/platforms/osx-10.13-x86_64.rb

Add platform config for macOS 10.13, using macOS 10.12 template.

(PA-1491) Add platform config for macOS 10.13.

---

configs/components/pxp-agent.rb

In PA-1850, it was found that when there is a system version of openssl
installed on Windows, then the pxp-agent will fail to start properly if
the user tries to restart it. Specifically, Puppet shows the service as
being in the "paused" state. The reason this happened is because when Windows
executes the pxp-agent.exe file, it searches for its required .dll files first
in the .exe file's directory, then in the system library directory
(e.g. C:\Windows:\System32), and then the custom PATH last (as a rough approximation,
it actually searches some other locations, but the relative ordering of ".exe directory"
=> "system library directory" => PATH is still there). See https://msdn.microsoft.com/en-us/library/7d83bc18.aspx
for more details. Since we do not have any .dll files in …

(PA-1850) Copy dependent .dll files to bin directory for pxp-agent

---

acceptance/tests/validate_vendored_ruby.rb

Attempting to require the puppet resource_api in the vendored ruby
acceptance tests failed on Windows cygwin hosts because Beaker was
unable to set RUBYLIB correctly in that context. This is a workaround;
BKR-1445 and BKR-986 exist to address this problem.

(PA-1989) Fix `RUBYLIB` in vendored ruby acceptance on Windows

---

acceptance/tests/validate_vendored_modules.rb
configs/components/_base-module.rb
configs/components/module-puppetlabs-mailalias_core.rb
configs/components/module-puppetlabs-maillist_core.rb
configs/projects/puppet-agent.rb

Also adds puppetlabs-mailalias_core and puppetlabs-maillist_core as
vendor module components

(PA-1998) Add vendor module base component

---

acceptance/tests/validate_vendored_ruby.rb
configs/platforms/solaris-10-i386.rb
configs/platforms/solaris-10-sparc.rb

Also added an opportunistic guard to pkgutil exit status for faster fails.

(maint) use artifactory for solaris10 mirror

---

acceptance/tests/validate_vendored_ruby.rb
configs/platforms/solaris-10-i386.rb
configs/platforms/solaris-10-sparc.rb

Includes the OpenCSW artifactory revert commit.

Mergeup 1.10.x to 5.3.x

---

configs/components/module-puppetlabs-zone_core.json
configs/components/module-puppetlabs-zone_core.rb
configs/projects/puppet-agent.rb

(maint) Add zone module to PA

---

Gemfile
README.md
configs/components/puppet-runtime.json
configs/components/puppet-runtime.rb
configs/projects/puppet-agent.rb

Merge up updates to puppet-runtime json file format

(maint) Merge up 5.3.x -> 5.5.x

---

configs/platforms/aix-6.1-ppc.rb
configs/platforms/aix-7.1-ppc.rb
configs/platforms/cisco-wrlinux-5-x86_64.rb
configs/platforms/cisco-wrlinux-7-x86_64.rb
configs/platforms/el-5-i386.rb
configs/platforms/el-5-x86_64.rb
configs/platforms/el-6-i386.rb
configs/platforms/el-6-s390x.rb
configs/platforms/el-6-x86_64.rb
configs/platforms/el-7-aarch64.rb
configs/platforms/el-7-ppc64le.rb
configs/platforms/el-7-s390.rb
configs/platforms/el-7-s390x.rb
configs/platforms/el-7-x86_64.rb
configs/platforms/eos-4-i386.rb
configs/platforms/fedora-26-x86_64.rb
configs/platforms/fedora-27-x86_64.rb
configs/platforms/osx-10.12-x86_64.rb
configs/platforms/osx-10.13-x86_64.rb
configs/platforms/redhatfips-7-x86_64.rb
configs/platforms/sles-11-i386.rb
configs/platforms/sles-11-s390x.rb
configs/platforms/sles-11-x86_64.rb
configs/platforms/sles-12-ppc64le.rb
configs/platforms/sles-12-s390x.rb
configs/platforms/sles-12-x86_64.rb
ext/build_defaults.yaml

This reverts commit 6d815014e701a5b30c78427e715b7207e35cdf8e. Other tooling isn't ready for these changes yet.

Revert "(PA-2070) Match RPM build paths to shipped repo paths"

---

ext/build_defaults.yaml

if nothing breaks we will hopefully be able to use packaging as a gem

(PA-2031) update build_defaults to use packaging 1.0.x

---

Gemfile
Rakefile
ext/build_defaults.yaml

Needs testing...~~I also need to make a puppet-agent specific ticket for this, when I do I will update the PR~~

(PA-2031) Update puppet-agent to use packaging as a gem

---

acceptance/tests/validate_vendored_modules.rb
configs/components/module-puppetlabs-yumrepo_core.json
configs/components/module-puppetlabs-yumrepo_core.rb
configs/projects/puppet-agent.rb

(maint) Add yumrepo module

---

acceptance/tests/validate_vendored_modules.rb
configs/components/module-puppetlabs-mount_core.json
configs/components/module-puppetlabs-mount_core.rb
configs/projects/puppet-agent.rb

Blocked on https://tickets.puppetlabs.com/browse/PUP-8813

(maint) Add mount_core module

---

configs/components/module-puppetlabs-scheduled_task.json
configs/components/module-puppetlabs-scheduled_task.rb
configs/projects/puppet-agent.rb

(maint) Add scheduled_task module to PA

---

resources/windows/wix/customactions.wxs.erb

Depends on #1489 being merged first.

(PA-2113) Guard Windows permissions resetting code

---

README.md

(doc) fixed a typo in utility

---

Gemfile
configs/components/facter.rb
configs/components/runtime.rb
configs/platforms/osx-10.12-x86_64.rb

WIP: changed project osx-10.12 template to use hombrew in the context of a test user
This is still work in progress but it would be good if you have a look on it.
Related PR's:
https://github.com/puppetlabs/vanagon/pull/587
https://github.com/puppetlabs/puppet-runtime/pull/113

(PA-1272) Refactor our use of homebrew to not run as root

---

configs/components/cleanup.rb

These binaries can interfere with natively distributed curl on more
recent Windows releases when the path includes puppet-agent's bindir.

(PA-2319) Remove curl binaries from Windows packages

---

.gitattributes
azure-pipelines.yml
docker/Gemfile

Follow-on PR will do the heavy lifting of building / testing

(maint) Enable azure pipelines

---

ext/build_defaults.yaml

This PR depends on: https://github.com/puppetlabs/puppet-agent/pull/1595

(PA-2233) Add Fedora 29 to build_defaults

---

configs/components/cpp-hocon.rb
configs/components/cpp-pcp-client.rb
configs/components/facter.rb
configs/components/leatherman.rb
configs/components/libwhereami.rb
configs/components/puppet.rb
configs/components/pxp-agent.rb
configs/components/runtime.rb
configs/platforms/el-8-x86_64.rb
configs/projects/puppet-agent.rb

I need to run the pipeline but seems that i have an issue with beaker-hostgenerator and the builds are not running.
Till then have a look and let me know what you think.
This is using @ekinanp changes from leatherman and build with GCC 8.2
Is dependent ob: https://tickets.puppetlabs.com/browse/PA-2334

(PA-2325) Add el-8-x86_64

---

ext/build_defaults.yaml

PR depends on: https://github.com/puppetlabs/puppet-agent/pull/1605

(PA-2327) Update build_defaults.yaml to enable RHEL8 (x86_64)

---

configs/components/leatherman.json

Updates leatherman to v1.4.5 to support builds on redhat 8

(PA-2398) Update leatherman; 1.4.4 -> 1.4.5

---

azure-pipelines.yml

- Ensures .gitattributes apply properly when changes are made

(maint) Clean source repo on Azure checkout

---

.travis.yml
configs/components/cpp-hocon.rb
configs/components/cpp-pcp-client.rb
configs/components/facter.rb
configs/components/leatherman.rb
configs/components/libwhereami.rb
configs/components/puppet.rb
configs/components/pxp-agent.rb
configs/components/runtime.rb
configs/platforms/el-8-x86_64.rb
configs/platforms/osx-10.12-x86_64.rb
configs/projects/puppet-agent.rb
ext/build_defaults.yaml

This one was a little fiddly -- I'll run PR tests on it before I unblock it.

Merge up 5.5.x to 6.0.x

---

configs/components/facter.rb
configs/components/runtime.rb
configs/platforms/osx-10.14-x86_64.rb

Depends on PR https://github.com/puppetlabs/puppet-runtime/pull/122

(PA-2219) Add OSX 10.14 to puppet-agent

---

configs/components/cpp-hocon.rb
configs/components/cpp-pcp-client.rb
configs/components/facter.rb
configs/components/leatherman.rb
configs/components/libwhereami.rb
configs/components/pxp-agent.rb
configs/components/runtime.rb
configs/platforms/fedora-29-x86_64.rb
configs/platforms/osx-10.12-x86_64.rb
configs/platforms/osx-10.13-x86_64.rb
configs/platforms/osx-10.14-x86_64.rb
ext/build_defaults.yaml

Not entirely confident this is correct; I'll unblock once PR tests pass

(maint) Merge up 5.5.x to 6.0.x

---

azure-pipelines.yml
docker/ci/build.ps1
ext/smoke/README.md
ext/smoke/helpers.sh
ext/smoke/packages/run-smoke-test.sh
ext/smoke/repos/run-smoke-test.sh

Not sure if this is handled by automation, but put up to pick up some of the Docker changes we wanted to make.
Thanks!
I believe #1645 is not relevant and can be closed?

6.0.x mergeup to master

---

configs/components/leatherman.rb

Reverts puppetlabs/puppet-agent#1652

Revert "(maint) Update pl-cmake on Solaris to version 3.12.4"

---

configs/components/cpp-hocon.rb
configs/components/cpp-pcp-client.rb
configs/components/facter.rb
configs/components/leatherman.rb
configs/components/libwhereami.rb
configs/components/puppet.rb
configs/components/pxp-agent.rb
configs/components/runtime.rb
configs/platforms/debian-10-amd64.rb
configs/platforms/osx-10.12-x86_64.rb
configs/platforms/osx-10.13-x86_64.rb
configs/platforms/osx-10.14-x86_64.rb
configs/projects/puppet-agent.rb

The only conflict was with `configs/components/puppet.json`

(maint) Merge 6.0.x -> 6.4.x

---

configs/components/puppet-runtime.json

(maint) Update puppet-runtime to 201904250

---

Gemfile

This pull request contains two patches:
- Allow VANAGON_LOCATION and PACKAGING_LOCATION to pull from HTTPS sources in addtion to SSH sources.
- Add support for Gemfile.local.

(maint) Improve Gemfile

---

configs/components/facter.rb

(PA-2671) Build Facter with JRuby tag on

(PA-2671) Build Facter with JRuby tag on

---

ext/build_defaults.yaml

see individual commit messages for details

(PA-2702) Add redhatfips-7-x86_64 to `rpm_targets`

---

ext/build_defaults.yaml

(PA-2679) Update build_defaults with Fedora 30

---

configs/platforms/debian-8-amd64.rb
configs/platforms/debian-8-i386.rb

cherry pick for 708091fbf48f78850700fceb5d10df212d967c1b

(PA-2752) Temporarily confine python3.4 on Jessie

---

configs/components/facter.rb

merge after https://github.com/puppetlabs/facter/pull/1812

PA-2807 Enable Facter jruby support for Debian 10

---

configs/components/leatherman.json

Manually update leatherman. 
It seems like leatherman was updated during the CI run, so the CI is currently stuck

(maint) Update leatherman to 11a942a82ee7fecdf1b9313d2776ee4a08321e6e

---

docker/Makefile

* puppetlabs/6.4.x:
(maint) Update puppet to e698e682261ba3c15cd80f0fc30749a575d13c6a
(maint) Update pxp-agent to e3e910cc6dc30bb89625c89accdfcb7d052b2e0e
(maint) Update puppet-runtime to 201909120
(maint) Update puppet-runtime to 201909120
(maint) Update pxp-agent to d0b10a5efe32ed4df98e8aac5d6dca107e28e3b6
(maint) Update puppet to da8de973bac4ea1aa160f50c87b97f5b8c0e95bc
(maint) add pupperware as codeowner of 'docker' directory
(maint) Add `LATEST_VERSION` parameter for more configurability
(maint) Clean up nightly container build remnants
#	CODEOWNERS
#	configs/components/puppet.json
#	configs/components/pxp-agent.json
#	docker/Makefile
fcd8b59

(maint) Merge 6.4.x -> master

---

ext/smoke/helpers.sh

This PR forces $releasever to 7.
Without this fix, the tests will try to install packages from https://download.postgresql.org/pub/repos/yum/10/redhat/rhel-7Server-x86_64/repodata/repomd.xml - a repository that does not exist.
In redhat systems, the $releasever is set to `7Server` (https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/6/html/deployment_guide/sec-using_yum_variables), yet postgresql upstream repos make the assumption that it is set to 7.

(maint) set postgresql repo $releasever

---

azure-pipelines.yml

- Set reasonable upper bounds for various stages in Azure to abort
jobs quickly when Docker misbehaves

(maint) Add Azure step timeouts

---

configs/platforms/solaris-11-i386.rb
configs/platforms/solaris-11-sparc.rb

This reverts commit bc3aa34ba9732412e6e58c806e603d1e6cc0561f.

Revert "(maint) Remove solarisstudio"

---

configs/components/cleanup.rb
configs/components/cpp-hocon.json
configs/components/cpp-hocon.rb
configs/components/cpp-pcp-client.json
configs/components/cpp-pcp-client.rb
configs/components/facter-precompiled-gem.rb
configs/components/facter.rb
configs/components/leatherman.rb
configs/components/libwhereami.rb
configs/components/puppet.rb
configs/components/pxp-agent.rb
configs/components/runtime.rb
configs/platforms/aix-7.1-ppc.rb
configs/projects/puppet-agent.rb

use cpp-pcp-client from 1.6.x branch
bump cpp-hocon to 0.2.0
merge-down cleanup component
use shared boost except windows
build aix7.1 on aix6.1 platform

(PUP-10166) support openssl-1.1.1/boost-1.67 

---

acceptance/tests/validate_vendored_ruby.rb

This reverts commit c620d1abbc3b45832893caa0174cfb27bad08b82, reversing
changes made to 84c99712a57bab29d91fc5269d44645d87e7c7aa.

Revert "Merge pull request #1843 from mihaibuzgau/5.5.x"

---

acceptance/tests/validate_vendored_ruby.rb

This comment seems to have been left over.

(main) OPS-15487 is resolved

---

resources/windows/wix/localization/puppet_en-us.wxl
resources/windows/wix/ui/WarningDlg.wxs
resources/windows/wix/ui/WixUI_PuppetInstallDir.wxs.erb

This PR adds a warning dialog for Windows 2008 and 2008R2 stating that support for it will end after  Microsoft EOLs it

(PA-3018) Add warning for Win2008

---

acceptance/tests/selinux.rb
configs/platforms/el-8-x86_64.rb

This PR adds a test to check if `selinux` can be required.

(PA-3067) Add selinux test

---

configs/components/facter.rb
configs/components/pxp-agent.rb

depends on https://github.com/puppetlabs/facter/pull/1873 and https://github.com/puppetlabs/pxp-agent/pull/781

(PA-3025) disable dynamicbase on windowsfips

---

ext/build_defaults.yaml

(PA-3132) Nightly ship Ubuntu 20.04 internally

---

.travis.yml
configs/projects/puppet-agent.rb

This will pull in build metadata from the runtime.

(maint) Add ability to load upstream metadata

---

configs/components/puppet-runtime.json
configs/projects/puppet-agent.rb

There are some conflicts so doing this merge manually

Merge 5.5.x -> master

---

configs/components/puppet-runtime.rb
configs/platforms/sles-15-x86_64.rb

Depends on https://github.com/puppetlabs/puppet-runtime/pull/346

(PA-3006) Vendor boost and yaml-cpp on SLES 15

---

ext/smoke/helpers.sh
ext/smoke/packages/steps/setup-master.sh

- use `identify_master` only on repo smoke
- update reading of `route_file` config setting

(PA-3280) update tests

---

configs/components/facter.rb
configs/platforms/fedora-32-x86_64.rb

depends on: https://github.com/puppetlabs/facter/pull/1995

(PA-3214) add fedora32 platform

---

configs/components/facter.json
configs/components/puppet.json

* pl/master:
(maint) Update facter to ff8fc2fbb69e163cddb860b022e6eca98329cc1d
(PA-3214) add fedora32 platform
(maint) Update puppet to 19b347c79bd4c867c0f138ce67dfabad14964947
(maint) Update puppet to f1c74401cb8e0aef4f123bd858823ad3e820f191
(maint) Update puppet to 86c3c1b004320710aed5be3a7b3735b6a474059e
(maint) Update puppet to be837588fa95918e03fc4c77ffb0f25a91cdaa54
(maint) Update facter to 9f9a1b13887cbd25ffbf644746932a77f116aadd
(maint) Update puppet to 2be0923be88115a42ed69af6085f45787ec916eb
(maint) Update puppet to 464591cfe58dd18a874590dd8e973f8ba6fbc555
(maint) Update puppet to 6cd3a4fbfff3bdb18ded55ae14f2dadf976a5dbb
(maint) Update facter to 46ddc08bd1bf9fbe5df0a5664bf1e107ecd1f9dc
(maint) Update puppet-runtime to 202007210
(maint) Update puppet-runtime to 202007210
(maint) …

(maint) Merge up master to next

---

acceptance/lib/puppet/acceptance/fact_dif.rb
acceptance/tests/ensure_facter_3_and_facter_4_output_matches.rb
configs/components/facter-ng.rb

Facter bump and facter diff acceptance test corrections

(maint) Bump facter-ng to 4.0.42

---

acceptance/tests/puppet_facts.rb

test was previously testing facter -p

(FACT-2158) Add puppet facts show test

---

ext/release-lead.rake

Update release_lead:check_components_diff task
to handle components versions from an archived
package.

(PA-3437) update release_lead:check_components_diff

---

resources/windows/wix/customactions.wxs.erb
resources/windows/wix/sequences.wxs.erb
resources/windows/wix/ui/PuppetInstallDirDlg.wxs

it should behave like alias to existing PUPPET_MASTER_SERVER

(PA-3440) add new property PUPPET_SERVER

---

configs/platforms/aix-7.1-ppc.rb
ext/build_defaults.yaml

This if intermediary step of AIX6.1 removal on main and master

(PA-3435) update configuration to build on AIX7.1 in master

---

configs/components/cpp-pcp-client.rb
configs/components/leatherman.rb
configs/components/puppet.rb
configs/components/pxp-agent.rb
configs/components/runtime.rb

passing ad-hoc: https://jenkins-master-prod-1.delivery.puppetlabs.net/view/Adhoc/job/platform_puppet-agent-extra_puppet-agent-integration-suite_adhoc-ad_hoc/886/

(PA-3435) update puppet components to build on AIX7.1

---

configs/components/leatherman.rb

See https://github.com/puppetlabs/leatherman/pull/327 for context.

(PA-3474) Disable dynamicbase for leatherman on windowsfips

---

ext/build_defaults.yaml

* commit '09f1676902c7d552a30307c521131930106e3f74':
(maint) stop aix-6.1 promotion to PE
Conflicts:
ext/build_defaults.yaml

(maint) Merge 5.5.x to master

---

configs/components/pxp-agent.rb

More info: https://github.com/puppetlabs/pxp-agent/pull/824

(PA-3491) Install configfile for OS X log rotation

---

ext/smoke/helpers.sh
ext/smoke/packages/steps/setup-master.sh
ext/smoke/steps/setup-agent.sh

Replace builds.puppetlabs.lan with builds.delivery.puppetlabs.net.

(maint) Rename builds.puppetlabs.lan

---

configs/platforms/debian-10-armhf.rb

Add direct compiling for debian 10 armhf

---

configs/platforms/debian-11-amd64.rb
ext/build_defaults.yaml

CI passes with the following PRs:
- https://github.com/puppetlabs/facter/pull/2396 (facter 3)
- https://github.com/puppetlabs/facter/pull/2397 (facter 4)

(PA-3711) Add Debian 11 amd64 platform

---

configs/components/cpp-hocon.rb
configs/components/cpp-pcp-client.rb
configs/components/facter.rb
configs/components/leatherman.rb
configs/components/libwhereami.rb
configs/components/puppet.rb
configs/components/pxp-agent.rb
configs/components/runtime.rb
configs/platforms/ubuntu-18.04-aarch64.rb
configs/projects/puppet-agent.rb
ext/build_defaults.yaml

Was able to build this locally

(PA-3874) Add Ubuntu 18.04 aarch64 platform definition - 6.x

---

acceptance/Rakefile
acceptance/tests/facter_output/puppet_facts_output.rb

Rake task to get facts from specific platform using specific puppet-agent SHA

(PA-4043) rake task to get facts

---

acceptance/Gemfile

update acceptance/Gemfile location_for to accept https git URLs

(maint) update acceptance/Gemfile location_for

---

ext/release-lead.rake

Before this commit only pxp-agent component information was read
from pxp-agent-vanagon project metadata
After this commit we read the component information from pxp-agent-vanagon
for a hardcoded list of components

(maint) fix release_lead:check_components_diff task

---

acceptance/Rakefile

* remove the hosts.yaml generation since this is not needed in CI
* add option to ship the json files

(PA-4089) make acceptance:facts task CI friendly

---

ext/build_defaults.yaml

Waiting on pipelines to run successfully before merging.

(PA-4122) Update build_defaults.yaml with RedHat 9

---

configs/components/hiera.json

- (maint) Pin to previous released hiera

(maint) Pin to previous released hiera

---

Rakefile

Backports f693074fd to 6.x
The TRAVIS_COMMIT_RANGE environment variable uses triple dots to describe the
range[1]. When that is used in `git log base...HEAD`, then it will include all
commits that are not in both A and B. That means we will include commits in the
base branch that are unrelated to the PR.
For now, do what puppet does to convert triple dots to double dots. In the
future, use GITHUB_BASE_REF to determine the range of commits.
[1] https://github.com/travis-ci/travis-ci/issues/4596
(cherry picked from commit f693074fdc3060f9ed6d663aeef1901cc35ff634)

(maint) Replace triple dots in TRAVIS_COMMIT_RANGE with double dots

---

acceptance/tests/ensure_facter_3_and_facter_4_output_matches.rb

OSX 11, 12 have a known bug for facter 3 that we need to update a test for.

(maint) Patch acceptance test for osx 12 issue

---

configs/platforms/fedora-36-x86_64.rb
configs/projects/puppet-agent.rb

Currently, puppet-agent#main is failing due and changes made on 6.x will help resolve it.

(maint) Mergeup changes from 6.x to main

---

configs/platforms/fedora-32-x86_64.rb

It's already been dropped in CI

(PA-4275) Remove Fedora 32

---

configs/components/puppet-resource_api.json

In preparation for tagging 1.8.16

(maint) Update puppet-resource_api to 4ed60f05a048f16689a32ddc23515536e0f5ded8

---

configs/components/hiera.json
configs/platforms/solaris-10-sparc.rb
configs/projects/puppet-agent.rb

Accepting the minor spelling differences in the Solaris 10 SPARC platform definition so this doesn't come up again.

Manual 6.x mergeup

---

configs/components/puppet.rb

(PA-4080) Remove old replaces & provides for puppet-common

---

configs/platforms/solaris-11-i386.rb
configs/platforms/solaris-11-sparc.rb

This reverts commit 596a1f98df46703d389aee5e44273be68e6ed622.

Revert "(maint) Update Solaris 11 publisher"

---

configs/platforms/osx-13-x86_64.rb

added platform support for macos-13(x86_64)

(PA-4594) added macos13(x86_64) platform

---

acceptance/tests/validate_vendored_ruby.rb

Compiling native extensions for the sqlite3 gem fails for Solaris currently because it attempts to use a compilation flag not understood by the version of GCC we use on Solaris.
This commit installs the OpenCSW version of GCC on Solaris to enable the compilation of native extensions for the sqlite3 gem.

(PA-5665) Install OpenCSW GCC on Solaris

---

configs/components/module-puppetlabs-augeas_core.json

This commit updates the augeas_core module to v1.4.0, which includes adding the frozen string magic comment to the augeas feature.

(PA-5722) Update augeas_core module

---

configs/platforms/el-9-aarch64.rb

puppet-agent build : https://jenkins-platform.delivery.puppetlabs.net/job/platform_vanagon-generic-builder_vanagon-packaging_generic-builder/2350/

(PA-5735) Add RedHat9(ARM64) platform definition to main

---

acceptance/tests/validate_vendored_ruby.rb

facter: https://jenkins-platform.delivery.puppetlabs.net/view/puppet-agent/view/ad-hoc/job/platform_puppet-agent-extra_puppet-agent-integration-suite_adhoc-ad_hoc/RMM_COMPONENT_TO_TEST_NAME=facter,SLAVE_LABEL=k8s-beaker,TEST_TARGET=aix73-POWERfa%257Bpackaging_platform=aix-7.2-power%257D/1232/
puppet-agent: https://jenkins-platform.delivery.puppetlabs.net/view/puppet-agent/view/ad-hoc/job/platform_puppet-agent-extra_puppet-agent-integration-suite_adhoc-ad_hoc/RMM_COMPONENT_TO_TEST_NAME=puppet_agent,SLAVE_LABEL=k8s-beaker,TEST_TARGET=aix73-POWERfa%257Bpackaging_platform=aix-7.2-power%257D/1232/
puppet: https://jenkins-platform.delivery.puppetlabs.net/view/puppet-agent/view/ad-hoc/job/platform_puppet-agent-extra_puppet-agent-integration-suite_adhoc-ad_hoc/1225/RMM_COMPONENT_TO_TEST_NAME=puppe …

(PA-5927) Skip failing test for AIX7.3-power

---

configs/platforms/amazon-2023-aarch64.rb
configs/platforms/amazon-2023-x86_64.rb

Added platform file for amazon linux 2023

[PA-5570] Added platform file for amazon 2023 aarch64 & amd64

---

.github/workflows/jira.yml

This reverts commit 57516135928fee4a23b35e6ab632b59c81db9efd, reversing changes made to 1351e4170e4bd727f0ed2ebe2f0dd56755fe1c1f.

Revert "Merge pull request #2424 from joshcooper/label_pulls"

---

configs/components/module-puppetlabs-cron_core.json

See https://github.com/puppetlabs/puppetlabs-cron_core/blob/v1.2.1/CHANGELOG.md#v121-2023-11-28

(maint) Update cron_core to v1.2.1

---

configs/platforms/osx-14-arm64.rb

[vanagon generic builder](https://jenkins-platform.delivery.puppetlabs.net/view/vanagon-generic-builder/job/platform_vanagon-generic-builder_vanagon-packaging_generic-builder/2573/)

(PA-5908) Add macos14 ARM platform definition

---

configs/platforms/debian-11-amd64.rb
configs/platforms/debian-12-aarch64.rb
configs/platforms/debian-12-amd64.rb

(PA-5763) add debian 12 platforms for 7.x

---

acceptance/config/aio/options.rb
acceptance/teardown/common/099_Archive_Logs.rb

(PA-4154) Add post-suite step to archive logs

---

acceptance/tests/validate_vendored_ruby.rb

This reverts commit 7cb629e35cf2647fe03034e7986ec76003d25c6f.

Revert "Upgrade AlmaLinux release package"

---

ext/build_defaults.yaml

https://github.com/puppetlabs/ci-job-configs/pull/9355

(PA-5555) add debian-12-amd64 to foss build_defaults

---

configs/components/module-puppetlabs-augeas_core.json
configs/components/module-puppetlabs-cron_core.json
configs/components/module-puppetlabs-host_core.json
configs/components/module-puppetlabs-mount_core.json
configs/components/module-puppetlabs-selinux_core.json
configs/components/module-puppetlabs-sshkeys_core.json
configs/components/module-puppetlabs-zfs_core.json
configs/components/module-puppetlabs-zone_core.json

This commit updates all core modules. The notable changes from these new modules are mainly:
- Removal of concurrent-ruby as a dependency to avoid issues with Puppet
- Support for Amazon Linux
(cherry picked from commit d5cca1aa222ca316af870ce9d8d474b69f5d1c37)

Update core modules

---

configs/components/pxp-agent.rb
configs/platforms/sles-11-x86_64.rb

Vanagon Generic builder : https://jenkins-platform.delivery.puppetlabs.net/job/platform_vanagon-generic-builder_vanagon-packaging_generic-builder/BUILD_TARGET=ubuntu-18.04-amd64,SLAVE_LABEL=k8s-worker/2757/

(PA-6003) Add SLES 11 (x86_64) platform definition to puppet-agent-main

---

configs/platforms/el-9-ppc64le.rb

Added el-9-ppc64le platform for puppet-agent

(PA-6381): Added el-9-ppc64le platform for puppet-agent
